begin;
insert into auth.users(id,instance_id,aud,role,email,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
values('19000000-0000-4000-8000-000000000001','00000000-0000-0000-0000-000000000000','authenticated','authenticated','qa-rules-fix19@example.invalid',now(),'{"provider":"email","providers":["email"]}','{"nombre":"QA","apellidos":"FIX19","fecha_nacimiento":"1990-01-01"}',now(),now());
insert into public.kombax_account_private_r117(perfil_id,fecha_nacimiento) values('19000000-0000-4000-8000-000000000001','1990-01-01') on conflict(perfil_id) do update set fecha_nacimiento='1990-01-01';
select set_config('request.jwt.claim.sub','19000000-0000-4000-8000-000000000001',true);
set local role authenticated;
do $test$
declare r jsonb; d uuid; s uuid; p uuid; ev uuid; stage text; blocked boolean; checks jsonb:='[]'; q jsonb;
begin
stage:='free_account';
if exists(select 1 from public.app_kombax_social_mis_perfiles_r117(null)) then raise exception 'UNEXPECTED_PUBLIC_PROFILE';end if;
perform public.app_kombax_social_estado_v124(null);
select id into p from public.app_kombax_social_feed_v238(null,null,null,20) where audiencia='publica' limit 1;
if p is null then raise exception 'NO_PUBLIC_FIXTURE';end if;
perform public.app_kombax_social_directorio_v072('',10);
perform public.app_kombax_showcase_list_v054('',null,null,null,10);
perform public.app_kombax_eventos_visible_page_v236();
r:=public.app_kombax_commercial_purchase_eligibility_r63();
if (r->>'eligible')::boolean is not true then raise exception 'FREE_ADULT_PURCHASE_INELIGIBLE';end if;
checks:=checks||jsonb_build_array('free account without public profile: Social feed/directory, Showcase, Events and purchase eligibility');
stage:='spectator';
r:=public.app_kombax_perfil_mutate_r58('kombax.profile.save','{"tipo":"espectador","nombre_publico":"QA spectator FIX19"}',gen_random_uuid());
d:=(r#>>'{data,id}')::uuid;
select id into s from public.app_kombax_social_mis_perfiles_r117(null) where perfil_directo_id=d;
if s is null then raise exception 'SPECTATOR_SOCIAL_MISSING';end if;
perform public.app_kombax_social_mutate_v123('kombax.social.like',jsonb_build_object('publicacion_id',p,'activo',true),gen_random_uuid());
perform public.app_kombax_social_mutate_v123('kombax.social.guardar',jsonb_build_object('publicacion_id',p,'activo',true),gen_random_uuid());
perform public.app_kombax_social_mutate_v123('kombax.social.comentar',jsonb_build_object('publicacion_id',p,'autor_social_id',s,'texto','QA spectator comment reverted'),gen_random_uuid());
blocked:=false;
begin perform public.app_kombax_social_mutate_v123('kombax.social.publicar',jsonb_build_object('autor_perfil_id',s,'tipo','actualizacion','texto','QA FORBIDDEN spectator','audiencia','publica'),gen_random_uuid());
exception when others then if SQLERRM like '%NOT_ALLOWED%' or SQLERRM like '%FORBIDDEN%' or SQLERRM like '%NOT_ENABLED%' then blocked:=true;else raise;end if;end;
if not blocked then raise exception 'SPECTATOR_PUBLISHED';end if;
checks:=checks||jsonb_build_array('spectator: like, save, comment allowed; publish denied by server');
for stage in select unnest(array['marca','federacion','profesional','media']) loop
 r:=public.app_kombax_perfil_mutate_r58('kombax.profile.save',jsonb_build_object('tipo',stage,'nombre_publico','QA unverified FIX19 '||stage),gen_random_uuid());
 d:=(r#>>'{data,id}')::uuid;
 select id into s from public.app_kombax_social_mis_perfiles_r117(null) where perfil_directo_id=d;
 blocked:=false;
 begin perform public.app_kombax_social_mutate_v123('kombax.social.publicar',jsonb_build_object('autor_perfil_id',s,'tipo','actualizacion','texto','QA forbidden unverified','audiencia','publica'),gen_random_uuid());
 exception when others then if SQLERRM like '%NOT_ALLOWED%' or SQLERRM like '%FORBIDDEN%' then blocked:=true;else raise;end if;end;
 if not blocked then raise exception 'UNVERIFIED_PUBLISHED %',stage;end if;
 checks:=checks||jsonb_build_array('unverified '||stage||': publish denied by server');
end loop;
stage:='competitor';
r:=public.app_kombax_perfil_mutate_r58('kombax.profile.save','{"tipo":"competidor","nombre_publico":"QA competitor FIX19","disciplinas":["Boxeo"]}',gen_random_uuid());d:=(r#>>'{data,id}')::uuid;
if r#>>'{data,verificacion_estado}'<>'verificado' then raise exception 'PILOT_SLOT_NOT_AVAILABLE';end if;
perform public.app_kombax_social_mutate_v123('kombax.social.direct.activate',jsonb_build_object('perfil_directo_id',d,'acepta_normas',true,'acepta_privacidad',true),gen_random_uuid());
select id into s from public.app_kombax_social_mis_perfiles_r117(null) where perfil_directo_id=d;
r:=public.app_kombax_social_mutate_v123('kombax.social.publicar',jsonb_build_object('autor_perfil_id',s,'tipo','actualizacion','texto','QA verified competitor reverted','audiencia','publica'),gen_random_uuid());
if r#>>'{data,id}' is null then raise exception 'COMPETITOR_POST_MISSING';end if;
checks:=checks||jsonb_build_array('verified pilot competitor after explicit terms: Social publish allowed');
stage:='competitor_event';
if not exists(select 1 from public.app_kombax_eventos_mis_organizadores_v160() where sujeto_id=d and puede_organizar) then raise exception 'COMPETITOR_ORGANIZER_MISSING';end if;
r:=public.app_kombax_eventos_mutate_v253('event.save',jsonb_build_object('sujeto_tipo','perfil_directo','sujeto_id',d,'nombre','QA_FIX19_EVENT_ROLLBACK','tipo','seminario','estado','borrador','fecha_inicio','2026-12-01T10:00:00Z','fecha_fin','2026-12-01T12:00:00Z','pais','España','municipio','Girona'),gen_random_uuid());
ev:=(r#>>'{data,id}')::uuid;if ev is null then raise exception 'EVENT_NOT_CREATED';end if;
stage:='publication_request';
r:=public.app_kombax_commercial_activation_request_r64('direct_profile',d,'EVENT_PUBLICATION',ev,7,gen_random_uuid());
if r->>'status'<>'requested' or (r->>'payment_activation_performed')::boolean then raise exception 'EVENT_ACTIVATION_UNEXPECTED';end if;
stage:='ticketing_request';
r:=public.app_kombax_event_ticketing_service_request_r628(ev,gen_random_uuid());
if r#>>'{data,status}'<>'requested' then raise exception 'TICKETING_NOT_REQUESTED %',r;end if;
checks:=checks||jsonb_build_array('competitor without Club plan: event draft, punctual publication and Ticketing requests allowed, no charge');
perform set_config('kombax.qa_competitor19',d::text,true);
perform set_config('kombax.qa_rules19',jsonb_build_object('checks',checks,'role',current_user,'rollback',true,'stripe_calls',0)::text,true);
exception when others then raise exception 'QA_FIX19_STAGE_%: %',stage,SQLERRM;
end $test$;
reset role;
update public.perfiles_kombax_directos set verificacion_estado='pendiente',workflow_estado='submitted' where id=current_setting('kombax.qa_competitor19')::uuid;
set local role authenticated;
do $denied$
declare s uuid; blocked boolean:=false;
begin
select id into s from public.app_kombax_social_mis_perfiles_r117(null) where perfil_directo_id=current_setting('kombax.qa_competitor19')::uuid;
begin perform public.app_kombax_social_mutate_v123('kombax.social.publicar',jsonb_build_object('autor_perfil_id',s,'tipo','actualizacion','texto','QA competitor unverified rejected','audiencia','publica'),gen_random_uuid());
exception when others then if SQLERRM like '%NOT_ALLOWED%' or SQLERRM like '%FORBIDDEN%' then blocked:=true;else raise;end if;end;
if not blocked then raise exception 'UNVERIFIED_COMPETITOR_PUBLISHED';end if;
if exists(select 1 from public.app_kombax_eventos_mis_organizadores_v160() where sujeto_id=current_setting('kombax.qa_competitor19')::uuid and puede_organizar) then raise exception 'UNVERIFIED_COMPETITOR_ORGANIZES';end if;
perform set_config('kombax.qa_rules19',(current_setting('kombax.qa_rules19')::jsonb||jsonb_build_object('unverified_competitor_publish_and_organize_denied',true))::text,true);
end $denied$;
select current_setting('kombax.qa_rules19')::jsonb as result;
rollback;
