import { repos } from '../core/repositories.js';
import { backend } from '../core/backend.js';
import { state } from '../core/state.js';
import { has, rolesLabel } from '../core/permissions.js';
import { esc, dtFmt, isoDate, monthStart, sleep } from '../core/utils.js';
import { pageHeader, hero, quickRow, card, table, empty, badge, metric, openForm, toast, setError, setMainHtml } from '../ui/components.js';
import { icon } from '../ui/icons.js';
import { CLUB_THEMES, themeDefinition } from '../core/platform.js';
import { performanceSnapshot } from '../core/query-cache.js';
import { openKombaxPublicProfile } from './public-profile.js';
import { openPrivacyConditions } from './help-legal.js';
import { openAuthenticatedPasswordChange } from './account-security.js';

const bind=(selector,fn)=>document.querySelectorAll(selector).forEach(el=>el.addEventListener('click',()=>fn(el.dataset.id,el)));
const nativeNotificationState=()=>{try{return String(window.UrbanWarriorsNative?.getNotificationPermissionState?.()||'web')}catch{return 'web'}};

export async function renderUsers(){
  setMainHtml('<div class="loading-card">Cargando equipo…</div>');
  try{
    const canCodes=['direccion','coordinacion'].includes(state.session?.rol);
    const [members,codes,requests]=await Promise.all([repos.users.members(),canCodes?repos.accessCodes.get():Promise.resolve(null),canCodes?repos.users.teamRequests():Promise.resolve([])]);
    const grouped=new Map();for(const m of members){const key=m.perfil_id||m.perfiles?.id||m.id;const g=grouped.get(key)||{...m,roles:[],coord:false};g.roles.push(m.rol);g.coord=g.coord||m.coordinacion===true;g.activo=g.activo||m.activo;grouped.set(key,g);}
    const memberCards=[...grouped.values()].map(m=>{const roleText=m.coord?'Coordinación':rolesLabel(m.roles);return quickRow(icon(m.coord?'shieldCheck':'user'),`${m.perfiles?.nombre||''} ${m.perfiles?.apellidos||''}`.trim()||'Miembro',`${roleText} · ${m.perfiles?.telefono||'sin teléfono'} · alta ${dtFmt(m.creado_en)}`,badge(m.activo?'Activo':'Inactivo',m.activo?'ok':'neutral'))}).join('');
    const teamCode=codes?.equipo?.codigo||'—';
    const codeCard=canCodes?card('Código de acceso del equipo',hero({kicker:'CÓDIGO DEL CLUB',title:`${teamCode}`,body:'Código reutilizable de 4 o 5 dígitos. Puedes compartirlo con futuros miembros del equipo. Usarlo solo crea una solicitud pendiente: nunca concede permisos automáticamente.',dark:true,actions:`<button class="btn btn-primary" id="copy-team-access-code">Copiar código</button><button class="btn btn-ghost" id="rotate-team-access-code">Cambiar código</button>`})):'';
    const reqRows=(requests||[]).map(r=>{const name=`${r.nombre||''} ${r.apellidos||''}`.trim()||r.email||'Cuenta KOMBAX';const role=r.coordinacion?'Coordinación':(r.rol_asignado?rolesLabel([r.rol_asignado]):'Pendiente de asignar');return `<tr><td><strong>${esc(name)}</strong><br><small>${esc(r.email||'')}</small></td><td>${badge(r.estado,r.estado==='aprobada'?'ok':r.estado==='pendiente'?'warn':'neutral')}</td><td>${esc(role)}</td><td>${dtFmt(r.creado_en)}</td><td>${canCodes&&r.estado==='pendiente'?`<div class="row-actions"><button class="btn btn-primary btn-sm approve-team-request" data-id="${esc(r.id)}">Aprobar</button><button class="btn btn-ghost btn-sm reject-team-request" data-id="${esc(r.id)}">Rechazar</button></div>`:'—'}</td></tr>`});
    setMainHtml(`${pageHeader('Equipo','Personas, roles y acceso del equipo','','Administración')}<div class="grid-2">${card('Equipo activo',memberCards||empty('Sin miembros'))}${codeCard}</div>${canCodes?card('Solicitudes de acceso al equipo',reqRows.length?table(['Persona','Estado','Rol','Solicitud','Acciones'],reqRows):empty('No hay solicitudes pendientes')):''}`);
    document.getElementById('copy-team-access-code')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(teamCode);toast('Código de equipo copiado')}catch{prompt('Copia el código',teamCode)}});
    document.getElementById('rotate-team-access-code')?.addEventListener('click',()=>openForm({title:'Cambiar código de equipo',subtitle:'Escribe 4 o 5 dígitos o déjalo vacío para generar automáticamente uno nuevo de 5 dígitos. El código anterior dejará de funcionar inmediatamente.',fields:[{name:'codigo',label:'Nuevo código',placeholder:'Ej. 48271',help:'Solo números · 4 o 5 dígitos'}],submitText:'Cambiar código',onSubmit:async v=>{const code=String(v.codigo||'').trim();if(code&&!/^\d{4,5}$/.test(code))throw new Error('El código debe tener 4 o 5 dígitos numéricos.');await repos.accessCodes.rotate('equipo',code);toast('Código de equipo actualizado');await renderUsers();}}));
    document.querySelectorAll('.approve-team-request').forEach(b=>b.addEventListener('click',()=>{const isManager=state.session?.rol==='direccion';openForm({title:'Aprobar acceso al equipo',subtitle:'Asigna el rol real. El código usado no determina permisos.',fields:[{name:'rol',label:'Rol',type:'select',required:true,options:[...(isManager?[{value:'coordinacion',label:'Coordinación'}]:[]),{value:'secretaria',label:'Secretaría'},{value:'economia',label:'Economía / Tesorería'},{value:'comunicacion',label:'Comunicación'},{value:'monitor',label:'Monitor'}]},{name:'nota',label:'Nota interna',type:'textarea',full:true}],submitText:'Aprobar acceso',onSubmit:async v=>{await repos.users.resolveTeamRequest(b.dataset.id,'aprobada',v.rol,v.nota||'');toast('Acceso al equipo aprobado');await renderUsers();}})}));
    document.querySelectorAll('.reject-team-request').forEach(b=>b.addEventListener('click',()=>openForm({title:'Rechazar solicitud',fields:[{name:'nota',label:'Motivo / nota interna',type:'textarea',full:true}],submitText:'Rechazar',onSubmit:async v=>{await repos.users.resolveTeamRequest(b.dataset.id,'rechazada',null,v.nota||'');toast('Solicitud rechazada');await renderUsers();}})));
  }catch(e){setError(e);setMainHtml(`${pageHeader('Equipo')} ${empty('No se pudo cargar el equipo',e.message)}`)}
}

export async function renderSettings(){
  setMainHtml('<div class="loading-card">Cargando configuración…</div>');
  try{
    const [rows,config,history]=await Promise.all([repos.settings.club(),repos.settings.config(),repos.settings.brandingHistory()]);const c=rows?.[0]||state.session?.club||{};const can=has(state.session,'clubConfig');const canBranding=['direccion','coordinacion'].includes(state.session?.rol);
    const configMap=Object.fromEntries((config||[]).map(x=>[x.clave,x.valor]));
    const currentTheme=themeDefinition(c.theme_id);
    const brandPreview=`<div class="brand-preview ${esc(currentTheme.className)}" style="${c.portada_url?`--preview-cover:url('${esc(c.portada_url)}')`:''}"><div class="brand-preview-overlay"></div><div class="brand-preview-content">${c.logo_url?`<img src="${esc(c.logo_url)}" alt="Logo del club">`:`<div class="brand-preview-fallback">${icon('shield',{size:46})}</div>`}<div><span>${esc(currentTheme.name.toUpperCase())} · V${esc(c.branding_version||1)}</span><h3>${esc(c.nombre||'Tu club')}</h3><p>${esc(c.lema||'Bring the Pain')}</p></div></div></div>`;
    const themeCards=`<div class="theme-selector">${Object.values(CLUB_THEMES).map(t=>`<article class="theme-choice ${esc(t.className)} ${t.id===currentTheme.id?'active':''}"><span class="theme-swatch"></span><div><strong>${esc(t.name)}</strong><small>${esc(t.description)}</small></div>${t.id===currentTheme.id?badge('Publicado','ok'):''}</article>`).join('')}</div>`;
    const historyRows=(history||[]).map(h=>`<tr><td>V${esc(h.version)}</td><td>${esc(themeDefinition(h.snapshot?.theme_id).name)}</td><td>${esc(h.motivo||'—')}</td><td>${dtFmt(h.creado_en)}</td><td>${canBranding&&Number(h.version)!==Number(c.branding_version)?`<button class="btn btn-ghost btn-sm restore-branding" data-version="${esc(h.version)}">Restaurar como nueva versión</button>`:'—'}</td></tr>`);
    setMainHtml(`${pageHeader('Configuración','Identidad, datos y personalización del club',can?'<button class="btn btn-primary" id="edit-club">'+icon('edit',{size:16})+' Personalizar</button>':'')}${card('Identidad visual publicada',brandPreview)}${card('Temas validados',themeCards)}${canBranding?card('Versiones de branding',historyRows.length?table(['Versión','Tema','Motivo','Fecha','Acción'],historyRows):empty('Sin versiones anteriores')):''}${card('Club',`<div class="grid-2"><div><p><strong>Nombre</strong><br>${esc(c.nombre||'')}</p><p><strong>Lema</strong><br>${esc(c.lema||'—')}</p><p><strong>Teléfono</strong><br>${esc(c.telefono||'—')}</p></div><div><p><strong>Email</strong><br>${esc(c.email||'—')}</p><p><strong>Dirección</strong><br>${esc(c.direccion||'—')}</p><p><strong>Web</strong><br>${esc(c.web||'—')}</p></div></div>`)}${state.session?.platform_admin===true?card('Herramientas técnicas',`<p class="muted">Área reservada a la Administración global de KOMBAX para soporte, diagnóstico y certificación. La información técnica queda fuera de la navegación cotidiana.</p><div class="row-actions"><a class="btn btn-ghost" href="#diagnostics">${icon('activity',{size:17})} Diagnóstico</a><a class="btn btn-ghost" href="#certification">${icon('shieldCheck',{size:17})} Certificación E2E</a></div>`):''}`);
    document.querySelectorAll('.restore-branding').forEach(b=>b.addEventListener('click',()=>openForm({title:'Restaurar identidad visual',subtitle:`La versión ${b.dataset.version} se publicará como una versión nueva; el historial no se sobrescribe.`,fields:[],submitText:'Restaurar',onSubmit:async()=>{const out=await repos.settings.restoreBranding(b.dataset.version);Object.assign(state.session.club||{},out);localStorage.setItem('uw2_app_session',JSON.stringify(state.session));toast('Branding restaurado');setTimeout(()=>location.reload(),320);}})));
    document.getElementById('edit-club')?.addEventListener('click',()=>{
      const brandingFields=canBranding?[{name:'theme_id',label:'Tema premium del club',type:'select',required:true,value:currentTheme.id,options:Object.values(CLUB_THEMES).map(t=>({value:t.id,label:t.name}))},{name:'logo',label:'Logo del club',type:'file',accept:'image/jpeg,image/png,image/webp,image/gif',help:'JPG, PNG, WEBP o GIF. Se optimiza y limita a 5 MB.'},{name:'quitar_logo',label:'Quitar logo actual',type:'checkbox',value:false},{name:'portada',label:'Imagen de portada / ambiente',type:'file',accept:'image/jpeg,image/png,image/webp,image/gif',help:'Se conserva la versión anterior para poder restaurarla.'},{name:'quitar_portada',label:'Quitar portada actual',type:'checkbox',value:false}]:[];
      const modal=openForm({title:'Personalizar el club',subtitle:canBranding?'Previsualiza el tema y publica una versión reversible.':'Puedes editar los datos operativos; el branding requiere Gestor o Coordinación.',fields:[{name:'nombre',label:'Nombre',required:true},{name:'lema',label:'Lema'},{name:'telefono',label:'Teléfono'},{name:'email',label:'Email',type:'email'},{name:'direccion',label:'Dirección',full:true},{name:'web',label:'Web'},...brandingFields,{name:'dia_vencimiento',label:'Día de vencimiento',type:'number',min:1,max:28,value:configMap.dia_vencimiento||10},{name:'avisos_clase_horas',label:'Aviso de clase (horas)',type:'number',min:1,value:configMap.avisos_clase_horas||24}],initial:c,onSubmit:async v=>{
        const meta={nombre:v.nombre,lema:v.lema,telefono:v.telefono,email:v.email,direccion:v.direccion,web:v.web,dia_vencimiento:Number(v.dia_vencimiento||10),avisos_clase_horas:Number(v.avisos_clase_horas||24)};
        if(!canBranding){await repos.settings.saveClub(meta);Object.assign(state.session.club||{},meta);localStorage.setItem('uw2_app_session',JSON.stringify(state.session));toast('Configuración guardada');setTimeout(()=>location.reload(),320);return;}
        let logoUrl=v.quitar_logo?'':(c.logo_url||''),coverUrl=v.quitar_portada?'':(c.portada_url||''),uploadedLogo='',uploadedCover='',published=null;
        try{if(v.logo){uploadedLogo=await repos.settings.uploadBrandImage('logo',v.logo);logoUrl=uploadedLogo;}if(v.portada){uploadedCover=await repos.settings.uploadBrandImage('cover',v.portada);coverUrl=uploadedCover;}published=await repos.settings.publishBranding({expected_version:c.branding_version||1,theme_id:v.theme_id,logo_url:logoUrl,portada_url:coverUrl});await repos.settings.saveClub(meta);Object.assign(state.session.club||{},meta,published);localStorage.setItem('uw2_app_session',JSON.stringify(state.session));toast('Personalización publicada');setTimeout(()=>location.reload(),320);}catch(e){if(published){await repos.settings.restoreBranding(c.branding_version||1).catch(()=>{});}if(uploadedLogo)await repos.settings.removeBrandImage(uploadedLogo).catch(()=>{});if(uploadedCover)await repos.settings.removeBrandImage(uploadedCover).catch(()=>{});throw e;}
      }});
      if(canBranding){const grid=modal.form.querySelector('.form-grid'),preview=document.createElement('div');preview.className=`field full theme-live-preview ${currentTheme.className}`;preview.innerHTML=`<span>VISTA PREVIA GLOBAL · NO PUBLICADA</span><strong>${esc(c.nombre||'Tu club')}</strong><small>${esc(currentTheme.description)}</small><div class="theme-preview-components"><i></i><b>Botón principal</b><em>Tarjeta premium</em></div>`;grid.insertBefore(preview,grid.children[6]||null);modal.form.elements.theme_id?.addEventListener('change',e=>{const t=themeDefinition(e.target.value);preview.className=`field full theme-live-preview ${t.className}`;preview.querySelector('small').textContent=t.description;});}
    });
  }catch(e){setError(e);setMainHtml(`${pageHeader('Configuración')} ${empty('No se pudo cargar la configuración',e.message)}`)}
}

export async function renderProfile(){
  const s=state.session;
  const pushState=nativeNotificationState();
  const nativePush=pushState!=='web';
  const pushGranted=pushState==='granted';
  const pushNeedsSettings=pushState==='settings';
  const pushDescription=pushGranted?'Notificaciones Android activadas en este dispositivo':pushNeedsSettings?'Android tiene las notificaciones bloqueadas. Puedes habilitarlas desde Ajustes.':'Permite las notificaciones para recibir comunicaciones importantes del club, avisos de cobro y recordatorios.';
  const pushAction=pushGranted?badge('Activadas','ok'):`<button class="btn btn-ghost btn-sm" id="enable-push">${pushNeedsSettings?'Abrir ajustes de notificaciones':'Activar notificaciones'}</button>`;
  const [avatarUrl,socialProfiles]=await Promise.all([s?.avatar_path?repos.settings.avatarUrl(s.avatar_path).catch(()=> ''):Promise.resolve(''),repos.kombaxSocial.myProfiles().catch(()=>[])]);
  const memberSocial=(socialProfiles||[]).find(x=>x?.perfil_tipo==='miembro'||x?.sujeto_tipo==='miembro')||null;
  const memberSocialHasAvatar=Boolean(memberSocial?.avatar_path||memberSocial?.avatar_url);
  const initials=String(`${s?.nombre||''} ${s?.apellidos||''}`).split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()).join('')||'KX';
  setMainHtml(`${pageHeader('Mi perfil','Tu identidad dentro de tu club')}
    ${card('Perfil personal',`<div class="profile-photo-card"><div class="profile-photo-large">${avatarUrl?`<img src="${esc(avatarUrl)}" alt="Foto de perfil">`:esc(initials)}</div><div><h3 style="margin:0">${esc(`${s?.nombre||''} ${s?.apellidos||''}`.trim())}</h3><p class="muted" style="margin:5px 0">${esc(s?.email||'')}</p><p class="muted" style="margin:5px 0">${esc(s?.telefono||'')}</p><small>${esc(rolesLabel(s?.roles||[s?.rol]))}</small>${memberSocial?'<p class="muted profile-public-note">Tu identidad de miembro en KOMBAX Social está activa. Puedes mantener una foto pública sincronizada sin exponer otros datos privados.</p>':''}<div class="profile-photo-actions"><button class="btn btn-primary btn-sm" id="change-avatar">${icon('image',{size:15})} ${s?.avatar_path?'Cambiar foto':'Subir foto'}</button>${s?.avatar_path?'<button class="btn btn-ghost btn-sm" id="remove-avatar">Quitar foto</button>':''}<button class="btn btn-ghost btn-sm" id="edit-profile">Editar datos</button>${memberSocial&&s?.avatar_path&&!memberSocialHasAvatar?'<button class="btn btn-ghost btn-sm" id="sync-public-avatar">Sincronizar foto actual con KOMBAX Social</button>':''}${memberSocial?'<button class="btn btn-ghost btn-sm" id="open-public-social-profile">Ver mi perfil público KOMBAX</button>':''}</div></div></div>`)}
    ${card('Seguridad y acceso',`${quickRow(icon('lock'),'Cambiar contraseña','Verifica tu contraseña actual y establece una nueva. La sesión se cerrará al terminar.','<button type="button" class="btn btn-primary btn-sm" id="change-account-password">Cambiar contraseña</button>')}`)}
    ${card('Avisos y privacidad',`${quickRow(icon('bell'),'Activa las notificaciones',pushDescription,pushAction)}${quickRow(icon('shieldCheck'),'Privacidad y condiciones','Consulta condiciones, privacidad, Comunidad del Club y derechos de imagen','<button type="button" class="btn btn-ghost btn-sm" id="open-privacy-conditions">Abrir</button>')}`)}`);
  document.getElementById('change-account-password')?.addEventListener('click',()=>openAuthenticatedPasswordChange({onComplete:()=>location.reload()}));
  document.getElementById('open-privacy-conditions')?.addEventListener('click',openPrivacyConditions);
  document.getElementById('enable-push')?.addEventListener('click',async()=>{try{if(nativePush){if(pushNeedsSettings)window.UrbanWarriorsNative.openNotificationSettings();else window.UrbanWarriorsNative.requestNotifications();toast(pushNeedsSettings?'Revisa el permiso de KOMBAX en Ajustes':'Android mostrará la solicitud oficial de notificaciones');setTimeout(()=>renderProfile(),900);return;}const permission='Notification' in window?(Notification.permission==='granted'?'granted':await Notification.requestPermission()):'denied';if(permission==='granted'){localStorage.setItem('uw_foreground_notifications','1');toast('Avisos del navegador activados');await renderProfile();}else toast('No se concedió permiso para mostrar avisos','error');}catch(e){setError(e)}});
  document.getElementById('edit-profile')?.addEventListener('click',()=>openForm({title:'Editar perfil',fields:[{name:'nombre',label:'Nombre',required:true},{name:'apellidos',label:'Apellidos'},{name:'telefono',label:'Teléfono'}],initial:s,onSubmit:async v=>{await repos.settings.profile(v);Object.assign(state.session,v);localStorage.setItem('uw2_app_session',JSON.stringify(state.session));toast('Perfil actualizado');await renderProfile();}}));
  document.getElementById('change-avatar')?.addEventListener('click',()=>openForm({title:'Foto de perfil',subtitle:'Tu foto personal es privada dentro del club. Si quieres, puedes publicar una copia como avatar de tu identidad de miembro en KOMBAX Social.',fields:[{name:'avatar',label:'Imagen',type:'file',accept:'image/jpeg,image/png,image/webp',required:true,help:'JPG, PNG o WEBP · máximo 5 MB.'},{name:'public_social',label:'Usar también como foto pública en KOMBAX Social',type:'checkbox',value:memberSocial!==null,full:true,help:memberSocial?'La copia pública se utilizará en tu perfil Social, publicaciones, comentarios y directorio. Puedes desmarcar esta opción.':'Activa primero tu identidad de miembro en KOMBAX Social para publicar una foto pública.'}],submitText:'Guardar foto',onSubmit:async v=>{const out=await repos.settings.uploadAvatar(v.avatar);state.session.avatar_path=out?.avatar_path||'';localStorage.setItem('uw2_app_session',JSON.stringify(state.session));window.dispatchEvent(new CustomEvent('uw-profile-avatar-changed'));let publicSynced=false;if(v.public_social===true&&memberSocial){try{await repos.kombaxSocial.uploadMedia(memberSocial.id,'avatar',v.avatar,{enAlbum:false});publicSynced=true;window.dispatchEvent(new CustomEvent('uw-kombax-social-profile-media-changed',{detail:{social_profile_id:memberSocial.id,kind:'avatar'}}));}catch(error){setError(error);toast('La foto personal se guardó, pero no se pudo actualizar la foto pública de KOMBAX Social.','error');}}toast(publicSynced?'Foto actualizada también en KOMBAX Social':'Foto de perfil actualizada');await renderProfile();}}));
  document.getElementById('sync-public-avatar')?.addEventListener('click',async()=>{if(!memberSocial||!s?.avatar_path)return;const button=document.getElementById('sync-public-avatar');if(button)button.disabled=true;try{await repos.kombaxSocial.syncPrivateAvatar(memberSocial.id,s.avatar_path);window.dispatchEvent(new CustomEvent('uw-kombax-social-profile-media-changed',{detail:{social_profile_id:memberSocial.id,kind:'avatar_sync'}}));toast('Foto pública sincronizada con KOMBAX Social');await renderProfile();}catch(error){if(button)button.disabled=false;setError(error);}});
  document.getElementById('open-public-social-profile')?.addEventListener('click',()=>memberSocial&&openKombaxPublicProfile(memberSocial.id));
  document.getElementById('remove-avatar')?.addEventListener('click',async()=>{try{await repos.settings.removeAvatar();state.session.avatar_path='';localStorage.setItem('uw2_app_session',JSON.stringify(state.session));window.dispatchEvent(new CustomEvent('uw-profile-avatar-changed'));toast('Foto de perfil eliminada');await renderProfile();}catch(e){setError(e)}});
}

export async function renderInstall(){
  const role=state.session?.rol;const staff=['direccion','coordinacion','secretaria','economia','comunicacion','monitor'].includes(role);const canPoster=['direccion','coordinacion','secretaria'].includes(role);
  const resources=[quickRow(icon('fileText'),'Manual interactivo del portal de club','Guía operativa completa, buscable y organizada por funciones','<a class="btn btn-primary btn-sm" href="#help">Abrir manual</a>')];
  if(canPoster)resources.push(quickRow(icon('qr'),'Cartel genérico de descarga KOMBAX','Para recepción, gimnasio o eventos · espacio QR + código de invitación','<a class="btn btn-ghost btn-sm" href="./assets/docs/Cartel_Descarga_KOMBAX_Club.png" target="_blank">Abrir cartel</a>'));
  setMainHtml(`${pageHeader('Instalar KOMBAX','Instalación, formación y recursos del portal de club','', 'Mi cuenta')}
    ${hero({kicker:'KOMBAX en tu móvil',title:'Tu club, siempre a mano.',body:'Instala la aplicación web progresiva o utiliza el canal Android disponible para tu club.',actions:'<button class="btn btn-primary" id="install-pwa">Instalar PWA</button>',dark:true})}
    <div class="grid-2">${card('Instalación rápida',`<div style="display:grid;place-items:center;padding:10px"><img src="./assets/install-qr.png" alt="QR de instalación KOMBAX" style="width:min(260px,80%);border-radius:18px;background:#fff;padding:10px"><p class="muted">Escanea el QR desde tu móvil para abrir KOMBAX y el portal de tu club.</p></div>`)}${card('Formación y recursos',resources.join(''))}</div>
    ${canPoster?card('Cartel de descarga del club',`<div class="kx-install-poster"><img src="./assets/docs/Cartel_Descarga_KOMBAX_Club.png" alt="Cartel genérico de descarga KOMBAX para clubes"><div><strong>Listo para personalizar con el acceso del club</strong><p class="muted">El diseño es genérico y no contiene el nombre de ningún club. El espacio de QR y el código escrito están preparados para el material de recepción.</p><a class="btn btn-ghost" href="./assets/docs/Cartel_Descarga_KOMBAX_Club.png" target="_blank">${icon('qr',{size:16})} Ver cartel completo</a></div></div>`):''}`);
  document.getElementById('install-pwa')?.addEventListener('click',async()=>{if(window.__uwInstallPrompt){window.__uwInstallPrompt.prompt();await window.__uwInstallPrompt.userChoice;window.__uwInstallPrompt=null;}else toast('En este dispositivo usa el menú del navegador → Instalar aplicación.','error');});
}

export async function renderDiagnostics(){
  if(state.session?.platform_admin!==true){setMainHtml(`${pageHeader('Acceso restringido')} ${empty('Administración KOMBAX requerida','Esta información está reservada a la administración global de KOMBAX.')}`);return;}
  setMainHtml('<div class="loading-card">Ejecutando diagnóstico…</div>');
  try{
    const [contract,probe,diagnostic]=await Promise.all([backend.contract(),backend.probe(),backend.diagnostic().catch(e=>({error:e.message}))]);state.diagnostics={contract,probe,diagnostic};
    const trace=state.trace.map(t=>`<div class="trace-item ${t.ok===true?'trace-ok':t.ok===false?'trace-bad':'trace-pending'}"><strong>${esc(t.label||t.kind)} ${t.ms!=null?`· ${t.ms} ms`:''}</strong><small>${esc(t.error||t.detail||t.requestId||'')}</small></div>`).join('');
    const cachePerf=performanceSnapshot(),times=state.trace.map(x=>Number(x.ms)).filter(Number.isFinite).sort((a,b)=>a-b),percentile=p=>times.length?times[Math.min(times.length-1,Math.max(0,Math.ceil(times.length*p)-1))]:0,slow=state.trace.filter(x=>Number(x.ms)>5000);
    const perf=`<div class="metrics">${metric('Consultas medidas',times.length,'sesión actual')}${metric('P50',`${percentile(.5)} ms`,'red + RPC')}${metric('P95',`${percentile(.95)} ms`,'red + RPC')}${metric('> 5 segundos',slow.length,slow.length?'requiere investigación':'sin incidencias registradas')}</div><p class="muted">Caché segura por club/usuario: ${cachePerf.count} cargas · P50 ${cachePerf.p50} ms · P95 ${cachePerf.p95} ms · ${cachePerf.errors} errores.</p>`;
    setMainHtml(`${pageHeader('Diagnóstico del sistema','Estado observable del canal real')}${card('Rendimiento percibido',perf)}${card('Contrato',`<pre style="white-space:pre-wrap;font-size:12px">${esc(JSON.stringify(contract,null,2))}</pre>`)}${card('Sonda de escritura',`<pre style="white-space:pre-wrap;font-size:12px">${esc(JSON.stringify(probe,null,2))}</pre>`)}${card('Diagnóstico de persistencia',`<pre style="white-space:pre-wrap;font-size:12px">${esc(JSON.stringify(diagnostic,null,2))}</pre>`)}${card('Traza de esta sesión',trace||empty('Sin operaciones registradas'))}`);
  }catch(e){setError(e);setMainHtml(`${pageHeader('Diagnóstico del sistema')} ${empty('Diagnóstico fallido',e.message)}`)}
}

function certStep(name,detail=''){return {name,detail,status:'pending',error:null,data:null}}
function renderCertBoard(steps,running=false){
  const box=document.getElementById('cert-board');if(!box)return;
  box.innerHTML=steps.map((s,i)=>`<div class="cert-step ${s.status==='ok'?'ok':s.status==='fail'?'fail':''}"><span class="cert-index">${s.status==='ok'?icon('checkCircle',{size:15}):s.status==='fail'?icon('alert',{size:15}):i+1}</span><div><strong>${esc(s.name)}</strong><small>${esc(s.error||s.detail||'Pendiente')}</small></div>${s.status==='ok'?badge('OK','ok'):s.status==='fail'?badge('FALLO','danger'):badge(running?'Pendiente':'No ejecutado','neutral')}</div>`).join('');
}

export async function renderCertification(){
  if(state.session?.platform_admin!==true||!has(state.session,'certification')){setMainHtml(`${pageHeader('Certificación E2E')} ${empty('Acceso restringido','Solo la administración global de KOMBAX puede ejecutar la certificación.')}`);return;}
  const steps=[
    certStep('Contrato y sonda backend'),certStep('Diagnóstico SQL final v166'),certStep('Crear y leer disciplina'),certStep('Editar y releer disciplina'),certStep('Crear y leer grado'),certStep('Crear grupo con horario y leerlo'),certStep('Crear y leer tarifa'),certStep('Crear alumno y matrícula'),certStep('Crear sesión + confirmar asistencia'),certStep('Registrar asistencia y leerla'),certStep('Crear seguimiento y leerlo'),certStep('Crear comunicación y leerla'),certStep('Crear material y variante'),certStep('Subir y leer documento privado'),certStep('Crear serie recurrente y ocurrencia'),certStep('Publicar y borrar en Comunidad del Club'),certStep('Ciclo de vida seguro'),certStep('Logout + login + persistencia'),certStep('Borrado total RC10 + limpieza Storage')
  ];
  setMainHtml(`${pageHeader('Certificación E2E final','Navegador → Supabase → Storage → PostgreSQL → lectura posterior')}
    <div class="alert alert-warning" style="margin:0 0 18px"><strong>Uso controlado</strong><span>Esta prueba crea registros E2E identificables en el Supabase real, valida Storage privado y operaciones de ciclo de vida. Al final elimina también el histórico E2E mediante las operaciones reforzadas del Gestor de la app, de forma que la certificación no deja datos de prueba.</span></div>
    ${card('Ejecución',`<p>No usa mocks ni DML directo. Todas las escrituras pasan por <code>app_mutate_v160</code> y los archivos por Supabase Storage.</p><button class="btn btn-primary" id="start-cert">Ejecutar certificación final</button> <button class="btn btn-ghost" id="export-cert" disabled>Exportar resultado</button><div id="cert-board" style="margin-top:18px"></div>`)}`);
  renderCertBoard(steps,false);
  document.getElementById('start-cert')?.addEventListener('click',()=>openForm({title:'Autorizar certificación final',subtitle:'Introduce tu contraseña únicamente para verificar logout + nuevo login. No se almacena.',fields:[{name:'password',label:'Contraseña',type:'password',required:true}],submitText:'Iniciar E2E',onSubmit:async v=>{await runCertification(steps,v.password);}}));
  document.getElementById('export-cert')?.addEventListener('click',()=>{
    const blob=new Blob([JSON.stringify(state.certification,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`urban-warriors-cert-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href);
  });
}

async function runCertification(steps,password){
  const prefix=`E2E_RC10_${new Date().toISOString().replace(/[-:.TZ]/g,'').slice(0,14)}`;const ids={};const email=state.session.email;const log=[];const sessionAccessCode=`E2E${Date.now().toString(36).slice(-7).toUpperCase()}`;
  const set=async(index,fn)=>{
    steps[index].status='pending';steps[index].detail='Ejecutando…';renderCertBoard(steps,true);
    try{const data=await fn();steps[index].status='ok';steps[index].data=data;steps[index].detail=typeof data==='string'?data:'Verificado';log.push({step:steps[index].name,ok:true,data});renderCertBoard(steps,true);return data;}
    catch(e){steps[index].status='fail';steps[index].error=e.message;log.push({step:steps[index].name,ok:false,error:e.message});renderCertBoard(steps,false);throw e;}
  };
  const findOne=async(table,id)=>{const rows=await backend.select(table,`select=*&id=eq.${encodeURIComponent(id)}&limit=1`);if(!rows?.[0])throw new Error(`${table}: el ID ${id} no aparece en lectura posterior.`);return rows[0];};
  const assertGone=async(table,id)=>{const rows=await backend.select(table,`select=id&id=eq.${encodeURIComponent(id)}&limit=1`);if(rows?.length)throw new Error(`${table}: el ID ${id} debía estar eliminado.`);return true;};
  try{
    await set(0,async()=>{const [c,p]=await Promise.all([backend.contract(),backend.probe()]);if(!c.ok||!p.ok)throw new Error('Contrato o sonda sin OK');if(Number(c.schema_epoch)!==160)throw new Error(`Epoch inesperado: ${c.schema_epoch}`);return {contract:c.backend_version,epoch:c.schema_epoch,probe:true,operations:c.operations?.length||0}});
    await set(1,async()=>{const d=await backend.diagnostic();const list=Array.isArray(d)?d:[];const fails=list.filter(x=>String(x.estado||x.status||x.resultado||'OK').toUpperCase()==='FALLO');if(fails.length)throw new Error(`Diagnóstico SQL contiene ${fails.length} control(es) en FALLO`);return {rows:list.length,avisos:list.filter(x=>String(x.estado||'').toUpperCase()==='AVISO').length}});
    await set(2,async()=>{const r=await repos.catalog.saveDiscipline({nombre:`${prefix}_DISCIPLINA`,descripcion:'Certificación E2E RC10',color:'#ffffff',activa:true,orden:999});ids.discipline=r.id;const row=await findOne('disciplinas',r.id);return {id:r.id,nombre:row.nombre}});
    await set(3,async()=>{await repos.catalog.saveDiscipline({id:ids.discipline,nombre:`${prefix}_DISCIPLINA`,descripcion:'E2E EDITADO',color:'#ffffff',activa:true,orden:998});const row=await findOne('disciplinas',ids.discipline);if(row.descripcion!=='E2E EDITADO')throw new Error('La edición no aparece en la lectura.');return {id:row.id,descripcion:row.descripcion}});
    await set(4,async()=>{const r=await repos.catalog.saveGrade({disciplina_id:ids.discipline,nombre:`${prefix}_GRADO`,orden:99,color:'#ffffff',meses_minimos:0,activo:true});ids.grade=r.id;return findOne('grados',r.id)});
    await set(5,async()=>{const r=await repos.groups.save({disciplina_id:ids.discipline,nombre:`${prefix}_GRUPO`,monitor_nombre:'E2E',sala:'E2E',edad_min:10,edad_max:99,plazas:20,activo:true,horarios:[{dia_semana:1,hora_inicio:'18:00',hora_fin:'19:00'}]});ids.group=r.id;const row=await findOne('grupos',r.id);const hs=await backend.select('horarios_grupo',`select=*&grupo_id=eq.${encodeURIComponent(r.id)}`);if(!hs.length)throw new Error('Grupo creado sin horario persistido.');return {id:row.id,horarios:hs.length}});
    await set(6,async()=>{const r=await repos.tariffs.save({nombre:`${prefix}_TARIFA`,descripcion:'E2E',importe:1,matricula:0,periodicidad:'mensual',activa:true});ids.tariff=r.id;return findOne('tarifas',r.id)});
    await set(7,async()=>{const r=await repos.members.save({nombre:'E2E',apellidos:prefix,fecha_nacimiento:'2000-01-01',telefono:'600000000',email:`${prefix.toLowerCase()}@invalid.local`,disciplina_id:ids.discipline,grupo_id:ids.group,grado_id:ids.grade,tarifa_id:ids.tariff,estado:'activo',notas_internas:'Certificación E2E RC10'});ids.member=r.id;const row=await findOne('socios',r.id);const links=await backend.select('socio_disciplinas',`select=*&socio_id=eq.${encodeURIComponent(r.id)}&activa=eq.true`);if(!links.length)throw new Error('Alumno creado sin matrícula persistida.');ids.enrollment=links[0].id;return {id:row.id,matriculas:links.length}});
    await set(8,async()=>{const r=await repos.sessions.save({grupo_id:ids.group,fecha:isoDate(),hora_inicio:'18:00',hora_fin:'19:00',monitor_nombre:'E2E',estado:'programada',observacion_general:'Certificación E2E',codigo_acceso:sessionAccessCode});ids.session=r.id;await findOne('sesiones_entrenamiento',r.id);const reservation=await repos.sessions.reserve(r.id,ids.member);ids.reservation=reservation.id;const rows=await backend.select('reservas_sesion',`select=*&sesion_id=eq.${encodeURIComponent(r.id)}&socio_id=eq.${encodeURIComponent(ids.member)}&limit=1`);if(!rows?.[0]||rows[0].estado!=='confirmada')throw new Error('La confirmación previa no quedó persistida.');return {sesion:r.id,reserva:rows[0].id,estado:rows[0].estado}});
    await set(9,async()=>{const r=await repos.sessions.saveAttendance({sesion_id:ids.session,socio_id:ids.member,estado:'presente',observacion:'E2E'});ids.attendance=r.id;const rows=await backend.select('asistencias',`select=*&sesion_id=eq.${encodeURIComponent(ids.session)}&socio_id=eq.${encodeURIComponent(ids.member)}&limit=1`);if(!rows?.[0]||rows[0].estado!=='presente')throw new Error('La asistencia no aparece como presente.');return {id:rows[0].id,estado:rows[0].estado}});
    await set(10,async()=>{const r=await repos.tracking.save({socio_id:ids.member,tipo:'e2e',nota:'Certificación E2E RC10',visibilidad:'equipo',fecha:isoDate()});ids.tracking=r.id;return findOne('seguimiento',r.id)});
    await set(11,async()=>{const bin=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='),c=>c.charCodeAt(0));const img=new File([bin],`${prefix}.png`,{type:'image/png'});const imagen_url=await repos.communications.uploadImage(img);const r=await repos.communications.save({tipo:'noticia',titulo:`${prefix}_COMUNICACION`,cuerpo:'Certificación E2E RC10',audiencia:'todos',estado:'borrador',imagen_url});ids.communication=r.id;ids.communicationImage=imagen_url;const row=await findOne('comunicaciones',r.id);if(!row.imagen_url)throw new Error('La imagen pública no quedó asociada a la comunicación.');return {id:r.id,imagen:true}});
    await set(12,async()=>{const r=await repos.material.save({disciplina_id:ids.discipline,nombre:`${prefix}_MATERIAL`,categoria:'E2E',descripcion:'Certificación',precio:1,stock:0,obligatorio:false,referencia:prefix,activo:true});ids.material=r.id;await findOne('material_catalogo',r.id);const v=await repos.material.saveVariant({material_id:r.id,talla:'U',color:'Negro',referencia:`${prefix}-V`,stock:1,activa:true});ids.variant=v.id;await findOne('material_variantes',v.id);return {material:r.id,variante:v.id}});
    await set(13,async()=>{const file=new File([new Blob(['%PDF-1.4\n% Urban Warriors E2E RC6\n'],{type:'application/pdf'})],`${prefix}.pdf`,{type:'application/pdf'});const r=await repos.documents.upload(ids.member,file,{nombre:`${prefix}_INSCRIPCION`,tipo:'inscripcion_asociacion',fecha_documento:isoDate(),firmado:true,visible_familia:true,observaciones:'E2E Storage'});ids.document=r.id;const row=await findOne('documentos_socios',r.id);if(row.estado!=='vigente'||row.firmado!==true)throw new Error('Metadatos documentales incompletos.');const url=await repos.documents.url(row.storage_path);if(!url)throw new Error('No se pudo generar URL firmada del documento.');return {id:r.id,estado:row.estado,signedUrl:true}});
    await set(14,async()=>{const d=new Date();d.setDate(d.getDate()+1);const date=d.toISOString().slice(0,10);const isoDow=d.getDay()===0?7:d.getDay();const r=await repos.sessions.saveSeries({grupo_id:ids.group,dias_semana:[isoDow],hora_inicio:'07:15',hora_fin:'08:15',monitor_nombre:'E2E RECURRENTE',sala:'E2E',fecha_inicio:date,fecha_fin:date,activa:true});ids.series=r.id;const seriesRow=await findOne('series_sesiones',r.id);const occ=await backend.select('sesiones_entrenamiento',`select=*&serie_id=eq.${encodeURIComponent(r.id)}&fecha=eq.${date}&limit=1`);if(!occ?.[0])throw new Error('La serie no generó su ocurrencia recurrente.');ids.recurringSession=occ[0].id;return {serie:seriesRow.id,ocurrencia:occ[0].id,fecha:date}});
    await set(15,async()=>{const bin=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII='),c=>c.charCodeAt(0));const img=new File([bin],`${prefix}-community.png`,{type:'image/png'});const path=await repos.community.upload(img);let pub;try{pub=await repos.community.publish({texto:`${prefix} comunidad`,media_path:path,media_tipo:'imagen'});ids.community=pub.id;await findOne('publicaciones_comunidad',pub.id);await repos.community.delete(pub.id);await assertGone('publicaciones_comunidad',pub.id);return {publicada:true,borrada:true,storage:true};}catch(e){await backend.remove('community-media',path).catch(()=>{});throw e;}});
    await set(16,async()=>{const g=await repos.groups.save({disciplina_id:ids.discipline,nombre:`${prefix}_GRUPO_BORRABLE`,monitor_nombre:'E2E',sala:'',plazas:1,activo:true,horarios:[]});await repos.groups.delete(g.id);await assertGone('grupos',g.id);const pre=await repos.preenrollments.create({tipo_solicitud:'adulto',nombre:'E2E',apellidos:`${prefix}_SOL`,telefono:'600000001',disciplina_id:ids.discipline,observaciones:'Desechable'});await repos.preenrollments.cancel(pre.id,'E2E');await repos.preenrollments.delete(pre.id);await assertGone('preinscripciones',pre.id);const pub=await repos.communications.save({tipo:'noticia',titulo:`${prefix}_BORRABLE`,cuerpo:'E2E',audiencia:'todos',estado:'borrador'});await repos.communications.delete(pub.id);await assertGone('comunicaciones',pub.id);const ses=await repos.sessions.save({grupo_id:ids.group,fecha:isoDate(),hora_inicio:'20:00',hora_fin:'21:00',monitor_nombre:'E2E',estado:'programada',codigo_acceso:`X${Date.now().toString(36).slice(-7).toUpperCase()}`});await repos.sessions.delete(ses.id);await assertGone('sesiones_entrenamiento',ses.id);return {grupo:true,preinscripcion:true,publicacion:true,sesion:true}});
    await set(17,async()=>{await backend.signOut({preserveTrace:true});const s=await backend.signIn(email,password);if(!s?.id)throw new Error('No se pudo volver a iniciar sesión.');const [row,doc]=await Promise.all([findOne('disciplinas',ids.discipline),findOne('documentos_socios',ids.document)]);return {relogin:true,disciplina:row.id===ids.discipline,documento:doc.id===ids.document}});
    await set(18,async()=>{await repos.communications.delete(ids.communication);await assertGone('comunicaciones',ids.communication);await repos.material.forceDelete(ids.material);await assertGone('material_catalogo',ids.material);await repos.members.forceDelete(ids.member);await assertGone('socios',ids.member);await repos.groups.forceDelete(ids.group);await assertGone('grupos',ids.group);await repos.catalog.forceDeleteGrade(ids.grade);await assertGone('grados',ids.grade);await repos.tariffs.forceDelete(ids.tariff);await assertGone('tarifas',ids.tariff);await repos.catalog.forceDeleteDiscipline(ids.discipline);await assertGone('disciplinas',ids.discipline);return {publicacionEImagen:true,material:true,alumnoEHistorial:true,grupoYSesiones:true,serieRecurrente:true,comunidad:true,catalogo:true}});
    state.certification={version:window.UW_CONFIG.release.version,at:new Date().toISOString(),prefix,ids,steps:log,trace:state.trace};document.getElementById('export-cert').disabled=false;toast('Certificación E2E final completada');
  }catch(e){state.certification={version:window.UW_CONFIG.release.version,at:new Date().toISOString(),prefix,ids,steps:log,trace:state.trace,error:e.message};document.getElementById('export-cert').disabled=false;setError(e);}
  renderCertBoard(steps,false);
}
