import { repos } from '../core/repositories.js';
import { state } from '../core/state.js';
import { financePremiumRepo as premium } from '../core/finance-premium-repository.js';
import { esc, money, dateFmt, isoDate, humanError } from '../core/utils.js';
import { pageHeader, badge, empty, openForm, openDetail, toast, setError, setMainHtml } from '../ui/components.js';
import { renderFinance } from './finance.js';
import { buildFinanceReportPdf, sha256Blob } from './finance-report-pdf.js';

const PORTAL_ROLES=new Set(['familia','alumno','monitor']);
const TABS=[['summary','Resumen'],['charges','Cargos'],['automations','Automatizaciones'],['payments','Pagos'],['receipts','Recibos'],['reports','Informes']];
const CATEGORY=[['cuota','Cuota'],['matricula','Matrícula'],['licencia','Licencia'],['material','Material'],['competicion','Competición'],['evento','Evento'],['desplazamiento','Desplazamiento'],['otro','Otro']];
const PERIODICITY=[['mensual','Mensual'],['trimestral','Trimestral'],['semestral','Semestral'],['anual','Anual'],['unica','Única']];
const PAYMENT_METHODS=['transferencia','bizum','efectivo','tarjeta','otro'];
let tab='summary';
let filters={year:String(new Date().getFullYear())};
let offset=0;
let busy=false;
let catalogs=null;
let deepLinkHandled='';

const categoryLabel=v=>Object.fromEntries(CATEGORY)[v]||v||'Otro';
const statusKind=v=>v==='pagada'?'ok':v==='vencida'?'danger':v==='parcialmente_pagada'?'warn':v==='anulada'||v==='exenta'?'neutral':'warn';
const monthName=v=>{const d=new Date(`${v}-01T12:00:00`);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('es-ES',{month:'short',year:'2-digit'}).format(d)};
const pct=(value,max)=>max>0?Math.max(2,Math.min(100,100*Number(value||0)/max)):0;
const cleanFilters=()=>Object.fromEntries(Object.entries(filters).filter(([,v])=>v!==''&&v!=null));

async function loadCatalogs(){
  if(catalogs)return catalogs;
  const [members,groups,disciplines,tariffs]=await Promise.all([
    repos.members.list(500),repos.groups.list(),repos.catalog.disciplines(),repos.tariffs.list()
  ]);
  catalogs={members:(members||[]).filter(x=>x.estado==='activo'),groups:(groups||[]).filter(x=>x.activo!==false),disciplines:(disciplines||[]).filter(x=>x.activa!==false),tariffs:tariffs||[]};
  return catalogs;
}

function filterChips(){
  const labels={year:'Año',month:'Mes',date_from:'Desde',date_to:'Hasta',socio_id:'Alumno',grupo_id:'Grupo',disciplina_id:'Disciplina',categoria:'Categoría',estado:'Estado',tarifa_id:'Tarifa',regla_id:'Regla',metodo:'Método',aging:'Antigüedad',focus:'Vista'};
  const values=cleanFilters();
  const chips=Object.entries(values).map(([k,v])=>`<button type="button" class="kx-fin-filter-chip" data-remove-filter="${esc(k)}"><span>${esc(labels[k]||k)}</span><strong>${esc(String(v))}</strong><b aria-hidden="true">×</b></button>`).join('');
  return `<div class="kx-fin-filterbar" aria-label="Filtros financieros activos"><div>${chips||'<span class="kx-fin-filter-empty">Sin filtros adicionales</span>'}</div>${chips?'<button class="btn btn-ghost btn-sm" id="kx-fin-clear-filters" type="button">Limpiar filtros</button>':''}</div>`;
}

function navTabs(ctx){
  return `<nav class="kx-fin-tabs" aria-label="Secciones de Finanzas">${TABS.map(([id,label])=>`<button type="button" data-fin-tab="${id}" class="${tab===id?'active':''}">${esc(label)}${id==='payments'&&Number(ctx.pagos_por_validar||0)>0?`<span>${Number(ctx.pagos_por_validar)}</span>`:''}</button>`).join('')}</nav>`;
}

function kpiCard(id,label,value,sub,active=false){return `<button type="button" class="kx-fin-kpi ${active?'is-active':''}" data-fin-focus="${id}" aria-pressed="${active?'true':'false'}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(sub||'Pulsa para filtrar')}</small></button>`;}

function renderMonthlyChart(months=[]){
  const max=Math.max(1,...months.flatMap(m=>[Number(m.generado||0),Number(m.cobrado||0),Number(m.pendiente||0)]));
  if(!months.length)return empty('Sin evolución para estos filtros','Amplía el periodo o limpia filtros para ver la serie mensual.');
  return `<div class="kx-fin-chart" role="group" aria-label="Generado, cobrado y pendiente por mes">
    <div class="kx-fin-chart-legend"><span><i class="is-generated"></i>Generado</span><span><i class="is-collected"></i>Cobrado</span><span><i class="is-pending"></i>Pendiente</span></div>
    <div class="kx-fin-chart-grid">${months.map(m=>{const key=String(m.mes||'');return `<button type="button" class="kx-fin-chart-month" data-chart-month="${esc(key)}" aria-label="${esc(monthName(key))}: generado ${money(m.generado)}, cobrado ${money(m.cobrado)}, pendiente ${money(m.pendiente)}"><span class="kx-fin-bars"><i class="is-generated" style="--bar:${pct(m.generado,max)}%" title="Generado ${money(m.generado)}"></i><i class="is-collected" style="--bar:${pct(m.cobrado,max)}%" title="Cobrado ${money(m.cobrado)}"></i><i class="is-pending" style="--bar:${pct(m.pendiente,max)}%" title="Pendiente ${money(m.pendiente)}"></i></span><b>${esc(monthName(key))}</b><small>${money(m.pendiente)} pend.</small></button>`}).join('')}</div>
  </div>`;
}

function renderAging(aging=[]){
  const labels={sin_vencer:'Sin vencer','1_15':'1–15 días','16_30':'16–30','31_60':'31–60',mas_60:'+60 días'};
  return `<div class="kx-fin-aging">${aging.map(a=>`<button type="button" data-aging="${esc(a.bucket)}" class="${filters.aging===a.bucket?'active':''}"><span>${esc(labels[a.bucket]||a.bucket)}</span><strong>${money(a.importe)}</strong><small>${Number(a.cargos||0)} cargos · ${Number(a.alumnos||0)} alumnos</small></button>`).join('')}</div>`;
}

function renderAttention(attention={}){
  const items=[['payments','Pagos por validar',attention.pagos_por_validar||0,'Revisar pagos comunicados'],['overdue','Cargos vencidos',attention.vencidos||0,'Priorizar deuda vencida'],['automation-errors','Errores de automatización',attention.errores_automatizacion||0,'Revisar ejecuciones'],['paused','Avisos pausados',attention.avisos_pausados||0,'Comprobar excepciones']];
  return `<div class="kx-fin-attention">${items.map(([id,label,count,sub])=>`<button type="button" data-attention="${id}" class="${Number(count)>0?'needs-attention':''}"><span>${esc(label)}</span><strong>${Number(count)}</strong><small>${esc(sub)}</small></button>`).join('')}</div>`;
}

function renderNextAutomations(rows=[]){
  if(!rows.length)return empty('Sin automatizaciones próximas','Crea una automatización cuando quieras que KOMBAX prepare cargos recurrentes.');
  return `<div class="kx-fin-next">${rows.map(r=>`<button type="button" data-open-rule="${esc(r.regla_id)}"><span><strong>${esc(r.nombre)}</strong><small>${esc(categoryLabel(r.categoria))} · ${esc(r.periodicidad)}</small></span><span><b>${dateFmt(r.proxima_generacion)}</b><small>${money(r.importe)}</small></span></button>`).join('')}</div>`;
}

function renderSummary(ctx,dashboard){
  const s=dashboard.summary||{};const focus=filters.focus||'';
  return `<section class="kx-fin-summary">
    <div class="kx-fin-kpis">${kpiCard('generado','Generado',money(s.generado),`${Number(s.cargos||0)} cargos`,focus==='generado')}${kpiCard('cobrado','Cobrado',money(s.cobrado),`${Number(s.porcentaje_cobro||0).toFixed(1)} % de cobro`,focus==='cobrado')}${kpiCard('pendiente','Pendiente',money(s.pendiente),`${Number(s.alumnos_con_deuda||0)} alumnos`,focus==='pendiente')}${kpiCard('vencido','Vencido',money(s.vencido),'Requiere atención',focus==='vencido')}${kpiCard('all','% de cobro',`${Number(s.porcentaje_cobro||0).toFixed(1)} %`,'Salud financiera',focus==='all')}</div>
    <div class="kx-fin-dashboard-grid"><section class="kx-fin-panel kx-fin-chart-panel"><header><div><small>EVOLUCIÓN</small><h2>Generado · Cobrado · Pendiente</h2></div><span>Interactivo</span></header>${renderMonthlyChart(dashboard.months||[])}</section><section class="kx-fin-panel"><header><div><small>OPERATIVA</small><h2>Requiere atención</h2></div></header>${renderAttention(dashboard.attention||{})}</section></div>
    <section class="kx-fin-panel"><header><div><small>ANTIGÜEDAD</small><h2>Deuda por vencimiento</h2></div><span>Selecciona un tramo</span></header>${renderAging(dashboard.aging||[])}</section>
    <div class="kx-fin-dashboard-grid"><section class="kx-fin-panel"><header><div><small>CATEGORÍAS</small><h2>Distribución financiera</h2></div></header><div class="kx-fin-category-list">${(dashboard.categories||[]).map(c=>`<button type="button" data-category="${esc(c.categoria)}" class="${filters.categoria===c.categoria?'active':''}"><span>${esc(categoryLabel(c.categoria))}</span><strong>${money(c.generado)}</strong><small>${money(c.pendiente)} pendiente</small></button>`).join('')||empty('Sin categorías','No hay cargos para estos filtros.')}</div></section><section class="kx-fin-panel"><header><div><small>PRÓXIMO</small><h2>Qué sucederá automáticamente</h2></div><span>${ctx.finance_recurring_enabled?'Automático':'Shadow / manual'}</span></header>${renderNextAutomations(dashboard.next_automations||[])}</section></div>
  </section>`;
}

function rowHtml(r){return `<tr class="kx-fin-row" data-charge-id="${esc(r.cuota_id)}" tabindex="0"><td><strong>${esc(`${r.socio_apellidos||''}, ${r.socio_nombre||''}`.replace(/^,\s*/,''))}</strong><small>${esc(r.grupos||r.disciplinas||'')}</small></td><td><strong>${esc(r.concepto)}</strong><small>${esc(categoryLabel(r.categoria))}</small></td><td>${esc(String(r.periodo||'').slice(0,7))}</td><td>${money(r.importe)}</td><td>${money(r.pagado_validado)}</td><td><strong>${money(r.saldo)}</strong></td><td>${dateFmt(r.vencimiento)}${Number(r.dias_vencido)>0?`<small>${Number(r.dias_vencido)} días</small>`:''}</td><td>${badge(r.estado,statusKind(r.estado))}</td><td>${r.regla_nombre?esc(r.regla_nombre):'Manual'}</td></tr>`;}
function mobileRowHtml(r){return `<button type="button" class="kx-fin-mobile-charge" data-charge-id="${esc(r.cuota_id)}"><span><strong>${esc(`${r.socio_nombre||''} ${r.socio_apellidos||''}`.trim())}</strong><small>${esc(r.concepto)} · ${esc(String(r.periodo||'').slice(0,7))}</small></span><span><strong>${money(r.saldo)}</strong>${badge(r.estado,statusKind(r.estado))}<small>Vence ${dateFmt(r.vencimiento)}</small></span></button>`;}

function renderRows(rowsData){
  const rows=rowsData.rows||[];const total=Number(rowsData.total||0);const limit=Number(rowsData.limit||60);const start=Number(rowsData.offset||0);
  if(!rows.length)return empty('Sin cargos para estos filtros','Prueba a limpiar filtros o crear un nuevo cargo.');
  return `<div class="kx-fin-table desktop-fin-table"><table><thead><tr><th>Alumno</th><th>Concepto</th><th>Periodo</th><th>Importe</th><th>Cobrado</th><th>Pendiente</th><th>Vencimiento</th><th>Estado</th><th>Regla</th></tr></thead><tbody>${rows.map(rowHtml).join('')}</tbody></table></div><div class="kx-fin-mobile-list">${rows.map(mobileRowHtml).join('')}</div><div class="kx-fin-pagination"><span>${start+1}–${Math.min(start+rows.length,total)} de ${total}</span><div><button class="btn btn-ghost btn-sm" id="fin-prev" ${start<=0?'disabled':''}>Anterior</button><button class="btn btn-ghost btn-sm" id="fin-next" ${start+limit>=total?'disabled':''}>Siguiente</button></div></div>`;
}

function renderCharges(rowsData){return `<section class="kx-fin-panel kx-fin-table-panel"><header><div><small>DRILL-DOWN</small><h2>Cargos</h2></div><span>Selecciona una fila para abrir el detalle</span></header>${renderRows(rowsData)}</section>`;}

function renderAutomations(ctx,rules,scopes){
  const scopeMap=new Map();for(const s of scopes||[]){if(!scopeMap.has(s.regla_id))scopeMap.set(s.regla_id,[]);scopeMap.get(s.regla_id).push(s);}
  const flags=[['finance_v2_enabled','Núcleo v2'],['finance_dashboard_v2_enabled','Dashboard premium'],['finance_recurring_enabled','Recurrencias automáticas'],['finance_reports_enabled','Informes PDF']];
  return `<div class="kx-fin-automation-layout"><section class="kx-fin-panel"><header><div><small>CONTROL DE DESPLIEGUE</small><h2>Feature flags del club</h2></div><span>Rollback sin borrar datos</span></header><div class="kx-fin-flags">${flags.map(([key,label])=>`<div><span><strong>${esc(label)}</strong><small>${key}</small></span><button type="button" class="btn btn-sm ${ctx[key]?'btn-primary':'btn-ghost'}" data-feature-key="${key}" data-feature-enabled="${ctx[key]?'1':'0'}" ${!ctx.can_direction?'disabled':''}>${ctx[key]?'Activado':'Desactivado'}</button></div>`).join('')}</div></section><section class="kx-fin-panel"><header><div><small>AUTOMATIZACIONES</small><h2>Reglas de cobro</h2></div><button class="btn btn-primary btn-sm" id="new-fin-rule">Nueva automatización</button></header><div class="kx-fin-rule-list">${(rules||[]).map(r=>{const ss=scopeMap.get(r.id)||[];const scopeText=ss.map(s=>s.tipo).join(', ')||'Sin destinatarios';return `<article class="kx-fin-rule ${r.activa?'':'is-disabled'}"><div><span>${badge(categoryLabel(r.categoria),r.activa?'ok':'neutral')}</span><h3>${esc(r.nombre)}</h3><p>${esc(r.concepto)} · ${money(r.importe)} · ${esc(r.periodicidad)}</p><small>${esc(scopeText)} · genera día ${r.dia_generacion} · vence día ${r.dia_vencimiento}</small></div><div class="kx-fin-rule-actions"><button class="btn btn-ghost btn-sm" data-rule-shadow="${esc(r.id)}">Simular</button><button class="btn btn-ghost btn-sm" data-rule-generate="${esc(r.id)}">Generar ahora</button><button class="btn btn-ghost btn-sm" data-open-rule="${esc(r.id)}">Detalle</button></div></article>`}).join('')||empty('Aún no hay automatizaciones','Crea la primera regla y ejecútala primero en modo simulación.')}</div></section></div>`;
}

function renderPayments(payments,members){
  const memberMap=new Map((members||[]).map(m=>[m.id,m]));const pending=(payments||[]).filter(p=>p.estado_validacion==='pendiente');
  return `<section class="kx-fin-panel"><header><div><small>TESORERÍA</small><h2>Pagos por validar</h2></div><span>${pending.length} pendientes</span></header>${pending.length?`<div class="kx-fin-payment-list">${pending.map(p=>{const m=memberMap.get(p.socio_id);return `<article><div><strong>${esc(m?`${m.nombre} ${m.apellidos}`:'Alumno')}</strong><small>${dateFmt(p.fecha)} · ${esc(p.metodo||'—')} · ${esc(p.referencia||'Sin referencia')}</small></div><strong>${money(p.importe)}</strong><div><button class="btn btn-primary btn-sm" data-validate-payment="${esc(p.id)}">Validar</button><button class="btn btn-ghost btn-sm" data-reject-payment="${esc(p.id)}">Rechazar</button></div></article>`}).join('')}</div>`:empty('Todo al día','No hay pagos pendientes de validar.')}</section>`;
}

function renderReceipts(receipts,members){
  const memberMap=new Map((members||[]).map(m=>[m.id,m]));
  return `<section class="kx-fin-panel"><header><div><small>DOCUMENTOS</small><h2>Recibos</h2></div><span>Un recibo final por cargo completado</span></header>${(receipts||[]).length?`<div class="kx-fin-receipts">${receipts.map(r=>{const m=memberMap.get(r.socio_id);return `<button type="button" data-receipt-id="${esc(r.id)}"><span><strong>${esc(r.numero||'Recibo')}</strong><small>${esc(m?`${m.nombre} ${m.apellidos}`:'')} · ${dateFmt(r.fecha_pago)}</small></span><span><strong>${money(r.importe)}</strong>${r.anulado_en?badge('Anulado','danger'):badge('Cobrado','ok')}</span></button>`}).join('')}</div>`:empty('Sin recibos','Los recibos aparecerán cuando un cargo quede completamente pagado.')}</section>`;
}

function reportRow(r){return `<article class="kx-fin-report-row"><div><strong>${esc(r.titulo)}</strong><small>${esc(r.identificador)} · v${Number(r.version||1)} · ${dateFmt(r.generado_en)}</small></div><span>${badge(r.archivo_estado,r.archivo_estado==='listo'?'ok':r.archivo_estado==='error'?'danger':'warn')}</span><div><button class="btn btn-ghost btn-sm" data-report-open="${esc(r.id)}" ${r.archivo_estado!=='listo'?'disabled':''}>Abrir PDF</button>${r.archivo_estado==='pendiente'?`<button class="btn btn-primary btn-sm" data-report-retry="${esc(r.id)}">Archivar PDF</button>`:''}<button class="btn btn-ghost btn-sm" data-report-update="${esc(r.id)}">Versión actualizada</button></div></article>`;}
function renderReports(ctx,reports){return `<section class="kx-fin-panel"><header><div><small>INFORMES</small><h2>Snapshots financieros</h2></div>${ctx.finance_reports_enabled?'<button class="btn btn-primary btn-sm" id="generate-fin-report">Generar informe de esta vista</button>':ctx.can_direction?'<button class="btn btn-ghost btn-sm" id="enable-fin-reports">Activar informes</button>':''}</header>${ctx.finance_reports_enabled?((reports||[]).length?`<div class="kx-fin-report-list">${reports.map(reportRow).join('')}</div>`:empty('Aún no hay informes','Genera un informe de la vista actual. Quedará congelado y archivado.')):`<div class="kx-fin-disabled-feature"><strong>Informes desactivados para este club</strong><p>Actívalos cuando el piloto esté preparado. La activación no modifica datos financieros existentes.</p></div>`}</section>`;}

function filterPanel(cats,rules){
  const c=catalogs||{members:[],groups:[],disciplines:[],tariffs:[]};
  return `<details class="kx-fin-filter-panel"><summary>Filtros avanzados</summary><div class="kx-fin-filter-grid"><label>Año<input id="fin-filter-year" type="number" min="2020" max="2200" value="${esc(filters.year||'')}"></label><label>Mes<select id="fin-filter-month"><option value="">Todos</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${String(filters.month)===String(i+1)?'selected':''}>${i+1}</option>`).join('')}</select></label><label>Alumno<select id="fin-filter-student"><option value="">Todos</option>${c.members.map(x=>`<option value="${esc(x.id)}" ${filters.socio_id===x.id?'selected':''}>${esc(`${x.apellidos}, ${x.nombre}`)}</option>`).join('')}</select></label><label>Grupo<select id="fin-filter-group"><option value="">Todos</option>${c.groups.map(x=>`<option value="${esc(x.id)}" ${filters.grupo_id===x.id?'selected':''}>${esc(x.nombre)}</option>`).join('')}</select></label><label>Disciplina<select id="fin-filter-discipline"><option value="">Todas</option>${c.disciplines.map(x=>`<option value="${esc(x.id)}" ${filters.disciplina_id===x.id?'selected':''}>${esc(x.nombre)}</option>`).join('')}</select></label><label>Categoría<select id="fin-filter-category"><option value="">Todas</option>${CATEGORY.map(([v,l])=>`<option value="${v}" ${filters.categoria===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Regla<select id="fin-filter-rule"><option value="">Todas</option>${(rules||[]).map(x=>`<option value="${esc(x.id)}" ${filters.regla_id===x.id?'selected':''}>${esc(x.nombre)}</option>`).join('')}</select></label><label>Método<select id="fin-filter-method"><option value="">Todos</option>${PAYMENT_METHODS.map(x=>`<option value="${x}" ${filters.metodo===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div><button class="btn btn-primary btn-sm" id="apply-fin-filters">Aplicar filtros</button></div></details>`;
}

async function renderPremium(ctx){
  setMainHtml('<div class="loading-card">Cargando Finanzas Premium…</div>');
  try{
    await loadCatalogs();
    const [dashboard,rowsData,rules,scopes,payments,receipts,reports]=await Promise.all([
      premium.dashboard(cleanFilters()),premium.rows(cleanFilters(),60,offset),premium.rules(),premium.ruleScopes(),repos.finance.payments(300),repos.finance.receipts(300),ctx.finance_reports_enabled?premium.reports():Promise.resolve([])
    ]);
    const actions='<button class="btn btn-primary" id="new-fin-charge">+ Nuevo cargo</button><button class="btn btn-ghost" id="new-fin-automation">Nueva automatización</button>'+(Number(ctx.pagos_por_validar||0)>0?`<button class="btn btn-ghost" id="jump-fin-payments">Pagos por validar <b>${Number(ctx.pagos_por_validar)}</b></button>`:'')+(ctx.finance_reports_enabled?'<button class="btn btn-ghost" id="quick-fin-report">Generar informe</button>':'');
    const body=tab==='summary'?renderSummary(ctx,dashboard):tab==='charges'?renderCharges(rowsData):tab==='automations'?renderAutomations(ctx,rules,scopes):tab==='payments'?renderPayments(payments,catalogs.members):tab==='receipts'?renderReceipts(receipts,catalogs.members):renderReports(ctx,reports);
    setMainHtml(`${pageHeader('Finanzas Premium','Control financiero, automatización y trazabilidad sin procesar dinero dentro de KOMBAX.',actions,'FINANZAS 2.0')}${navTabs(ctx)}${filterChips()}${filterPanel(dashboard.categories||[],rules)}${body}`);
    bindPremium(ctx,{dashboard,rowsData,rules,scopes,payments,receipts,reports});
    await handleDeepLink();
  }catch(error){setError(error);setMainHtml(`${pageHeader('Finanzas Premium')}<div class="alert alert-error"><strong>No se pudo cargar la experiencia premium</strong><span>${esc(humanError(error))}</span></div><button class="btn btn-ghost" id="finance-fallback">Abrir Finanzas clásica</button>`);document.getElementById('finance-fallback')?.addEventListener('click',renderFinance);}
}

function mountPilotActivator(ctx){
  if(!ctx?.can_direction)return;
  const root=document.getElementById('main-view');if(!root||root.querySelector('.kx-fin-pilot-banner'))return;
  root.insertAdjacentHTML('afterbegin',`<section class="kx-fin-pilot-banner"><div><small>FINANZAS PREMIUM 2.0</small><strong>Disponible como piloto controlado</strong><span>Activa núcleo + dashboard. Las recurrencias y los informes permanecen desactivados hasta validarlos.</span></div><button class="btn btn-primary" id="activate-finance-pilot">Activar piloto</button></section>`);
  document.getElementById('activate-finance-pilot')?.addEventListener('click',async()=>{if(busy)return;busy=true;try{await premium.setFeature('finance_v2_enabled',true);await premium.setFeature('finance_dashboard_v2_enabled',true);toast('Finanzas Premium activado para este club');await renderFinanceEntry();}catch(e){setError(e)}finally{busy=false}});
}

export async function renderFinanceEntry(){
  if(PORTAL_ROLES.has(state.session?.rol))return renderFinance();
  let ctx;try{ctx=await premium.context();}catch{return renderFinance();}
  if(!ctx?.finance_dashboard_v2_enabled){await renderFinance();mountPilotActivator(ctx);return;}
  return renderPremium(ctx);
}

function bindPremium(ctx,data){
  document.querySelectorAll('[data-fin-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.finTab;offset=0;renderPremium(ctx)}));
  document.querySelectorAll('[data-remove-filter]').forEach(b=>b.addEventListener('click',()=>{delete filters[b.dataset.removeFilter];offset=0;renderPremium(ctx)}));
  document.getElementById('kx-fin-clear-filters')?.addEventListener('click',()=>{filters={year:String(new Date().getFullYear())};offset=0;renderPremium(ctx)});
  document.getElementById('apply-fin-filters')?.addEventListener('click',()=>{filters={...filters,year:document.getElementById('fin-filter-year')?.value||'',month:document.getElementById('fin-filter-month')?.value||'',socio_id:document.getElementById('fin-filter-student')?.value||'',grupo_id:document.getElementById('fin-filter-group')?.value||'',disciplina_id:document.getElementById('fin-filter-discipline')?.value||'',categoria:document.getElementById('fin-filter-category')?.value||'',regla_id:document.getElementById('fin-filter-rule')?.value||'',metodo:document.getElementById('fin-filter-method')?.value||''};offset=0;renderPremium(ctx)});
  document.querySelectorAll('[data-fin-focus]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.finFocus;if(f==='all'||filters.focus===f)delete filters.focus;else filters.focus=f;offset=0;tab='summary';renderPremium(ctx)}));
  document.querySelectorAll('[data-chart-month]').forEach(b=>b.addEventListener('click',()=>{const [year,month]=String(b.dataset.chartMonth||'').split('-');if(year)filters.year=String(Number(year));if(month)filters.month=String(Number(month));offset=0;tab='charges';renderPremium(ctx)}));
  document.querySelectorAll('[data-aging]').forEach(b=>b.addEventListener('click',()=>{filters.aging=filters.aging===b.dataset.aging?'':b.dataset.aging;offset=0;tab='charges';renderPremium(ctx)}));
  document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{filters.categoria=filters.categoria===b.dataset.category?'':b.dataset.category;offset=0;renderPremium(ctx)}));
  document.querySelectorAll('[data-attention]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.attention;if(id==='payments')tab='payments';else if(id==='overdue'){filters.focus='vencido';tab='charges'}else if(id==='automation-errors')tab='automations';else if(id==='paused')tab='charges';offset=0;renderPremium(ctx)}));
  document.querySelectorAll('[data-charge-id]').forEach(el=>{const fn=()=>openChargeDetail(el.dataset.chargeId,ctx);el.addEventListener('click',fn);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn()}})});
  document.getElementById('fin-prev')?.addEventListener('click',()=>{offset=Math.max(0,offset-60);renderPremium(ctx)});document.getElementById('fin-next')?.addEventListener('click',()=>{offset+=60;renderPremium(ctx)});
  document.getElementById('new-fin-charge')?.addEventListener('click',()=>openChargeWizard(ctx));document.getElementById('new-fin-automation')?.addEventListener('click',()=>openRuleWizard(ctx));document.getElementById('new-fin-rule')?.addEventListener('click',()=>openRuleWizard(ctx));
  document.getElementById('jump-fin-payments')?.addEventListener('click',()=>{tab='payments';renderPremium(ctx)});document.getElementById('quick-fin-report')?.addEventListener('click',()=>generateReport(ctx));document.getElementById('generate-fin-report')?.addEventListener('click',()=>generateReport(ctx));
  document.getElementById('enable-fin-reports')?.addEventListener('click',async()=>{try{await premium.setFeature('finance_reports_enabled',true);toast('Informes activados');await renderFinanceEntry()}catch(e){setError(e)}});
  document.querySelectorAll('[data-feature-key]').forEach(b=>b.addEventListener('click',()=>toggleFeature(b.dataset.featureKey,b.dataset.featureEnabled==='1',ctx)));
  document.querySelectorAll('[data-rule-shadow]').forEach(b=>b.addEventListener('click',()=>shadowRule(b.dataset.ruleShadow,ctx)));document.querySelectorAll('[data-rule-generate]').forEach(b=>b.addEventListener('click',()=>generateRule(b.dataset.ruleGenerate,ctx)));document.querySelectorAll('[data-open-rule]').forEach(b=>b.addEventListener('click',()=>openRuleDetail(b.dataset.openRule,data.rules,data.scopes,ctx)));
  document.querySelectorAll('[data-validate-payment]').forEach(b=>b.addEventListener('click',()=>reviewPayment(b.dataset.validatePayment,'validar',ctx)));document.querySelectorAll('[data-reject-payment]').forEach(b=>b.addEventListener('click',()=>reviewPayment(b.dataset.rejectPayment,'rechazar',ctx)));
  document.querySelectorAll('[data-receipt-id]').forEach(b=>b.addEventListener('click',()=>openReceiptDetail(b.dataset.receiptId)));
  document.querySelectorAll('[data-report-open]').forEach(b=>b.addEventListener('click',()=>openReport(b.dataset.reportOpen)));document.querySelectorAll('[data-report-retry]').forEach(b=>b.addEventListener('click',()=>archiveExistingReport(b.dataset.reportRetry,ctx)));document.querySelectorAll('[data-report-update]').forEach(b=>b.addEventListener('click',()=>generateReport(ctx,b.dataset.reportUpdate)));
}

async function toggleFeature(key,enabled,ctx){
  const label={finance_v2_enabled:'núcleo v2',finance_dashboard_v2_enabled:'dashboard premium',finance_recurring_enabled:'recurrencias automáticas',finance_reports_enabled:'informes'}[key]||key;
  if(key==='finance_recurring_enabled'&&!enabled&&!confirm('Activar recurrencias reales para este club. Solo debe hacerse después de validar las reglas en modo simulación. ¿Continuar?'))return;
  if(enabled&&key==='finance_v2_enabled'&&!confirm('Desactivar el núcleo premium también desactivará dashboard, recurrencias e informes. Los datos y cargos existentes se conservarán. ¿Continuar?'))return;
  try{await premium.setFeature(key,!enabled);toast(`${label}: ${!enabled?'activado':'desactivado'}`);await renderFinanceEntry()}catch(e){setError(e)}
}

async function shadowRule(id,ctx){try{const out=await premium.shadowRule(id,isoDate(),false);toast(`Simulación: ${Number(out.candidatos||0)} candidatos · ${Number(out.creados||0)} escritos`);await showRulePreview(id)}catch(e){setError(e)}}
async function generateRule(id,ctx){if(!confirm('Generar ahora comparte las mismas protecciones de idempotencia. No borra cargos previos. ¿Continuar?'))return;try{const out=await premium.generateRuleNow(id,isoDate(),false);toast(`Generación completada: ${Number(out.creados||0)} cargos nuevos`);offset=0;await renderPremium(ctx)}catch(e){setError(e)}}
async function showRulePreview(id){try{const rows=await premium.previewRule(id,isoDate(),false);openDetail({title:'Simulación de cargos',subtitle:`${rows.filter(x=>x.decision==='generar').length} cargos se generarían`,width:'900px',body:`<div class="kx-fin-preview-list">${rows.map(r=>`<div><span><strong>${esc(r.socio_nombre)}</strong><small>${esc(r.decision)}</small></span><span>${money(r.importe)} · ${dateFmt(r.vencimiento)}</span></div>`).join('')}</div>`})}catch(e){setError(e)}}

function scopesFromForm(type,value){if(type==='todos')return[{tipo:'todos'}];if(type==='socios')return String(value||'').split(',').filter(Boolean).map(id=>({tipo:'socio',id}));return value?[{tipo:type,id:value}]:[];}
function scopeStepHtml(type,value){const c=catalogs;const select=(items,label)=>`<label>${label}<select id="fin-wiz-scope-value">${items.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}</option>`).join('')}</select></label>`;if(type==='socios')return `<label>Alumnos<select id="fin-wiz-scope-multi" multiple size="8">${c.members.map(x=>`<option value="${esc(x.id)}">${esc(`${x.apellidos}, ${x.nombre}`)}</option>`).join('')}</select><small>Ctrl/Cmd o toque múltiple según dispositivo.</small></label>`;if(type==='grupo')return select(c.groups.map(x=>({id:x.id,label:x.nombre})),'Grupo');if(type==='disciplina')return select(c.disciplines.map(x=>({id:x.id,label:x.nombre})),'Disciplina');return '<div class="kx-fin-wizard-note"><strong>Todos los alumnos activos</strong><span>Los alumnos dados de baja no se incluirán.</span></div>';}

function openChargeWizard(ctx){
  const model={categoria:'cuota',concepto:'',scopeType:'grupo',scopes:[],importe:'',periodo:`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}-01`,vencimiento:isoDate(),observaciones:'',preview:null};let step=1;
  const {wrap}=openDetail({title:'+ Nuevo cargo',subtitle:'Preview obligatorio antes de crear cualquier lote',width:'820px',body:'<div id="fin-charge-wizard"></div>'});
  const host=wrap.querySelector('#fin-charge-wizard');
  const render=()=>{const names=['Categoría','Concepto','Destinatarios','Importe','Periodo','Vencimiento','Observaciones','Preview'];let content='';if(step===1)content=`<label>Categoría<select id="fin-wiz-category">${CATEGORY.map(([v,l])=>`<option value="${v}" ${model.categoria===v?'selected':''}>${l}</option>`).join('')}</select></label>`;if(step===2)content=`<label>Concepto<input id="fin-wiz-concept" value="${esc(model.concepto)}" placeholder="Ej. Licencia Kickboxing"></label>`;if(step===3)content=`<label>Destinatarios<select id="fin-wiz-scope-type"><option value="socios" ${model.scopeType==='socios'?'selected':''}>Alumno(s)</option><option value="grupo" ${model.scopeType==='grupo'?'selected':''}>Grupo</option><option value="disciplina" ${model.scopeType==='disciplina'?'selected':''}>Disciplina</option><option value="todos" ${model.scopeType==='todos'?'selected':''}>Todos los activos</option></select></label><div id="fin-wiz-scope-host">${scopeStepHtml(model.scopeType)}</div>`;if(step===4)content=`<label>Importe individual (€)<input id="fin-wiz-amount" type="number" min="0" step="0.01" value="${esc(model.importe)}"></label>`;if(step===5)content=`<label>Periodo<input id="fin-wiz-period" type="date" value="${esc(model.periodo)}"></label>`;if(step===6)content=`<label>Vencimiento<input id="fin-wiz-due" type="date" value="${esc(model.vencimiento)}"></label>`;if(step===7)content=`<label>Observaciones<textarea id="fin-wiz-notes" rows="5" placeholder="Opcional">${esc(model.observaciones)}</textarea></label>`;if(step===8)content=model.preview?`<div class="kx-fin-preview"><div><span>Destinatarios</span><strong>${Number(model.preview.cantidad)}</strong></div><div><span>Concepto</span><strong>${esc(model.preview.concepto)}</strong></div><div><span>Importe individual</span><strong>${money(model.preview.importe_individual)}</strong></div><div><span>Total</span><strong>${money(model.preview.total)}</strong></div><div><span>Vencimiento</span><strong>${dateFmt(model.preview.vencimiento)}</strong></div><div class="full"><span>Alumnos</span><p>${(model.preview.destinatarios||[]).map(x=>esc(x.nombre)).join(' · ')}</p></div></div>`:'<div class="loading-card">Calculando preview autoritativo…</div>';
    host.innerHTML=`<div class="kx-fin-wizard"><ol>${names.map((n,i)=>`<li class="${i+1===step?'active':i+1<step?'done':''}"><span>${i+1}</span><b>${n}</b></li>`).join('')}</ol><section><h3>${names[step-1]}</h3>${content}</section><footer><button class="btn btn-ghost" id="fin-wiz-back" ${step===1?'disabled':''}>Atrás</button><span>Paso ${step} de 8</span>${step<8?'<button class="btn btn-primary" id="fin-wiz-next">Continuar</button>':'<button class="btn btn-primary" id="fin-wiz-create">Crear cargos</button>'}</footer></div>`;
    host.querySelector('#fin-wiz-scope-type')?.addEventListener('change',e=>{model.scopeType=e.target.value;host.querySelector('#fin-wiz-scope-host').innerHTML=scopeStepHtml(model.scopeType)});host.querySelector('#fin-wiz-back')?.addEventListener('click',()=>{step--;model.preview=null;render()});host.querySelector('#fin-wiz-next')?.addEventListener('click',async()=>{try{capture();if(step===7){model.preview=await premium.previewCharge(payload());step=8;render()}else{step++;render()}}catch(e){setError(e)}});host.querySelector('#fin-wiz-create')?.addEventListener('click',async()=>{if(!model.preview)return;try{await premium.createCharge({...payload(),preview_hash:model.preview.preview_hash});toast(`${model.preview.cantidad} cargos creados`);wrap.closest('.modal-layer')?.remove();offset=0;tab='charges';await renderFinanceEntry()}catch(e){setError(e)}});
  };
  const capture=()=>{if(step===1)model.categoria=host.querySelector('#fin-wiz-category')?.value||model.categoria;if(step===2){model.concepto=host.querySelector('#fin-wiz-concept')?.value.trim()||'';if(!model.concepto)throw new Error('Indica el concepto.')}if(step===3){if(model.scopeType==='socios'){const ids=[...host.querySelector('#fin-wiz-scope-multi').selectedOptions].map(x=>x.value);model.scopes=scopesFromForm('socios',ids.join(','))}else model.scopes=scopesFromForm(model.scopeType,host.querySelector('#fin-wiz-scope-value')?.value||'');if(!model.scopes.length)throw new Error('Selecciona destinatarios.')}if(step===4){model.importe=host.querySelector('#fin-wiz-amount')?.value;if(model.importe===''||Number(model.importe)<0)throw new Error('Indica un importe válido.')}if(step===5)model.periodo=host.querySelector('#fin-wiz-period')?.value||'';if(step===6)model.vencimiento=host.querySelector('#fin-wiz-due')?.value||'';if(step===7)model.observaciones=host.querySelector('#fin-wiz-notes')?.value||'';};
  const payload=()=>({categoria:model.categoria,concepto:model.concepto,destinatarios:model.scopes,importe:Number(model.importe),periodo:model.periodo,vencimiento:model.vencimiento,observaciones:model.observaciones});render();
}

function openRuleWizard(ctx){
  const c=catalogs;openForm({title:'Nueva automatización',subtitle:'Configúrala una vez. Antes de activar recurrencias, utiliza Simular.',width:'860px',fields:[{name:'nombre',label:'Nombre de la regla',required:true},{name:'concepto',label:'Concepto',required:true},{name:'categoria',label:'Categoría',type:'select',value:'cuota',options:CATEGORY.map(([value,label])=>({value,label}))},{name:'importe',label:'Importe',type:'number',step:'0.01',min:0,required:true},{name:'periodicidad',label:'Periodicidad',type:'select',value:'mensual',options:PERIODICITY.map(([value,label])=>({value,label}))},{name:'fecha_inicio',label:'Fecha de inicio',type:'date',value:isoDate(),required:true},{name:'dia_generacion',label:'Día de generación',type:'number',min:1,max:31,value:1,required:true},{name:'dia_vencimiento',label:'Día de vencimiento',type:'number',min:1,max:31,value:10,required:true},{name:'scope_type',label:'Destinatarios',type:'select',value:'grupo',options:[{value:'grupo',label:'Grupo'},{value:'disciplina',label:'Disciplina'},{value:'todos',label:'Todos los activos'}]},{name:'scope_id',label:'Grupo o disciplina',type:'select',options:[...c.groups.map(x=>({value:`grupo:${x.id}`,label:`Grupo · ${x.nombre}`})),...c.disciplines.map(x=>({value:`disciplina:${x.id}`,label:`Disciplina · ${x.nombre}`}))]},{name:'observaciones',label:'Observaciones',type:'textarea',full:true}],submitText:'Crear automatización',onSubmit:async v=>{const rule=await premium.saveRule({nombre:v.nombre,concepto:v.concepto,categoria:v.categoria,importe:Number(v.importe),periodicidad:v.periodicidad,fecha_inicio:v.fecha_inicio,dia_generacion:Number(v.dia_generacion),dia_vencimiento:Number(v.dia_vencimiento),zona_horaria:state.session?.club?.zona_horaria||'Europe/Madrid',politica_alta:'siguiente_ciclo',activa:true,observaciones:v.observaciones||''});let scopes;if(v.scope_type==='todos')scopes=[{tipo:'todos'}];else{const [type,id]=String(v.scope_id||'').split(':');if(type!==v.scope_type||!id)throw new Error('Selecciona el destinatario correcto.');scopes=[{tipo:type,id}]}await premium.replaceRuleScopes(rule.id,scopes);toast('Automatización creada en modo seguro');tab='automations';await renderFinanceEntry();}});
}

function openRuleDetail(id,rules,scopes,ctx){const r=(rules||[]).find(x=>x.id===id);if(!r)return;const ss=(scopes||[]).filter(x=>x.regla_id===id);openDetail({title:r.nombre,subtitle:'Automatización financiera',width:'760px',body:`<div class="kx-fin-detail-grid"><div><span>Concepto</span><strong>${esc(r.concepto)}</strong></div><div><span>Categoría</span><strong>${esc(categoryLabel(r.categoria))}</strong></div><div><span>Importe</span><strong>${money(r.importe)}</strong></div><div><span>Periodicidad</span><strong>${esc(r.periodicidad)}</strong></div><div><span>Generación</span><strong>Día ${r.dia_generacion}</strong></div><div><span>Vencimiento</span><strong>Día ${r.dia_vencimiento}</strong></div><div class="full"><span>Destinatarios</span><strong>${esc(ss.map(x=>x.tipo).join(', ')||'Sin destinatarios')}</strong></div><div class="full"><span>Política de alta</span><strong>Sin prorrateo automático · siguiente ciclo</strong></div></div>`,actions:`<button class="btn btn-ghost" id="rule-preview-detail">Simular</button><button class="btn btn-primary" id="rule-generate-detail">Generar ahora</button>`});document.getElementById('rule-preview-detail')?.addEventListener('click',()=>showRulePreview(id));document.getElementById('rule-generate-detail')?.addEventListener('click',()=>generateRule(id,ctx));}

async function openChargeDetail(id,ctx){try{const r=await premium.charge(id);if(!r)return;const [payments,receipts]=await Promise.all([repos.finance.payments(500),repos.finance.receipts(500)]);const p=(payments||[]).filter(x=>x.cuota_id===id),rec=(receipts||[]).filter(x=>x.cuota_id===id);const actions=r.saldo>0?'<button class="btn btn-primary" id="fin-detail-collect">Registrar cobro</button>':'';const {wrap}=openDetail({title:r.concepto,subtitle:`${r.socio_nombre} ${r.socio_apellidos}`,width:'880px',body:`<div class="kx-fin-detail-grid"><div><span>Importe</span><strong>${money(r.importe)}</strong></div><div><span>Cobrado validado</span><strong>${money(r.pagado_validado)}</strong></div><div><span>Saldo</span><strong>${money(r.saldo)}</strong></div><div><span>Estado</span><strong>${esc(r.estado)}</strong></div><div><span>Periodo</span><strong>${esc(String(r.periodo||'').slice(0,7))}</strong></div><div><span>Vencimiento</span><strong>${dateFmt(r.vencimiento)}</strong></div><div><span>Categoría</span><strong>${esc(categoryLabel(r.categoria))}</strong></div><div><span>Regla</span><strong>${esc(r.regla_nombre||'Cargo manual')}</strong></div></div><section class="kx-fin-detail-section"><h3>Pagos</h3>${p.length?p.map(x=>`<div><span>${dateFmt(x.fecha)} · ${esc(x.metodo||'—')}</span><strong>${money(x.importe)} · ${esc(x.estado_validacion)}</strong></div>`).join(''):'<p>Sin pagos registrados.</p>'}</section><section class="kx-fin-detail-section"><h3>Recibos</h3>${rec.length?rec.map(x=>`<div><span>${esc(x.numero)}</span><strong>${x.anulado_en?'Anulado':'Disponible'}</strong></div>`).join(''):'<p>El recibo final aparecerá al completar el cargo.</p>'}</section>`,actions});wrap.querySelector('#fin-detail-collect')?.addEventListener('click',()=>{openForm({title:'Registrar cobro',subtitle:'Dinero ya recibido fuera de KOMBAX',fields:[{name:'importe',label:'Importe',type:'number',step:'0.01',min:.01,required:true,value:r.saldo},{name:'fecha',label:'Fecha',type:'date',value:isoDate(),required:true},{name:'metodo',label:'Método',type:'select',value:'transferencia',options:PAYMENT_METHODS.map(x=>({value:x,label:x}))},{name:'referencia',label:'Referencia'},{name:'observaciones',label:'Observaciones',type:'textarea',full:true}],submitText:'Registrar cobro',onSubmit:async v=>{await repos.finance.adminPayment({...v,cuota_id:id,importe:Number(v.importe)});toast('Cobro registrado');await renderFinanceEntry();}})});}catch(e){setError(e)}}

async function reviewPayment(id,decision,ctx){if(decision==='validar'){try{await repos.finance.validate(id,'validar','');toast('Pago validado');await renderPremium(ctx)}catch(e){setError(e)};return;}openForm({title:'Rechazar pago',subtitle:'El pago no contará como cobrado.',fields:[{name:'motivo',label:'Motivo',type:'textarea',required:true,full:true}],submitText:'Rechazar',onSubmit:async v=>{await repos.finance.validate(id,'rechazar',v.motivo);toast('Pago rechazado');await renderPremium(ctx);}});}
async function openReceiptDetail(id){try{const r=await premium.receipt(id);if(!r)return;openDetail({title:`Recibo ${r.numero||''}`,subtitle:r.anulado_en?'Recibo anulado · histórico preservado':'Recibo de cobro',body:`<div class="kx-fin-detail-grid"><div><span>Importe</span><strong>${money(r.importe)}</strong></div><div><span>Fecha de pago</span><strong>${dateFmt(r.fecha_pago)}</strong></div><div><span>Método</span><strong>${esc(r.metodo||'—')}</strong></div><div><span>Estado</span><strong>${r.anulado_en?'Anulado':'Cobrado'}</strong></div><div class="full"><span>Emisor</span><strong>${esc(r.emisor_nombre||state.session?.club?.nombre||'Club')}</strong></div>${r.motivo_anulacion?`<div class="full"><span>Motivo de anulación</span><strong>${esc(r.motivo_anulacion)}</strong></div>`:''}</div>`})}catch(e){setError(e)}}

async function generateReport(ctx,sourceId=null){if(!ctx.finance_reports_enabled)return;try{toast('Creando snapshot financiero…');const snap=await premium.createReport({tipo:'tesoreria',titulo:'Tesorería · vista actual',filters:cleanFilters(),origen_informe_id:sourceId||null});await archiveSnapshot(snap);toast(`Informe ${snap.identificador} archivado`);tab='reports';await renderFinanceEntry()}catch(e){setError(e)}}
async function archiveSnapshot(snap){const blob=buildFinanceReportPdf(snap);const sha=await sha256Blob(blob);await premium.uploadReport(snap.storage_path,blob);await premium.finalizeReport(snap.id,sha,blob.size);return {sha,bytes:blob.size};}
async function archiveExistingReport(id,ctx){try{const snap=await premium.reportSnapshot(id);if(!snap)return;await archiveSnapshot({id:snap.id,identificador:snap.identificador,version:snap.version,titulo:snap.titulo,filtros:snap.filtros,resumen:snap.resumen,dataset:snap.dataset,storage_path:snap.storage_path});toast('PDF archivado');await renderPremium(ctx)}catch(e){setError(e)}}
async function openReport(id){try{const report=await premium.reportSnapshot(id);if(!report?.storage_path)return;const url=await premium.reportUrl(report.storage_path,600);window.open(url,'_blank','noopener')}catch(e){setError(e)}}

async function handleDeepLink(){
  const params=new URLSearchParams(location.search);const target=params.get('finance_target');const entity=params.get('entity_id');const key=`${target}:${entity}`;if(!target||!entity||deepLinkHandled===key)return;deepLinkHandled=key;
  if(target==='charge')return openChargeDetail(entity,await premium.context());if(target==='payment'){tab='payments';return renderFinanceEntry()}if(target==='receipt')return openReceiptDetail(entity);if(target==='automation'){tab='automations';filters.regla_id=entity;return renderFinanceEntry()}
}
