import { repos } from '../core/repositories.js';
import { state } from '../core/state.js';
import { has } from '../core/permissions.js';
import { esc, byName, dateFmt, isoDate, humanError } from '../core/utils.js';
import { pageHeader, progress, quickRow, card, table, empty, badge, openForm, openDetail, confirmDialog, toast, setError, setMainHtml } from '../ui/components.js';
import { icon } from '../ui/icons.js';
import { clubInviteUrl, studentInviteText, shareInvitation, copyInvitation } from '../core/invitations.js';
import { migrationAssistBanner, openMigrationPreparation } from './customer-operations.js';

const DAYS=['','Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const DOC_TYPES=[['inscripcion_asociacion','Inscripción asociación'],['contrato_alta','Ficha / contrato de alta'],['autorizacion','Autorización'],['consentimiento','Consentimiento'],['tutor','Documentación tutor/a'],['certificado','Certificado'],['medico','Documento médico'],['identidad','Identidad'],['otro','Otro']];
const bind=(selector,fn)=>document.querySelectorAll(selector).forEach(el=>el.addEventListener('click',()=>fn(el.dataset.id,el)));
const options=(rows,label=(r)=>r.nombre)=>rows.map(r=>({value:r.id,label:label(r)}));
const ageFromDob=(dob)=>{if(!dob)return null;const d=new Date(`${String(dob).slice(0,10)}T00:00:00`);if(Number.isNaN(d.getTime()))return null;const now=new Date();let age=now.getFullYear()-d.getFullYear();const m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))age--;return age;};

function groupFields(disciplines,schedules=[]){
  const rows=[0,1,2,3,4,5,6].map(i=>schedules[i]||{});
  const f=[
    {name:'disciplina_id',label:'Disciplina',type:'select',required:true,options:options(disciplines.filter(d=>d.activa))},
    {name:'nombre',label:'Nombre',required:true},{name:'monitor_nombre',label:'Monitor/a'},{name:'sala',label:'Sala'},
    {name:'edad_min',label:'Edad mínima',type:'number',min:0},{name:'edad_max',label:'Edad máxima',type:'number',min:0},{name:'plazas',label:'Plazas',type:'number',min:1},{name:'activo',label:'Grupo activo',type:'checkbox',value:true}
  ];
  rows.forEach((r,i)=>{const n=i+1;f.push({name:`dia_${n}`,label:`Horario ${n} · día`,type:'select',options:DAYS.slice(1).map((d,j)=>({value:j+1,label:d})),value:r.dia_semana||''});f.push({name:`inicio_${n}`,label:`Horario ${n} · inicio`,type:'time',value:r.hora_inicio?.slice(0,5)||''});f.push({name:`fin_${n}`,label:`Horario ${n} · fin`,type:'time',value:r.hora_fin?.slice(0,5)||''});});
  return f;
}
function collectSchedules(v){const out=[];for(let i=1;i<=7;i++){if(v[`dia_${i}`]&&v[`inicio_${i}`]&&v[`fin_${i}`])out.push({dia_semana:Number(v[`dia_${i}`]),hora_inicio:v[`inicio_${i}`],hora_fin:v[`fin_${i}`]});}return out;}

export async function renderGroups(){
  setMainHtml('<div class="loading-card">Cargando grupos…</div>');
  try{
    const [allGroups,schedules,disciplines,enrollments]=await Promise.all([repos.groups.list(),repos.groups.schedules(),repos.catalog.disciplines(),repos.members.enrollments()]);
    const groups=allGroups;groups.sort(byName);const can=has(state.session,'group');
    const cards=groups.map(g=>{const d=disciplines.find(x=>x.id===g.disciplina_id);const hs=schedules.filter(h=>h.grupo_id===g.id).map(h=>`${DAYS[h.dia_semana]} ${String(h.hora_inicio).slice(0,5)}–${String(h.hora_fin).slice(0,5)}`);const count=new Set(enrollments.filter(e=>e.grupo_id===g.id&&e.activa).map(e=>e.socio_id)).size;const cap=Number(g.plazas||0),pct=cap?Math.min(100,Math.round(count/cap*100)):0;return `<section class="card brand-card"><div class="card-head"><div><div class="page-kicker">${esc(d?.nombre||'Disciplina')}</div><h2 style="font-size:20px">${esc(g.nombre)}</h2></div><div class="row-actions">${badge(g.activo?'Activo':'Archivado',g.activo?'ok':'neutral')}${can?`<button class="btn btn-ghost btn-sm edit-group" data-id="${esc(g.id)}">${icon('edit',{size:14})} Editar</button><button class="btn btn-ghost btn-sm archive-group" data-id="${esc(g.id)}">${g.activo?'Archivar':'Reactivar'}</button><button class="btn btn-danger btn-sm delete-group" data-id="${esc(g.id)}">${icon('trash',{size:14})} Eliminar</button>`:''}</div></div><div class="grid-2" style="gap:12px"><div><small class="muted">HORARIOS</small><p style="line-height:1.7;margin:8px 0 0">${hs.length?hs.map(esc).join('<br>'):'—'}</p></div><div><small class="muted">MONITOR / SALA</small><p style="line-height:1.7;margin:8px 0 0">${esc(g.monitor_nombre||'Sin asignar')}<br>${esc(g.sala||'—')}</p></div></div><div style="margin-top:18px;display:flex;justify-content:space-between;align-items:end"><div><small class="muted">OCUPACIÓN</small><strong style="display:block;font-size:24px;margin-top:4px">${count}/${g.plazas||'—'}</strong></div><span class="muted">${pct}%</span></div>${progress(pct)}</section>`}).join('');
    setMainHtml(`${pageHeader(state.session?.rol==='monitor'?'Mis grupos':'Grupos y horarios',state.session?.rol==='monitor'?'Grupos asignados a tu perfil':'Clases regulares, ocupación y responsables',can?'<button class="btn btn-primary" id="new-group">Nuevo grupo</button>':'','Club')}<div class="grid-2">${cards||empty('Sin grupos')}</div>`);
    const reload=()=>renderGroups();
    const open=(g={})=>openForm({title:g.id?'Editar grupo':'Nuevo grupo',fields:groupFields(disciplines,schedules.filter(h=>h.grupo_id===g.id)),initial:g,onSubmit:async v=>{await repos.groups.save({...g,...v,id:g.id||null,horarios:collectSchedules(v)});toast('Grupo guardado');await reload();},width:'840px'});
    document.getElementById('new-group')?.addEventListener('click',()=>open());bind('.edit-group',id=>open(groups.find(x=>x.id===id)));
    bind('.archive-group',id=>{const g=groups.find(x=>x.id===id);confirmDialog(g.activo?'Archivar grupo':'Reactivar grupo',g.activo?'El grupo dejará de ofrecerse para nuevas matrículas, pero conservará su histórico.':'El grupo volverá a estar activo.',async()=>{await repos.groups.save({...g,activo:!g.activo,horarios:schedules.filter(h=>h.grupo_id===g.id).map(h=>({dia_semana:h.dia_semana,hora_inicio:String(h.hora_inicio).slice(0,5),hora_fin:String(h.hora_fin).slice(0,5)}))});toast(g.activo?'Grupo archivado':'Grupo reactivado');await reload();},{confirmText:g.activo?'Archivar':'Reactivar'});});
    bind('.delete-group',id=>confirmDialog('Eliminar grupo','Solo se elimina si no tiene matrículas ni sesiones relacionadas. Si ya tuvo actividad, archiva el grupo para conservar el histórico.',async()=>{await repos.groups.delete(id);toast('Grupo eliminado');await reload();},{confirmText:'Eliminar',danger:true}));
  }catch(e){setError(e);setMainHtml(`${pageHeader('Grupos y horarios')} ${empty('No se pudieron cargar los grupos',humanError(e))}`)}
}

async function loadMemberRelations(){const [disciplines,grades,groups,tariffs]=await Promise.all([repos.catalog.disciplines(),repos.catalog.grades(),repos.groups.list(),repos.tariffs.list()]);return {disciplines,grades,groups,tariffs};}
function memberFields(r){return [
  {name:'nombre',label:'Nombre',required:true},{name:'apellidos',label:'Apellidos',required:true},{name:'fecha_nacimiento',label:'Fecha de nacimiento',type:'date'},
  {name:'telefono',label:'Teléfono'},{name:'email',label:'Email',type:'email',help:'Opcional para fichas históricas/migradas. Las nuevas altas de adultos deben usar Preinscripciones y llevan email obligatorio.'},{name:'tutor_nombre',label:'Tutor/a'},
  {name:'disciplina_id',label:'Disciplina · opcional',type:'select',options:options(r.disciplines.filter(d=>d.activa)),help:'La ficha puede guardarse sin disciplina y completarse después.'},{name:'grupo_id',label:'Grupo · opcional',type:'select',options:options(r.groups.filter(g=>g.activo)),help:'No es necesario asignar grupo para registrar al alumno.'},
  {name:'grado_id',label:'Grado',type:'select',options:options(r.grades.filter(g=>g.activo),g=>`${r.disciplines.find(d=>d.id===g.disciplina_id)?.nombre||''} · ${g.nombre}`)},
  {name:'tarifa_id',label:'Tarifa',type:'select',options:options(r.tariffs.filter(t=>t.activa),t=>`${t.nombre} · ${Number(t.importe||0).toFixed(2)} €`)},
  {name:'estado',label:'Estado',type:'select',required:true,options:['prealta','activo','baja','suspendido'].map(x=>({value:x,label:x}))},
  {name:'contacto_emergencia',label:'Contacto de emergencia'},{name:'telefono_emergencia',label:'Teléfono emergencia'},{name:'notas_internas',label:'Notas internas',type:'textarea',full:true}
]}

async function renderMonitorMembers(){
  setMainHtml('<div class="loading-card">Cargando tus alumnos…</div>');
  try{
    const members=await repos.scopes.students();
    const rows=(members||[]).map(m=>`<tr data-member-row data-search="${esc(`${m.nombre||''} ${m.apellidos||''} ${m.email||''} ${m.telefono||''} ${m.disciplinas||''} ${m.grupos||''}`.toLowerCase())}" data-status="${esc(m.estado||'')}"><td><strong>${esc(m.apellidos||'')}, ${esc(m.nombre||'')}</strong></td><td>${m.edad==null?'—':`${Number(m.edad)} años`}</td><td>${esc(m.disciplinas||'—')}<br><small>${esc(m.grupos||'')}</small></td><td>${m.email||m.telefono?`${esc(m.email||'')}${m.email&&m.telefono?'<br>':''}<small>${esc(m.telefono||'')}</small>`:'<span class="muted">Privado</span>'}</td><td>${badge(m.estado||'—',m.estado==='activo'?'ok':m.estado==='suspendido'?'warn':'neutral')}</td></tr>`);
    setMainHtml(`${pageHeader('Mis alumnos','Solo alumnos asignados a tus ámbitos o grupos. Los datos administrativos, familiares, documentales y financieros permanecen separados.','','Privacidad')}
      <div class="alert alert-info"><strong>Acceso por ámbito</strong><span>Si un alumno pertenece a otro monitor no aparecerá aquí. El contacto solo se muestra cuando el Gestor lo autoriza expresamente.</span></div>
      <div class="filter-bar"><input id="member-search" type="search" placeholder="Buscar por alumno, disciplina o grupo…"><select id="member-status"><option value="">Todos los estados</option>${['activo','prealta','suspendido','baja'].map(x=>`<option value="${x}">${x}</option>`).join('')}</select><span class="badge badge-neutral" id="member-count">${members.length} alumnos</span></div>
      ${card('Alumnos asignados',rows.length?table(['Alumno','Edad','Actividad','Contacto','Estado'],rows):empty('Sin alumnos asignados','Pide al Gestor o Coordinación que te asigne un ámbito, alumnos o grupos.'))}`);
    const applyFilter=()=>{const q=String(document.getElementById('member-search')?.value||'').trim().toLowerCase(),st=document.getElementById('member-status')?.value||'';let visible=0;document.querySelectorAll('[data-member-row]').forEach(row=>{const show=(!q||row.dataset.search.includes(q))&&(!st||row.dataset.status===st);row.style.display=show?'':'none';if(show)visible++;});const c=document.getElementById('member-count');if(c)c.textContent=`${visible} alumnos`;};
    document.getElementById('member-search')?.addEventListener('input',applyFilter);document.getElementById('member-status')?.addEventListener('change',applyFilter);
  }catch(e){setError(e);setMainHtml(`${pageHeader('Mis alumnos')} ${empty('No se pudieron cargar tus alumnos',humanError(e))}`)}
}

export async function renderMembers(){
  if(state.session?.rol==='monitor')return renderMonitorMembers();
  setMainHtml('<div class="loading-card">Cargando alumnos…</div>');
  try{
    const can=has(state.session,'member');const canCodes=['direccion','coordinacion'].includes(state.session?.rol);const [members,enrollments,relations,documents,accessCodes,claims,interests]=await Promise.all([repos.members.list(),repos.members.enrollments(),loadMemberRelations(),repos.documents.list().catch(()=>[]),canCodes?repos.accessCodes.get():Promise.resolve(null),can?repos.members.claims().catch(()=>[]):Promise.resolve([]),can?repos.members.interests().catch(()=>[]):Promise.resolve([])]);
    const accessLabel={sin_activar:'Sin activar',invitacion_pendiente:'Invitación pendiente',vinculacion_pendiente:'Vinculación pendiente',activo:'Activo en KOMBAX'};
    const rowFor=(m)=>{const links=enrollments.filter(x=>x.socio_id===m.id&&x.activa);const names=links.map(l=>relations.disciplines.find(d=>d.id===l.disciplina_id)?.nombre).filter(Boolean).join(', ');const groups=links.map(l=>relations.groups.find(g=>g.id===l.grupo_id)?.nombre).filter(Boolean).join(', ');const docs=documents.filter(d=>d.socio_id===m.id&&d.estado!=='archivado'&&d.estado!=='sustituido');const access=m.kombax_acceso_estado||(m.perfil_id?'activo':'sin_activar');const age=ageFromDob(m.fecha_nacimiento);const needsTutor=age!=null&&age<16;const noAccessEmail=!String(m.kombax_acceso_email||m.email||'').trim();const displayAccess=access==='sin_activar'&&noAccessEmail?(needsTutor?'Tutor pendiente':'Falta email'):accessLabel[access]||access;const tone=access==='activo'?'ok':access==='vinculacion_pendiente'||access==='invitacion_pendiente'||(access==='sin_activar'&&noAccessEmail)?'warn':'neutral';return `<tr data-member-row data-search="${esc(`${m.nombre} ${m.apellidos} ${m.email||''} ${m.telefono||''} ${names} ${groups}`.toLowerCase())}" data-status="${esc(m.estado)}"><td><strong>${esc(m.apellidos)}, ${esc(m.nombre)}</strong><br><small>${esc(m.email||m.telefono||'')}</small></td><td>${esc(names||'—')}<br><small>${esc(groups||'')}</small></td><td>${badge(m.estado,m.estado==='activo'?'ok':m.estado==='suspendido'?'warn':m.estado==='baja'?'neutral':'warn')}</td><td>${badge(displayAccess,tone)}<br><small>${esc(m.kombax_acceso_modo==='tutor'?'Acceso mediante tutor':m.kombax_acceso_email||(needsTutor?'El menor de 16 no necesita email propio':''))}</small></td><td>${dateFmt(m.fecha_alta)}</td><td>${badge(`${docs.length} docs`,docs.length?'ok':'warn')}</td><td>${can?`<div class="row-actions"><button class="btn btn-ghost btn-sm edit-member" data-id="${esc(m.id)}">Editar</button>${access!=='activo'&&m.estado!=='baja'&&m.estado!=='suspendido'?`<button class="btn btn-primary btn-sm activate-kombax-member" data-id="${esc(m.id)}">${needsTutor?'Vincular tutor':'Activar KOMBAX'}</button>`:''}<button class="btn btn-ghost btn-sm enroll-member" data-id="${esc(m.id)}">Matrícula</button>${links.length?`<button class="btn btn-ghost btn-sm deactivate-enrollment" data-id="${esc(m.id)}">Baja matrícula</button>`:''}<button class="btn btn-ghost btn-sm graduate-member" data-id="${esc(m.id)}">Graduación</button><button class="btn btn-ghost btn-sm document-member" data-id="${esc(m.id)}">Documento</button>${m.estado!=='baja'?`<button class="btn btn-ghost btn-sm archive-member" data-id="${esc(m.id)}">Dar de baja</button>`:''}<button class="btn btn-danger btn-sm delete-member" data-id="${esc(m.id)}">Eliminar</button></div>`:''}</td></tr>`};
    const claimRows=(claims||[]).map(c=>quickRow(icon('link'),`${c.nombre} ${c.apellidos}`,`Cuenta verificada: ${c.account_email||'—'}`,`<div class="row-actions"><button class="btn btn-primary btn-sm approve-member-claim" data-id="${esc(c.claim_id)}">Aprobar vínculo</button><button class="btn btn-ghost btn-sm reject-member-claim" data-id="${esc(c.claim_id)}">Rechazar</button></div>`)).join('');
    const interestRows=(interests||[]).map(item=>{const family=item.request_kind==='family';return quickRow(icon('userPlus'),item.account_name||item.account_email||'',`${family?'Familiar / tutor':'Miembro / Practicante'} · ${item.account_email||''} · ${item.message||''}`,`<div class="row-actions"><button class="btn btn-primary btn-sm approve-club-link" data-id="${esc(item.thread_id)}" data-kind="${family?'family':'member'}">${family?'Vincular a alumno':'Autorizar miembro'}</button><button class="btn btn-ghost btn-sm reject-club-link" data-id="${esc(item.thread_id)}">Rechazar</button></div><small>No hace falta código: la autorización del club puede completar la vinculación.</small>`)}).join('');
    const headerActions=(can||canCodes)?`<div class="row-actions">${can?'<button class="btn btn-primary" id="student-email-invite">Invitar alumno por email</button>':''}${canCodes?'<button class="btn btn-ghost" id="student-access-code">Código alumnos/familias</button>':''}${can?'<button class="btn btn-ghost" id="new-member">Nuevo alumno</button>':''}</div>`:'';setMainHtml(`${pageHeader(state.session?.rol==='monitor'?'Mis alumnos':'Alumnos','Fichas, matrículas, grados y expediente documental',headerActions,'Gestión')}${claimRows?card(`Solicitudes de vinculación · ${claims.length}`,claimRows):''}${interestRows?card(`Consultas de acceso · ${interests.length}`,interestRows):''}<div class="filter-bar"><input id="member-search" type="search" placeholder="Buscar por nombre, email, disciplina o grupo…"><select id="member-status"><option value="">Todos los estados</option>${['activo','prealta','suspendido','baja'].map(x=>`<option value="${x}">${x}</option>`).join('')}</select><span class="badge badge-neutral" id="member-count">${members.length} alumnos</span></div>${card('Alumnos',members.length?table(['Alumno','Actividad','Estado','Acceso KOMBAX','Alta','Expediente','Acciones'],members.map(rowFor)):empty('Sin alumnos'))}`);
    document.querySelectorAll('[data-member-row] td:last-child .row-actions').forEach(actions=>{
      const buttons=[...actions.children].filter(node=>node.tagName==='BUTTON');if(buttons.length<=3)return;
      const more=document.createElement('details');more.className='kx-member-more';more.open=!window.matchMedia('(max-width:600px)').matches;
      more.innerHTML='<summary>Más acciones</summary><div class="kx-member-more-grid"></div>';
      buttons.slice(2).forEach(button=>more.lastElementChild.appendChild(button));actions.appendChild(more);
    });
    const headerNode=document.querySelector('#main-view .page-header');
    headerNode?.insertAdjacentHTML('afterend',migrationAssistBanner({title:'¿Ya tienes tus alumnos en Excel, CSV o fichas?',body:'Súbelos a KOMBAX Migrations y revisa la propuesta de importación antes de crear o actualizar fichas.'}));
    document.querySelector('#main-view [data-kx-migration-assist]')?.addEventListener('click',openMigrationPreparation);
    const applyFilter=()=>{const q=String(document.getElementById('member-search')?.value||'').trim().toLowerCase(),st=document.getElementById('member-status')?.value||'';let visible=0;document.querySelectorAll('[data-member-row]').forEach(row=>{const show=(!q||row.dataset.search.includes(q))&&(!st||row.dataset.status===st);row.style.display=show?'':'none';if(show)visible++;});const c=document.getElementById('member-count');if(c)c.textContent=`${visible} alumnos`;};document.getElementById('member-search')?.addEventListener('input',applyFilter);document.getElementById('member-status')?.addEventListener('change',applyFilter);
    const reload=()=>renderMembers();const openMember=(m={estado:'activo'})=>openForm({title:m.id?'Editar alumno':'Nuevo alumno',fields:memberFields(relations),initial:m,onSubmit:async v=>{await repos.members.save({...m,...v,id:m.id||null});toast('Alumno guardado');await reload();},width:'900px'});
    document.getElementById('student-email-invite')?.addEventListener('click',()=>openForm({title:'Invitar alumno o familia por email',subtitle:'La invitación será personal, de un solo uso y quedará vinculada al correo indicado. Puede usarla un alumno/a adulto o el padre, madre o tutor que gestione a un menor.',fields:[{name:'email',label:'Correo electrónico del alumno o tutor',type:'email',required:true,placeholder:'persona@correo.com'},{name:'nombre',label:'Nombre del destinatario (opcional)',placeholder:'Nombre'}],submitText:'Crear y enviar invitación',onSubmit:async v=>{const email=String(v.email||'').trim().toLowerCase();const validAddress=Boolean(email)&&/^\S+@\S+\.\S+$/.test(email);if(!validAddress)throw new Error('Indica un correo electrónico válido.');const invitation=await repos.users.createStudentInvitation(email,v.nombre||'');let sent=false,sendMessage='';try{await repos.users.sendStudentInvitation(invitation.id);sent=true;sendMessage='Invitación enviada por correo.';}catch(error){sendMessage=`La invitación se ha creado, pero el correo no se ha podido enviar: ${humanError(error)}`;}const code=String(invitation?.codigo||'');const clubName=state.session?.club?.nombre||'Tu club';const slug=state.session?.club?.slug||window.UW_CONFIG?.clubSlug||'';const url=clubInviteUrl({clubSlug:slug,type:'alumnos',code});const text=`${clubName} te invita a unirte a KOMBAX como alumno/a o familia. Esta invitación es personal para ${email}. Código: ${code}.`;toast(sent?'Invitación enviada':'Invitación creada; revisa el aviso de envío',sent?'ok':'error');setTimeout(()=>{const detail=openDetail({title:'Invitación personal · Alumno / familia',subtitle:sent?`Enviada a ${email}`:`Preparada para ${email}`,body:`<div class="detail-grid"><div><small>Destinatario</small><h3>${esc(email)}</h3></div><div><small>Código personal</small><h3><code>${esc(code)}</code></h3></div><div><small>Validez</small><p>7 días · un solo uso</p></div><div><small>Uso</small><p>Alumno/a adulto o padre, madre o tutor.</p></div></div><p>${esc(sendMessage)}</p><p>${esc(text)}</p>${url?`<p class="muted"><small>${esc(url)}</small></p>`:''}<div class="row-actions"><button class="btn btn-primary" id="share-student-email-invitation">Compartir invitación</button><button class="btn btn-ghost" id="copy-student-email-invitation">Copiar invitación</button></div>`});detail.wrap.querySelector('#share-student-email-invitation')?.addEventListener('click',async()=>{try{const result=await shareInvitation({title:`${clubName} · Invitación KOMBAX`,text,url});if(result==='copied')toast('Invitación copiada')}catch(e){setError(e)}});detail.wrap.querySelector('#copy-student-email-invitation')?.addEventListener('click',async()=>{await copyInvitation(text,url);toast('Invitación copiada')});},320);}}));
    document.getElementById('new-member')?.addEventListener('click',()=>openMember());
    document.getElementById('student-access-code')?.addEventListener('click',()=>{const code=accessCodes?.alumnos?.codigo||'—';const clubName=state.session?.club?.nombre||'Urban Warriors';const slug=state.session?.club?.slug||window.UW_CONFIG?.clubSlug||'';const url=clubInviteUrl({clubSlug:slug,type:'alumnos',code});const text=studentInviteText({clubName,code});const detail=openDetail({title:'Invitar alumno / familia',subtitle:'Comparte la invitación completa o únicamente el código. El alumno o la familia completará el alta desde su propia cuenta.',body:`<div class="detail-grid"><div><small>Código de alumnos/familias</small><h3><code>${esc(code)}</code></h3></div><div><small>Uso</small><p>Alumnos adultos y padres, madres o tutores. Los menores siguen siempre el flujo de tutor.</p></div></div><p>${esc(text)}</p>${url?`<p class="muted"><small>${esc(url)}</small></p>`:''}<div class="row-actions"><button class="btn btn-primary" id="share-student-invitation">Compartir invitación</button><button class="btn btn-ghost" id="copy-student-invitation">Copiar invitación</button><button class="btn btn-ghost" id="copy-student-access-code">Copiar solo código</button><button class="btn btn-ghost" id="rotate-student-access-code">Cambiar código</button></div>`});detail.wrap.querySelector('#share-student-invitation')?.addEventListener('click',async()=>{try{const result=await shareInvitation({title:`${clubName} · Invitación al club`,text,url});if(result==='copied')toast('Invitación copiada')}catch(e){setError(e)}});detail.wrap.querySelector('#copy-student-invitation')?.addEventListener('click',async()=>{await copyInvitation(text,url);toast('Invitación copiada')});detail.wrap.querySelector('#copy-student-access-code')?.addEventListener('click',async()=>{try{await copyInvitation(code);toast('Código copiado')}catch{prompt('Copia el código',code)}});detail.wrap.querySelector('#rotate-student-access-code')?.addEventListener('click',()=>openForm({title:'Cambiar código de alumnos/familias',subtitle:'Escribe 4 o 5 dígitos o déjalo vacío para generar automáticamente uno nuevo de 5 dígitos.',fields:[{name:'codigo',label:'Nuevo código',placeholder:'Ej. 31415',help:'Solo números · 4 o 5 dígitos'}],submitText:'Cambiar código',onSubmit:async v=>{const value=String(v.codigo||'').trim();if(value&&!/^\d{4,5}$/.test(value))throw new Error('El código debe tener 4 o 5 dígitos numéricos.');await repos.accessCodes.rotate('alumnos',value);toast('Código de alumnos/familias actualizado');await renderMembers();}}));});
    bind('.activate-kombax-member',id=>{const m=members.find(x=>x.id===id);if(!m)return;const age=ageFromDob(m.fecha_nacimiento);if(age==null){setError(new Error('Completa la fecha de nacimiento antes de activar KOMBAX.'));return;}const needsTutor=age<16;openForm({title:`${needsTutor?'Vincular tutor':'Activar KOMBAX'} · ${m.nombre} ${m.apellidos}`,subtitle:needsTutor?'El menor de 16 conserva su propia ficha. La cuenta KOMBAX será la del padre, madre o tutor autorizado.':'La ficha administrativa ya existe. La invitación vinculará exactamente esta ficha sin crear un duplicado.',fields:[{name:'email',label:needsTutor?'Correo del tutor responsable':'Correo de acceso del alumno',type:'email',required:true,value:m.kombax_acceso_email||m.email||'',help:needsTutor?'El menor de 16 no necesita correo propio. El tutor verificará este correo en su cuenta KOMBAX.':'Debe ser el correo que el alumno usará o ya usa en su cuenta KOMBAX.'}],submitText:'Crear y enviar activación',onSubmit:async v=>{const email=String(v.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))throw new Error('Indica un correo válido.');const invitation=await repos.members.inviteAccess(id,email);let sent=false,sendMessage='';try{await repos.users.sendStudentInvitation(invitation.id);sent=true;sendMessage='Invitación enviada por correo.';}catch(error){sendMessage=`La activación se creó, pero el correo no pudo enviarse: ${humanError(error)}`;}const code=String(invitation?.codigo||'');const clubName=state.session?.club?.nombre||'Tu club';const slug=state.session?.club?.slug||window.UW_CONFIG?.clubSlug||'';const url=clubInviteUrl({clubSlug:slug,type:'alumnos',code});toast(sent?'Activación enviada':'Activación creada; revisa el envío',sent?'ok':'error');setTimeout(()=>{openDetail({title:'Activación de ficha existente',subtitle:`${m.nombre} ${m.apellidos} · ${clubName}`,body:`<div class="detail-grid"><div><small>Estado</small><h3>Invitación pendiente</h3></div><div><small>${needsTutor?'Tutor':'Alumno'}</small><h3>${esc(email)}</h3></div><div><small>Código personal</small><h3><code>${esc(code)}</code></h3></div><div><small>Regla</small><p>${needsTutor?'La cuenta del tutor accede a la ficha del menor de 16.':'No crea otro alumno. Vincula esta ficha.'}</p></div></div><p>${esc(sendMessage)}</p>${url?`<p class="muted"><small>${esc(url)}</small></p>`:''}`});},240);await reload();}});});
    bind('.approve-member-claim',id=>confirmDialog('Aprobar vinculación','La cuenta KOMBAX verificada quedará vinculada a esta ficha administrativa del club. El histórico no se duplica ni se mueve.',async()=>{await repos.members.resolveClaim(id,true);toast('Cuenta vinculada a la ficha');await reload();},{confirmText:'Aprobar vínculo'}));
    bind('.reject-member-claim',id=>confirmDialog('Rechazar vinculación','La solicitud se cerrará y la ficha seguirá sin activar en KOMBAX.',async()=>{await repos.members.resolveClaim(id,false);toast('Solicitud rechazada');await reload();},{confirmText:'Rechazar'}));
    bind('.approve-club-link',(id,el)=>{const kind=el.dataset.kind||'member';if(kind==='family'){openForm({title:'Autorizar acceso familiar',subtitle:'Selecciona el alumno/a al que esta cuenta tendrá acceso como familiar o tutor.',fields:[{name:'socio_id',label:'Alumno/a',type:'select',required:true,options:members.filter(m=>m.estado==='activo').map(m=>({value:m.id,label:`${m.nombre} ${m.apellidos}${m.email?` · ${m.email}`:''}`}))}],submitText:'Autorizar vínculo familiar',onSubmit:async v=>{await repos.kombaxMemberships.resolveClubLink(id,true,v.socio_id);toast('Acceso familiar autorizado');await reload();}});}else{confirmDialog('Autorizar miembro','El club confirma que esta persona forma parte del club. Si no existe una ficha compatible, KOMBAX creará una ficha básica que podrás completar después.',async()=>{await repos.kombaxMemberships.resolveClubLink(id,true,null);toast('Membresía autorizada');await reload();},{confirmText:'Autorizar miembro'});}});
    bind('.reject-club-link',id=>confirmDialog('Rechazar solicitud','La cuenta conservará su perfil público KOMBAX, pero no tendrá acceso privado a este club.',async()=>{await repos.kombaxMemberships.resolveClubLink(id,false,null);toast('Solicitud rechazada');await reload();},{confirmText:'Rechazar'}));
    bind('.edit-member',id=>openMember(members.find(x=>x.id===id)));
    bind('.enroll-member',id=>openForm({title:'Añadir matrícula',subtitle:members.find(x=>x.id===id)?.nombre||'',fields:[{name:'disciplina_id',label:'Disciplina',type:'select',required:true,options:options(relations.disciplines.filter(d=>d.activa))},{name:'grupo_id',label:'Grupo',type:'select',required:true,options:options(relations.groups.filter(g=>g.activo))},{name:'tarifa_id',label:'Tarifa',type:'select',options:options(relations.tariffs.filter(t=>t.activa))}],onSubmit:async v=>{await repos.members.requestEnrollment(id,v.disciplina_id,v.grupo_id,v.tarifa_id);toast('Solicitud de matrícula registrada');await reload();}}));
    bind('.deactivate-enrollment',id=>{const links=enrollments.filter(x=>x.socio_id===id&&x.activa);openForm({title:'Desactivar matrícula',fields:[{name:'matricula_id',label:'Matrícula',type:'select',required:true,options:links.map(l=>({value:l.id,label:`${relations.disciplines.find(d=>d.id===l.disciplina_id)?.nombre||'Disciplina'} · ${relations.groups.find(g=>g.id===l.grupo_id)?.nombre||'Grupo'}`}))}],submitText:'Desactivar',onSubmit:async v=>{await repos.members.deactivateEnrollment(v.matricula_id);toast('Matrícula desactivada');await reload();}})});
    bind('.graduate-member',id=>openForm({title:'Registrar graduación',subtitle:members.find(x=>x.id===id)?.nombre||'',fields:[{name:'disciplina_id',label:'Disciplina',type:'select',required:true,options:options(relations.disciplines.filter(d=>d.activa))},{name:'grado_id',label:'Nuevo grado',type:'select',required:true,options:options(relations.grades.filter(g=>g.activo),g=>`${relations.disciplines.find(d=>d.id===g.disciplina_id)?.nombre||''} · ${g.nombre}`)},{name:'fecha',label:'Fecha',type:'date',required:true,value:isoDate()},{name:'examinador',label:'Examinador/a'},{name:'nota',label:'Nota',type:'textarea',full:true}],onSubmit:async v=>{await repos.members.graduation({...v,socio_id:id});toast('Graduación registrada');await reload();}}));
    bind('.document-member',id=>openForm({title:'Subir al expediente',subtitle:'Documentación privada del alumno',fields:[{name:'tipo',label:'Tipo',type:'select',required:true,options:DOC_TYPES.map(([value,label])=>({value,label}))},{name:'nombre',label:'Nombre del documento'},{name:'fecha_documento',label:'Fecha del documento',type:'date'},{name:'firmado',label:'Documento firmado',type:'checkbox',value:true},{name:'archivo',label:'Archivo',type:'file',required:true,accept:'.pdf,.jpg,.jpeg,.png,.webp',help:'PDF o imagen · máximo 10 MB'},{name:'visible_familia',label:'Visible para familia',type:'checkbox',value:true},{name:'observaciones',label:'Observaciones',type:'textarea',full:true}],onSubmit:async v=>{await repos.documents.upload(id,v.archivo,{...v,nombre:v.nombre||v.archivo.name});toast('Documento guardado en el expediente');await reload();}}));
    bind('.archive-member',id=>openForm({title:'Dar de baja al alumno',subtitle:'Se conserva todo su histórico de asistencia, pagos, recibos y documentación.',fields:[{name:'fecha_baja',label:'Fecha de baja',type:'date',value:isoDate(),required:true},{name:'motivo',label:'Motivo',type:'textarea',full:true,required:true}],submitText:'Dar de baja',onSubmit:async v=>{await repos.members.archive(id,v.motivo,v.fecha_baja);toast('Alumno dado de baja');await reload();}}));
    bind('.delete-member',id=>confirmDialog('Eliminar alumno','Solo se elimina si no tiene actividad histórica. Si ya entrenó, tuvo cuotas, documentos o movimientos, utiliza Dar de baja y conserva su expediente histórico.',async()=>{await repos.members.delete(id);toast('Alumno eliminado');await reload();},{confirmText:'Eliminar',danger:true}));
  }catch(e){setError(e);setMainHtml(`${pageHeader(state.session?.rol==='monitor'?'Mis alumnos':'Alumnos')} ${empty('No se pudieron cargar los alumnos',humanError(e))}`)}
}

export async function renderEnrollments(){
  setMainHtml('<div class="loading-card">Cargando preinscripciones…</div>');
  try{
    const [items,relations]=await Promise.all([repos.preenrollments.list(),loadMemberRelations()]);const can=has(state.session,'enrollmentManage');
    const groups=[{key:'enviada',label:'Nuevas'},{key:'en_revision',label:'En revisión'},{key:'pendiente_documentacion',label:'Documentación'},{key:'lista_espera',label:'Lista de espera'},{key:'aprobada',label:'Aprobadas'}];
    const actions=(p)=>can?`<div class="row-actions">${p.estado==='enviada'?`<button class="btn btn-primary btn-sm approve-pre" data-id="${esc(p.id)}">Aprobar</button><button class="btn btn-ghost btn-sm wait-pre" data-id="${esc(p.id)}">Espera</button><button class="btn btn-ghost btn-sm reject-pre" data-id="${esc(p.id)}">Rechazar</button>`:''}${p.estado!=='aprobada'&&p.estado!=='cancelada'?`<button class="btn btn-ghost btn-sm cancel-pre" data-id="${esc(p.id)}">Cancelar</button>`:''}${['borrador','enviada','rechazada','cancelada'].includes(p.estado)?`<button class="btn btn-danger btn-sm delete-pre" data-id="${esc(p.id)}">Eliminar</button>`:''}</div>`:'';
    const col=(g)=>`<section class="pipeline-col"><h3>${esc(g.label)} · ${items.filter(x=>x.estado===g.key).length}</h3>${items.filter(x=>x.estado===g.key).map(p=>`<div class="pipeline-card"><strong>${esc(p.nombre)} ${esc(p.apellidos)}</strong><small>${esc(p.tipo_solicitud==='menor'?'Menor · acceso tutor':'Adulto')} · ${esc(p.email_acceso||p.tutor_email||'Sin email')}<br>${esc(relations.disciplines.find(d=>d.id===p.disciplina_id)?.nombre||'Sin disciplina')} · ${dateFmt(p.creado_en)}</small>${p.observaciones?`<p class="muted">${esc(p.observaciones)}</p>`:''}${actions(p)}</div>`).join('')||'<div class="muted" style="font-size:11px;padding:10px 2px">Sin solicitudes</div>'}</section>`;
    const extras=items.filter(x=>!groups.some(g=>g.key===x.estado));
    setMainHtml(`${pageHeader('Preinscripciones','Pipeline de solicitudes y altas',can?'<button class="btn btn-primary" id="new-pre">Nueva preinscripción</button>':'','Gestión')}<div class="pipeline">${groups.map(col).join('')}</div>${extras.length?card('Otros estados',extras.map(x=>quickRow(icon('userPlus'),`${x.nombre} ${x.apellidos}`,x.estado,actions(x))).join('')):''}`);
    const reload=()=>renderEnrollments();
    document.getElementById('new-pre')?.addEventListener('click',()=>openForm({title:'Nueva preinscripción',subtitle:'Registro progresivo: primero los datos esenciales; disciplina, grupo, tarifa y teléfono pueden completarse después. Menores: tutor responsable.',fields:[{name:'tipo_solicitud',label:'Tipo',type:'select',required:true,value:'adulto',options:[{value:'adulto',label:'Alumno 16+'},{value:'menor',label:'Menor de 16'}]},{name:'nombre',label:'Nombre',required:true},{name:'apellidos',label:'Apellidos',required:true},{name:'fecha_nacimiento',label:'Fecha de nacimiento',type:'date',required:true},{name:'telefono',label:'Teléfono · opcional'},{name:'email_acceso',label:'Email de acceso / tutor',type:'email',help:'Opcional en una preinscripción administrativa de adulto. Para menores se necesita el email del tutor responsable; si existe una cuenta KOMBAX vinculada, se reutiliza.'},{name:'tutor_nombre',label:'Tutor/a (obligatorio si es menor de 16)'},{name:'parentesco',label:'Parentesco'},{name:'disciplina_id',label:'Disciplina · opcional',type:'select',options:options(relations.disciplines.filter(d=>d.activa)),help:'Puede asignarse después.'},{name:'grupo_id',label:'Grupo · opcional',type:'select',options:options(relations.groups.filter(g=>g.activo)),help:'Puede asignarse después.'},{name:'tarifa_id',label:'Tarifa · opcional',type:'select',options:options(relations.tariffs.filter(t=>t.activa))},{name:'observaciones',label:'Observaciones',type:'textarea',full:true}],onSubmit:async v=>{const email=String(v.email_acceso||'').trim().toLowerCase();if(email&&!/^\S+@\S+\.\S+$/.test(email))throw new Error('Indica un correo electrónico válido.');if(v.tipo_solicitud==='menor'&&!email)throw new Error('Indica el correo del tutor responsable.');const age=ageFromDob(v.fecha_nacimiento);if(age==null)throw new Error('La fecha de nacimiento es obligatoria.');if(v.tipo_solicitud==='adulto'&&age<16)throw new Error('Una persona menor de 16 años debe darse de alta mediante el flujo de tutor.');if(v.tipo_solicitud==='menor'&&age>=16)throw new Error('Una persona de 16 años o más debe usar el alta autónoma de alumno.');if(v.tipo_solicitud==='menor'&&!String(v.tutor_nombre||'').trim())throw new Error('Indica el nombre del tutor responsable.');await repos.preenrollments.create({...v,email_acceso:email});toast('Preinscripción creada · acceso KOMBAX preparado');await reload();}}));
    bind('.approve-pre',async(id,el)=>{el.disabled=true;try{const out=await repos.preenrollments.approve(id);if(out?.invitation_id){try{await repos.users.sendStudentInvitation(out.invitation_id);toast('Preinscripción aprobada · invitación KOMBAX enviada');}catch(error){toast('Preinscripción aprobada · invitación creada, envío pendiente','error');console.warn('KOMBAX activation email:',humanError(error));}}else if(out?.activation==='already_linked'){toast('Preinscripción aprobada · cuenta KOMBAX ya vinculada');}else{toast('Preinscripción aprobada');}await reload();}catch(e){setError(e);el.disabled=false;}});
    const reasonAction=(selector,title,fn,required=false)=>bind(selector,id=>openForm({title,fields:[{name:'motivo',label:'Motivo',type:'textarea',full:true,required}],onSubmit:async v=>{await fn(id,v.motivo);toast('Estado actualizado');await reload();}}));
    reasonAction('.wait-pre','Pasar a lista de espera',repos.preenrollments.wait);reasonAction('.reject-pre','Rechazar preinscripción',repos.preenrollments.reject,true);reasonAction('.cancel-pre','Cancelar preinscripción',repos.preenrollments.cancel,true);
    bind('.delete-pre',id=>confirmDialog('Eliminar solicitud','Solo se permite borrar solicitudes no aprobadas. La acción es definitiva.',async()=>{await repos.preenrollments.delete(id);toast('Solicitud eliminada');await reload();},{confirmText:'Eliminar',danger:true}));
  }catch(e){setError(e);setMainHtml(`${pageHeader('Preinscripciones')} ${empty('No se pudieron cargar las solicitudes',humanError(e))}`)}
}
