import { repos } from '../core/repositories.js';
import { state } from '../core/state.js';
import { esc } from '../core/utils.js';
import { pageHeader, card, quickRow, empty, badge, openDetail, openForm, confirmDialog, toast, setError, setMainHtml } from '../ui/components.js';
import { icon } from '../ui/icons.js';
import { rolesLabel } from '../core/permissions.js';
import { platformFeatures } from '../core/platform.js';

const team=()=>['direccion','coordinacion','secretaria','economia','comunicacion','monitor'].includes(state.session?.rol);
const diffusion=()=>['direccion','coordinacion','secretaria'].includes(state.session?.rol);
const titleFor=(t)=>({condiciones_uso:'Condiciones de uso',privacidad:'Política de privacidad',comunidad:'Normas de Comunidad del Club',derechos_imagen:'Autorización de imagen'})[t]||t;
const roleSet=()=>new Set(state.session?.roles?.length?state.session.roles:[state.session?.rol].filter(Boolean));
const ALL_STAFF=['direccion','coordinacion','secretaria','economia','comunicacion','monitor'];
const CLUB_ADMIN=['direccion','coordinacion'];

const CLUB_MANUAL=[
  {id:'start',group:'Primeros pasos',icon:'home',title:'Inicio y panel del club',summary:'Resumen diario, métricas, accesos rápidos y contexto del club.',route:'dashboard',roles:['todos'],keywords:'inicio dashboard métricas resumen portal club',steps:['Comprueba el club activo y tu identidad en la cabecera.','Revisa avisos, próximos eventos, sesiones y acciones pendientes.','Usa las tarjetas y navegación para entrar directamente en cada área.'],rules:['El contenido del panel cambia según el rol y sus permisos.','Un Monitor ve únicamente sus ámbitos asignados cuando tiene alcance restringido.']},
  {id:'profile',group:'Identidad del club',icon:'dojo',title:'Perfil del club y perfil público',summary:'Logo, portada, información pública, álbum y presencia de tu club en KOMBAX.',route:'profile',roles:['direccion','coordinacion'],keywords:'perfil club público logo portada album identidad actuar como club',steps:['Entra en Mi perfil desde una cuenta de Gestor o Coordinación.','Actualiza la información pública, imágenes y datos visibles.','Usa “Ver como público” para comprobar cómo lo verá la comunidad.'],rules:['La identidad del Club es distinta de la cuenta personal del Gestor.','El actor real se conserva para auditoría aunque publiques como Club.']},
  {id:'access',group:'Altas y acceso',icon:'key',title:'Códigos del club e invitaciones',summary:'Dos códigos cortos reutilizables: alumnos/familias y equipo.',route:'members',roles:['direccion','coordinacion','secretaria'],keywords:'código qr invitación alumnos familias equipo alta cartel',steps:['Desde Alumnos consulta o cambia el código de alumnos/familias.','Desde Equipo consulta o cambia el código de miembros del equipo.','Coloca el código de alumnos junto al QR del cartel de descarga.'],rules:['Los códigos admiten 4 o 5 dígitos y pueden rotarse cuando el club quiera.','El código de equipo nunca concede permisos sensibles automáticamente: crea una solicitud pendiente.','El autorregistro de alumno independiente requiere 16 años o más; menores de 16 se gestionan por club/tutor.']},
  {id:'enrollments',group:'Altas y acceso',icon:'userPlus',title:'Solicitudes de inscripción',summary:'Revisa y valida las solicitudes nuevas antes de convertirlas en alumnos activos.',route:'enrollments',roles:['direccion','coordinacion','secretaria'],keywords:'solicitudes alta inscripción alumno aprobar rechazar',steps:['Abre Solicitudes y revisa los datos enviados.','Comprueba identidad, contacto y datos deportivos requeridos.','Aprueba o rechaza según el procedimiento del club.'],rules:['La solicitud no equivale automáticamente a una membresía activa.','La información de menores debe seguir el flujo de tutor/club.']},
  {id:'students',group:'Alumnos y familias',icon:'user',title:'Alumnos y fichas',summary:'Gestiona altas, ficha personal, datos deportivos, relación familiar y estado.',route:'members',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'alumnos ficha socio datos perfil menor tutor',steps:['Busca al alumno por nombre o grupo.','Abre su ficha para consultar datos y contexto deportivo.','Edita únicamente los campos permitidos por tu rol.'],rules:['Los monitores restringidos solo pueden ver alumnos de sus grupos/cartera asignados.','Los datos familiares, administrativos y económicos están separados por permisos.']},
  {id:'team',group:'Equipo y permisos',icon:'users',title:'Equipo del club, roles y solicitudes',summary:'Gestiona personal, solicitudes del código de equipo y roles operativos.',route:'users',roles:['direccion','coordinacion','secretaria'],keywords:'equipo roles monitor secretaria tesoreria comunicación coordinación solicitud',steps:['Revisa las solicitudes pendientes de acceso del equipo.','Aprueba la persona y asigna el rol operativo correspondiente.','Comprueba después sus ámbitos de trabajo si es Monitor.'],rules:['El código de equipo no asigna un rol por sí solo.','Los permisos dependen del rol y del ámbito asignado.','La elevación a Coordinación/Gestor permanece protegida por reglas específicas.']},
  {id:'scopes',group:'Equipo y permisos',icon:'shieldCheck',title:'Ámbitos y privacidad de monitores',summary:'Asigna grupos, alumnos y capacidades concretas a cada monitor.',route:'scopes',roles:['direccion','coordinacion'],keywords:'monitor ámbito privacidad cartera grupo alumno permisos finanzas',steps:['Selecciona un Monitor.','Asigna los grupos y/o alumnos que debe gestionar.','Define el alcance financiero permitido cuando corresponda.'],rules:['La relación es muchos-a-muchos: un alumno puede estar en más de un grupo y tener más de un monitor autorizado.','Un monitor restringido no debe poder consultar alumnos fuera de su ámbito.']},
  {id:'catalog',group:'Estructura deportiva',icon:'layers',title:'Disciplinas y grados',summary:'Configura disciplinas, niveles y estructura deportiva del club.',route:'catalog',roles:['direccion','coordinacion','secretaria'],keywords:'disciplinas grados cinturones niveles catálogo deporte',steps:['Crea o revisa las disciplinas activas.','Configura los grados/niveles de cada disciplina.','Utiliza esta estructura en grupos, alumnos y progreso.'],rules:['La edición de disciplinas está reservada a roles autorizados.','Los monitores pueden trabajar con grados cuando su permiso lo permite.']},
  {id:'groups',group:'Clases y entrenamiento',icon:'users',title:'Grupos',summary:'Crea grupos, organiza alumnos y define la estructura de entrenamiento.',route:'groups',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'grupos clases alumnos horarios grupo compartido',steps:['Crea el grupo con su nombre y disciplina.','Añade o revisa los alumnos vinculados.','Relaciona el grupo con las sesiones de entrenamiento.'],rules:['Un alumno puede participar en varios grupos cuando el modelo del club lo requiera.','El Monitor solo opera sobre grupos asignados si está restringido.']},
  {id:'sessions',group:'Clases y entrenamiento',icon:'calendar',title:'Sesiones y recurrencia',summary:'Programa clases puntuales o recurrentes, cambios, sustituciones y cancelaciones.',route:'sessions',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'sesiones clases recurrencia calendario sustitución cancelar horario',steps:['Selecciona el grupo y crea la serie o sesión.','Define fecha, hora y recurrencia cuando proceda.','Registra excepciones, cambios o finalización de series desde la propia sesión.'],rules:['Los cambios de una sesión no deben alterar indebidamente toda la serie.','Los monitores restringidos solo modifican sesiones dentro de sus grupos autorizados.']},
  {id:'attendance',group:'Clases y entrenamiento',icon:'checkin',title:'Asistencia y check-in',summary:'Registra presencia/ausencia por sesión y consulta el historial.',route:'attendance',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'asistencia presencia ausencia checkin clase sesión',steps:['Abre Asistencia y selecciona la sesión correspondiente.','Marca la presencia de los alumnos autorizados.','Guarda y revisa el resultado antes de salir.'],rules:['La asistencia está vinculada a sesiones y alumnos reales.','El historial alimenta seguimiento y métricas del club.']},
  {id:'tracking',group:'Seguimiento deportivo',icon:'clipboard',title:'Seguimiento',summary:'Añade observaciones y seguimiento del alumno dentro del ámbito autorizado.',route:'tracking',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'seguimiento observaciones alumno monitor notas progreso',steps:['Busca al alumno autorizado.','Registra la observación o seguimiento pertinente.','Consulta el histórico para mantener continuidad entre sesiones.'],rules:['El seguimiento no debe exponer datos a monitores fuera del ámbito del alumno.','Utiliza información necesaria y profesional, evitando datos irrelevantes.']},
  {id:'progress',group:'Seguimiento deportivo',icon:'chart',title:'Progreso y evaluaciones',summary:'Consulta y actualiza la evolución deportiva, grados y resultados.',route:'progress',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'progreso evaluación grado cinturón resultado deportivo',steps:['Entra en Progreso y selecciona alumno/grupo.','Revisa el nivel actual y evolución registrada.','Actualiza la evaluación cuando tengas permiso.'],rules:['El progreso deportivo es independiente de la información financiera.','Respeta el alcance de grupos/alumnos del Monitor.']},
  {id:'finance',group:'Economía',icon:'wallet',title:'Finanzas, cuotas y cobros',summary:'Gestiona cuotas, estados de pago y operaciones económicas del club.',route:'finance',roles:['direccion','coordinacion','secretaria','economia','monitor','familia','alumno'],keywords:'finanzas cuotas pagos cobros cartera tesorería mensualidad',steps:['Filtra por periodo, alumno o estado.','Registra o revisa el cobro según tu permiso.','Comprueba que el estado final coincide con el movimiento realizado.'],rules:['Los roles ven distinta profundidad financiera.','Un Monitor puede tener alcance ninguno/estado/cartera/cobro/recibos según configuración.','Familias y alumnos solo ven la información económica que les corresponde.']},
  {id:'receipts',group:'Economía',icon:'receipt',title:'Recibos y justificantes',summary:'Consulta recibos generados y abre el justificante completo para imprimir o compartir.',route:'finance',roles:['direccion','coordinacion','secretaria','economia','monitor','familia','alumno'],keywords:'recibo justificante imprimir pago cobro logo',steps:['Localiza el cobro o mensualidad correspondiente.','Abre el recibo completo desde la acción disponible.','Imprime o conserva el justificante desde la vista preparada.'],rules:['El recibo debe corresponder a un cobro real y mantener trazabilidad.','La visibilidad depende del rol y relación con el alumno.']},
  {id:'reminders',group:'Economía',icon:'bell',title:'Avisos de cobro',summary:'Gestiona recordatorios de mensualidades y pagos pendientes.',route:'reminders',roles:['direccion','coordinacion','secretaria','economia'],keywords:'avisos cobro recordatorio deuda pendiente mensualidad',steps:['Filtra los pagos pendientes.','Revisa destinatario y contexto antes de enviar.','Registra el aviso y consulta su estado.'],rules:['Los avisos deben partir de información económica vigente.','Evita duplicar comunicaciones innecesarias.']},
  {id:'communications',group:'Contenido y comunicación',icon:'megaphone',title:'Comunicaciones y avisos',summary:'Publica información oficial del club para los destinatarios adecuados.',route:'communications',roles:['direccion','coordinacion','secretaria','comunicacion'],keywords:'comunicaciones avisos noticia anuncio club',steps:['Crea la comunicación y define el contenido.','Selecciona audiencia o contexto cuando corresponda.','Publica y comprueba la notificación resultante.'],rules:['Diferencia comunicaciones oficiales de publicaciones sociales.','Utiliza los canales internos para información operativa del club.']},
  {id:'events',group:'Contenido y comunicación',icon:'calendar',title:'Eventos',summary:'Crea y gestiona eventos, actividades, competiciones y comunicaciones asociadas.',route:'events',roles:['direccion','coordinacion','secretaria','monitor'],keywords:'eventos competición actividad fecha inscripción recordatorio',steps:['Crea el evento con fecha y descripción.','Configura los datos de participación disponibles.','Publica y revisa su visibilidad en el portal.'],rules:['Los eventos son contenido del club; no sustituyen a las sesiones de entrenamiento.','Los permisos de gestión varían según rol.']},
  {id:'community',group:'Comunidad',icon:'dojo',title:'Comunidad del Club',summary:'Capa interna del club para publicaciones, imágenes/vídeos y comunicación comunitaria.',route:'community',roles:['todos'],keywords:'comunidad club publicación imagen video interna portada',steps:['Acepta las Normas de Comunidad del Club si vas a publicar.','Crea una publicación con el contenido permitido.','Consulta el feed interno y las publicaciones vigentes.'],rules:['Es distinta de KOMBAX Social: esta comunidad está vinculada al club.','Publicar requiere aceptación vigente de las normas.','Se aplican límites de contenido y ciclo de vida configurados.']},
  {id:'social',group:'Comunidad',icon:'network',title:'Combat Social / KOMBAX Social',summary:'Red social pública: publicar, foto/vídeo, corazón, comentarios, guardados y perfiles públicos.',route:'social',roles:['todos'],keywords:'combat social kombax social like corazón comentario foto video publicación perfil público guardar',steps:['Activa una identidad Social elegible y selecciona con quién actúas.','Publica texto y, si quieres, foto/vídeo o contenido del álbum.','Usa el corazón, comenta, responde, guarda y toca nombre/avatar para abrir el perfil público.'],rules:['Miembro de club no se convierte automáticamente en Competidor.','El acceso Social de miembros requiere edad mínima verificada y activación voluntaria.','Los comentarios pueden estar abiertos, solo verificados o cerrados según la publicación.','Nombre y avatar del autor son navegables hacia su perfil público.']},
  {id:'showcase',group:'Comunidad',icon:'spotlight',title:'Showcase',summary:'Escaparate informativo de clubes/marcas: fichas, imágenes, guardar, compartir y CTA externos.',route:'showcase',roles:['todos'],keywords:'showcase escaparate producto servicio marca club imagen guardar compartir tienda web contacto',steps:['Explora fichas publicadas o abre el espacio de tu Club/Marca autorizado.','Crea una ficha con imagen, descripción y CTA cuando puedas gestionarlo.','Publica, comparte o guarda los elementos de interés.'],rules:['Showcase no es ecommerce: no hay carrito, checkout, pago, pedido, stock ni logística.','Los comentarios y corazones pertenecen a Social, no a Showcase.']},
  {id:'material',group:'Recursos del club',icon:'package',title:'Material',summary:'Gestiona el catálogo/material interno y las solicitudes relacionadas.',route:'material',roles:['direccion','coordinacion','secretaria','economia','familia','alumno'],keywords:'material equipamiento solicitud catálogo tienda interna',steps:['Consulta los materiales disponibles.','Gestiona artículos o solicitudes según tu rol.','Revisa el estado de cada solicitud.'],rules:['La gestión de material del club es independiente del Showcase público.']},
  {id:'documents',group:'Recursos del club',icon:'folder',title:'Archivo documental',summary:'Guarda y consulta documentos internos autorizados del club.',route:'documents',roles:['direccion','coordinacion','secretaria'],keywords:'documentos archivo fichero secretaria carpeta',steps:['Abre Archivo documental.','Sube o localiza el archivo correspondiente.','Comprueba que solo tenga acceso quien realmente lo necesita.'],rules:['El acceso documental está restringido a roles administrativos autorizados.']},
  {id:'archive',group:'Recursos del club',icon:'archive',title:'Archivo y papelera',summary:'Consulta elementos antiguos, archivados o candidatos a limpieza.',route:'archive',roles:['direccion','coordinacion','secretaria'],keywords:'archivo papelera borrar antiguos eventos notas cobros limpieza',steps:['Entra en Archivo y papelera.','Filtra por tipo y antigüedad.','Archiva, restaura o limpia solo cuando la acción sea segura.'],rules:['Los registros económicos/legales no deben borrarse si existe obligación de conservación.']},
  {id:'notifications',group:'Cuenta y sistema',icon:'bell',title:'Centro de notificaciones',summary:'Gestiona avisos informativos y acciones pendientes sin perder tareas importantes.',route:'notifications',roles:['todos'],keywords:'notificaciones contador leído marcar todo acción pendiente push',steps:['Abre Notificaciones y revisa los grupos de avisos.','Marca como leídos los informativos que ya hayas revisado.','Abre individualmente los avisos que requieren acción.'],rules:['“Marcar todo como leído” no debe ocultar notificaciones que requieren una acción real.','Las notificaciones push dependen también del permiso del dispositivo.']},
  {id:'settings',group:'Cuenta y sistema',icon:'settings',title:'Configuración, branding y temas',summary:'Datos del club, logo, portada y cuatro temas premium con acentos de neón sutil.',route:'settings',roles:['direccion','coordinacion','secretaria','economia','comunicacion'],keywords:'configuración branding logo portada tema color neon combat dark blue gold dojo',steps:['Abre Configuración y revisa los datos del club.','Selecciona el tema premium y comprueba la vista previa.','Publica la personalización para aplicarla al portal y perfil público.'],rules:['Los cuatro temas son Combat Dark Neon, Electric Blue Pro, Gold Luxe y Dojo Heritage Glow.','El neón se usa como acento, no como fondo saturado.','El perfil público del club recibe también su theme_id.']},
  {id:'install',group:'Cuenta y sistema',icon:'download',title:'Instalación, PWA y cartel de descarga',summary:'Instala KOMBAX y utiliza el cartel genérico del club con QR y código de invitación.',route:'install',roles:['todos'],keywords:'instalar pwa android cartel qr código descarga app club',steps:['Abre Instalar app.','Instala la PWA desde el navegador compatible o utiliza el canal Android del club.','Gestor/Coordinación/Secretaría pueden abrir el cartel genérico y completar QR/código cuando proceda.'],rules:['El cartel es genérico para cualquier club y no contiene nombres fijos de un tenant.','El QR debe resolver el club; el código corto valida el canal de alta.']},
  {id:'privacy',group:'Cuenta y sistema',icon:'shieldCheck',title:'Privacidad, condiciones y eliminación',summary:'Consulta textos legales, consentimientos y solicita eliminación de cuenta.',route:'help',roles:['todos'],keywords:'privacidad condiciones derechos imagen consentimiento eliminar cuenta normas legales',steps:['Baja hasta Condiciones y privacidad en esta misma pantalla.','Lee la versión vigente antes de aceptar o retirar un consentimiento.','Usa el centro de eliminación si necesitas iniciar el cierre de tu cuenta.'],rules:['Autorización de imagen y normas de comunidad son consentimientos diferenciados.','Eliminar cuenta no equivale a borrar trazabilidad económica/legal que deba conservarse.']}
];

const MEMBER_MANUAL=[
  {id:'member-start',group:'Lo esencial',icon:'home',title:'Mi inicio',summary:'Tu resumen personal: próximas clases, avisos y accesos principales.',route:'dashboard',roles:['alumno'],keywords:'inicio alumno miembro resumen clases avisos panel',steps:['Entra en Inicio al abrir KOMBAX.','Revisa tus próximas clases, avisos y situación general.','Usa los accesos directos para ir a la función que necesites.'],rules:['Solo ves información relacionada con tu cuenta y tu club.','Las funciones administrativas del club no forman parte del perfil Miembro.']},
  {id:'member-schedule',group:'Entrenamiento',icon:'calendar',title:'Horarios, sesiones y check-in',summary:'Consulta tus horarios y próximas sesiones; confirma asistencia cuando esté habilitado.',route:'groups',roles:['alumno'],keywords:'horario clase sesión reservar asistencia checkin entrenamiento',steps:['Abre Horarios para consultar tus grupos y clases.','Revisa la próxima sesión y, si está disponible, confirma o cancela tu asistencia.','El día de la clase utiliza Check-in cuando el club lo tenga habilitado.'],rules:['Solo aparecen grupos y sesiones vinculados a tu ficha.','Una reserva o check-in no modifica el horario creado por el club.']},
  {id:'member-finance',group:'Mi cuenta',icon:'wallet',title:'Mis cuotas, pagos y recibos',summary:'Consulta tus mensualidades, estado de pago y justificantes disponibles.',route:'finance',roles:['alumno'],keywords:'cuota pago recibo mensualidad deuda justificante finanzas',steps:['Entra en Cuotas.','Comprueba el periodo y el estado de cada mensualidad.','Abre el recibo o justificante cuando exista un cobro registrado.'],rules:['Solo puedes consultar información económica asociada a tu propia ficha.','Un recibo aparece cuando existe un cobro real registrado por el club.']},
  {id:'member-comms',group:'Mi club',icon:'megaphone',title:'Comunicaciones del club',summary:'Lee avisos e información oficial que el club dirige a sus miembros.',route:'communications',roles:['alumno'],keywords:'comunicación aviso noticia anuncio club información',steps:['Abre Comunicaciones.','Revisa los avisos nuevos y su fecha.','Consulta el contenido completo cuando necesites más detalle.'],rules:['Las comunicaciones oficiales son distintas de las publicaciones sociales.','La visibilidad depende de la audiencia definida por el club.']},
  {id:'member-events',group:'Mi club',icon:'calendar',title:'Eventos y actividades',summary:'Consulta eventos, actividades y competiciones publicadas para tu entorno.',route:'events',roles:['alumno'],keywords:'evento actividad competición fecha participación club',steps:['Abre Eventos.','Consulta fecha, descripción y detalles disponibles.','Sigue las indicaciones del club cuando el evento requiera una acción o participación.'],rules:['Un evento no sustituye al horario habitual de clases.','Las acciones disponibles dependen de cómo el club haya configurado el evento.']},
  {id:'member-material',group:'Mi club',icon:'package',title:'Material y solicitudes',summary:'Consulta material disponible y gestiona tus solicitudes al club.',route:'material',roles:['alumno'],keywords:'material equipamiento guantes solicitud pedido catálogo club',steps:['Abre Material.','Consulta los artículos disponibles y sus variantes cuando existan.','Envía una solicitud y revisa posteriormente su estado.'],rules:['Material es un servicio interno del club.','KOMBAX Showcase es un escaparate público diferente y no gestiona pedidos del club.']},
  {id:'member-community',group:'Comunidad',icon:'dojo',title:'Comunidad del Club',summary:'Participa en el espacio interno de publicaciones de tu propio club.',route:'community',roles:['alumno'],keywords:'comunidad club publicación foto video interna comentar contenido',steps:['Lee y acepta las Normas de Comunidad del Club antes de publicar.','Consulta el feed interno y crea contenido cuando tu cuenta lo permita.','Revisa tus publicaciones y la actividad disponible.'],rules:['La Comunidad del Club es interna y diferente de KOMBAX Social.','Publicar requiere mantener vigentes las normas y límites de contenido aplicables.']},
  {id:'member-social',group:'Comunidad',icon:'network',title:'KOMBAX Social',summary:'Activa, si eres elegible, tu identidad social pública y participa en la comunidad global.',route:'social',roles:['alumno'],feature:'social',keywords:'kombax social perfil público like corazón comentario guardar identidad',steps:['Desde Mi perfil comprueba si puedes activar KOMBAX Social.','Acepta sus normas específicas y crea tu identidad pública voluntariamente.','En Social puedes publicar, reaccionar, comentar, guardar y abrir perfiles públicos.'],rules:['El acceso de miembros requiere la edad mínima verificada por el club y activación voluntaria.','Ser Miembro no te convierte automáticamente en Competidor verificado.','Tu expediente privado del club permanece separado de la identidad pública Social.']},
  {id:'member-showcase',group:'Comunidad',icon:'spotlight',title:'KOMBAX Showcase',summary:'Explora el escaparate público de clubes, marcas y contenidos destacados.',route:'showcase',roles:['alumno'],feature:'showcase',keywords:'showcase escaparate marca club producto servicio guardar compartir',steps:['Abre KOMBAX Showcase.','Explora fichas públicas de clubes, marcas y elementos destacados.','Guarda o comparte contenido cuando la ficha ofrezca esa acción.'],rules:['Showcase no es una tienda online: no procesa pagos, carrito ni pedidos.','Las funciones de gestión de Showcase pertenecen a perfiles autorizados, no al Miembro.']},
  {id:'member-notifications',group:'Mi cuenta',icon:'bell',title:'Mis notificaciones',summary:'Revisa avisos informativos y tareas que necesitan tu atención.',route:'notifications',roles:['alumno'],keywords:'notificaciones aviso leído acción pendiente push contador',steps:['Abre Notificaciones.','Marca como leídos los avisos informativos que ya hayas revisado.','Abre individualmente cualquier notificación que requiera una acción.'],rules:['“Marcar todo como leído” no elimina las acciones pendientes importantes.','Las notificaciones push dependen también de los permisos del dispositivo.']},
  {id:'member-requests',group:'Mi cuenta',icon:'userPlus',title:'Mis solicitudes deportivas',summary:'Consulta o envía solicitudes relacionadas con tu inscripción deportiva.',route:'requests',roles:['alumno'],keywords:'solicitud deportiva inscripción disciplina grupo tarifa alta',steps:['Abre Solicitudes.','Revisa tus relaciones deportivas activas y solicitudes anteriores.','Envía una nueva solicitud de disciplina/grupo cuando necesites un cambio o alta.'],rules:['La solicitud queda pendiente hasta que el club la revise.','Enviar una solicitud no modifica por sí solo tu inscripción activa.']},
  {id:'member-profile',group:'Mi cuenta',icon:'user',title:'Mi perfil KOMBAX',summary:'Gestiona tu única identidad pública: banner, avatar, presentación, información deportiva, álbum y actividad Social.',route:'profile',roles:['alumno'],keywords:'perfil kombax banner avatar bio evolución deportiva álbum social identidad alumno',steps:['Abre Mi perfil.','Si KOMBAX Social aún no está activo, completa la activación voluntaria cuando seas elegible.','Edita desde la misma ficha tu banner, avatar, presentación e información deportiva pública.','Gestiona tu álbum y comprueba la parte privada del club separada debajo de tu ficha pública.'],rules:['Mi perfil y tu perfil KOMBAX Social son la misma identidad pública; no existe un segundo perfil deportivo visible.','La foto privada de acceso, documentos, cuotas, asistencia y expediente del club permanecen en una capa privada separada.','Ser Miembro no equivale a Competidor verificado ni concede una insignia KOMBAX.']},
  {id:'member-install',group:'Lo esencial',icon:'download',title:'Instalar KOMBAX',summary:'Instala la aplicación para acceder más rápido desde tu móvil o dispositivo.',route:'install',roles:['alumno'],keywords:'instalar app pwa android móvil acceso directo',steps:['Abre Instalar app.','Sigue la opción disponible para tu dispositivo o navegador.','Una vez instalada, entra con la misma cuenta de tu club.'],rules:['La instalación no crea una cuenta nueva ni cambia tus permisos.','El acceso sigue dependiendo de tu cuenta y del club seleccionado.']}
];

function manualDefinition(){
  const isMember=state.session?.rol==='alumno';
  const flags=platformFeatures();
  const items=(isMember?MEMBER_MANUAL:CLUB_MANUAL).filter(item=>!item.feature||flags[item.feature]===true);
  if(isMember)return {kind:'member',items,eyebrow:'KOMBAX · PERFIL MIEMBRO',heroTitle:'Tu guía KOMBAX',description:'Una guía breve para usar tu cuenta de alumno: entrenamientos, cuotas, comunicaciones, comunidad, perfil y servicios disponibles.',headerTitle:'Manual interactivo del miembro',headerSubtitle:'Solo las funciones que puedes utilizar como alumno del club',detailSubtitle:'Manual interactivo del perfil Miembro',searchPlaceholder:'Buscar: horario, cuota, recibo, evento, foto…',emptyHint:'Prueba otra palabra: “horario”, “cuota”, “evento”, “perfil”, “material” o “notificación”.'};
  return {kind:'club',items,eyebrow:'KOMBAX · PORTAL DE CLUB',heroTitle:'Manual interactivo',description:'Guía operativa completa y genérica para clubes. Busca una tarea, abre una función y sigue sus pasos sin salir de la aplicación.',headerTitle:'Manual interactivo del club',headerSubtitle:'Toda la operatividad del portal KOMBAX en una sola capa',detailSubtitle:'Manual interactivo del portal de club',searchPlaceholder:'Buscar: recibo, QR, comentario, monitor, sesión…',emptyHint:'Prueba otra palabra: “cuota”, “grupo”, “foto”, “código”, “perfil” o “notificación”.'};
}

function legalBody(text){return `<div class="legal-document">${esc(text||'').replace(/\n\n/g,'</p><p>').replace(/^/,'<p>').replace(/$/,'</p>').replace(/\n/g,'<br>')}</div>`}
function canOpen(item){if(item.roles.includes('todos'))return true;const roles=roleSet();return item.roles.some(r=>roles.has(r));}
function roleText(item){if(item.roles.includes('todos'))return 'Disponible según el contexto y permisos de la cuenta';return rolesLabel(item.roles)}
function manualCard(item){const allowed=canOpen(item);return `<article class="kx-manual-topic" data-manual-topic="${esc(item.id)}" data-manual-search="${esc(`${item.group} ${item.title} ${item.summary} ${item.keywords} ${item.steps.join(' ')} ${item.rules.join(' ')}`.toLowerCase())}"><button type="button" class="kx-manual-topic-head" data-manual-open="${esc(item.id)}"><span class="kx-manual-topic-icon">${icon(item.icon,{size:22})}</span><span><small>${esc(item.group)}</small><strong>${esc(item.title)}</strong><em>${esc(item.summary)}</em></span><span class="kx-manual-chevron">${icon('chevronRight',{size:18})}</span></button><div class="kx-manual-topic-actions"><span class="kx-manual-role ${allowed?'is-allowed':'is-limited'}">${allowed?'Acceso desde tu rol':'Consulta informativa'} · ${esc(roleText(item))}</span><button type="button" class="btn btn-ghost btn-sm" data-manual-open="${esc(item.id)}">Cómo funciona</button>${item.route&&item.route!=='help'?`<button type="button" class="btn btn-primary btn-sm" data-manual-route="${esc(item.route)}" ${allowed?'':'disabled'}>Ir a la función</button>`:''}</div></article>`}
function manualDetail(item){const allowed=canOpen(item);return `<div class="kx-manual-detail"><div class="kx-manual-detail-intro"><span class="kx-manual-detail-icon">${icon(item.icon,{size:28})}</span><div><strong>${esc(item.title)}</strong><p>${esc(item.summary)}</p></div></div><div class="kx-manual-detail-grid"><section><h3>${icon('checkCircle',{size:17})} Paso a paso</h3><ol>${item.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section><section><h3>${icon('shieldCheck',{size:17})} Reglas importantes</h3><ul>${item.rules.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section></div><div class="kx-manual-access"><strong>Quién puede usarlo</strong><span>${esc(roleText(item))}</span></div>${item.route&&item.route!=='help'?`<div class="row-actions"><button type="button" class="btn btn-primary" data-manual-modal-route="${esc(item.route)}" ${allowed?'':'disabled'}>${icon('arrowUpRight',{size:16})} ${allowed?'Abrir esta función':'No disponible con tu rol actual'}</button></div>`:''}</div>`}
function openManualTopic(item,detailSubtitle='Manual interactivo'){const modal=openDetail({title:item.title,subtitle:`${item.group} · ${detailSubtitle}`,body:manualDetail(item),width:'860px'});modal.wrap.querySelector('[data-manual-modal-route]')?.addEventListener('click',e=>{const route=e.currentTarget.dataset.manualModalRoute;modal.close?.();location.hash=`#${route}`;});}
function bindInteractiveManual(items,detailSubtitle){
  const search=document.getElementById('manual-search');const group=document.getElementById('manual-group-filter');const topics=[...document.querySelectorAll('[data-manual-topic]')];const emptyState=document.getElementById('manual-search-empty');
  const apply=()=>{const q=String(search?.value||'').trim().toLowerCase();const g=group?.value||'';let visible=0;topics.forEach(el=>{const item=items.find(x=>x.id===el.dataset.manualTopic);const matchQ=!q||el.dataset.manualSearch.includes(q);const matchG=!g||item?.group===g;const on=matchQ&&matchG;el.hidden=!on;if(on)visible++;});if(emptyState)emptyState.hidden=visible>0;};
  search?.addEventListener('input',apply);group?.addEventListener('change',apply);document.getElementById('manual-clear-search')?.addEventListener('click',()=>{if(search)search.value='';if(group)group.value='';apply();search?.focus();});
  document.querySelectorAll('[data-manual-open]').forEach(b=>b.addEventListener('click',()=>{const item=items.find(x=>x.id===b.dataset.manualOpen);if(item)openManualTopic(item,detailSubtitle);}));
  document.querySelectorAll('[data-manual-route]').forEach(b=>b.addEventListener('click',()=>{if(!b.disabled)location.hash=`#${b.dataset.manualRoute}`;}));
  document.querySelectorAll('[data-member-quick-route]').forEach(b=>b.addEventListener('click',()=>{if(!b.disabled)location.hash=`#${b.dataset.memberQuickRoute}`;}));
}


export async function openPrivacyConditions(){
  try{
    const [docs,accepts]=await Promise.all([repos.legal.docs(),repos.legal.acceptances().catch(()=>[])]);
    const accepted=new Map((accepts||[]).filter(a=>a.aceptado&&!a.revocado_en).map(a=>[`${a.tipo}:${a.version}`,a]));
    const rows=(docs||[]).map(d=>`<article class="kx-privacy-doc-row"><div><span class="page-kicker">${esc(titleFor(d.tipo))}</span><strong>Versión ${esc(d.version)}</strong><small>${accepted.has(`${d.tipo}:${d.version}`)?'Aceptado en tu cuenta':d.tipo==='derechos_imagen'?'Consentimiento opcional':'Texto vigente para consulta'}</small></div><button type="button" class="btn btn-ghost btn-sm" data-privacy-doc="${esc(d.id)}">Leer</button></article>`).join('');
    const modal=openDetail({title:'Privacidad y condiciones',subtitle:'Textos legales y consentimientos vigentes de tu club',body:`<div class="kx-privacy-center"><div class="alert"><strong>Separación de privacidad</strong><span>Tu perfil KOMBAX es tu única ficha pública. Tu expediente y actividad administrativa del club permanecen en una capa privada separada y nunca se publican automáticamente.</span></div><div class="kx-privacy-doc-list">${rows||'<div class="empty"><strong>Sin textos legales vigentes</strong></div>'}</div><p class="muted">La autorización de imagen es independiente de las funciones esenciales. Las Normas de Comunidad del Club y KOMBAX Social se gestionan como consentimientos diferenciados.</p></div>`,actions:'<button type="button" class="btn btn-ghost" id="privacy-delete-center">Privacidad y eliminación de cuenta</button>',width:'860px',className:'kx-privacy-modal'});
    modal.wrap.querySelectorAll('[data-privacy-doc]').forEach(b=>b.addEventListener('click',()=>{const d=(docs||[]).find(x=>String(x.id)===String(b.dataset.privacyDoc));if(!d)return;openDetail({title:titleFor(d.tipo),subtitle:`Versión ${d.version}`,body:legalBody(d.cuerpo),width:'900px'});}));
    modal.wrap.querySelector('#privacy-delete-center')?.addEventListener('click',openDeletionCenter);
  }catch(e){setError(e);}
}

async function openDeletionCenter(){
  try{
    const requests=await repos.accountDeletion.list().catch(()=>[]);
    const pending=(requests||[]).filter(x=>['requested','in_review','needs_information','confirmed'].includes(x.estado));
    const body=`<div class="kx-deletion-center"><div class="alert alert-warning"><strong>Eliminar cuenta no equivale a borrar trazabilidad legal</strong><span>KOMBAX separa la cuenta personal, el perfil público y el cierre del club. Los registros económicos o legalmente exigibles se conservan solo durante el periodo aplicable.</span></div><p>También existe el recurso web público <a href="./delete-account.html" target="_blank" rel="noopener noreferrer">Solicitud de eliminación de KOMBAX</a>.</p>${pending.length?`<div class="kx-deletion-list">${pending.map(r=>`<article><strong>${esc(r.alcance==='account'?'Cuenta personal':r.alcance==='club'?'Club':'Perfil KOMBAX')}</strong><span>${esc(r.estado)}</span><small>${esc(new Date(r.solicitado_en).toLocaleString('es-ES'))}</small>${['requested','needs_information'].includes(r.estado)?`<button class="btn btn-ghost btn-sm" data-delete-cancel="${esc(r.id)}">Cancelar solicitud</button>`:''}</article>`).join('')}</div>`:'<p class="muted">No hay solicitudes abiertas.</p>'}</div>`;
    const modal=openDetail({title:'Privacidad y eliminación',subtitle:'Solicitud trazable de cuenta, perfil o club',body,actions:'<button class="btn btn-danger" id="request-account-deletion">Solicitar eliminación de mi cuenta</button>',width:'760px'});
    modal.wrap.querySelector('#request-account-deletion')?.addEventListener('click',()=>openForm({title:'Solicitar eliminación de cuenta',subtitle:'La solicitud inicia el proceso de cierre. No ejecuta un borrado indiscriminado de facturación u otros registros sujetos a retención.',fields:[{name:'motivo',label:'Motivo (opcional)',type:'textarea',rows:4,full:true,maxLength:1200}],submitText:'Enviar solicitud',onSubmit:async v=>{await repos.accountDeletion.request({alcance:'account',motivo:v.motivo||''});toast('Solicitud de eliminación registrada');setTimeout(openDeletionCenter,180);}}));
    modal.wrap.querySelectorAll('[data-delete-cancel]').forEach(b=>b.addEventListener('click',()=>confirmDialog('Cancelar solicitud','La solicitud abierta dejará de tramitarse.',async()=>{await repos.accountDeletion.cancel(b.dataset.deleteCancel);toast('Solicitud cancelada');setTimeout(openDeletionCenter,180);},{confirmText:'Cancelar solicitud'})));
  }catch(e){setError(e);}
}

export async function renderHelpLegal(){
  setMainHtml('<div class="loading-card">Cargando manual interactivo…</div>');
  try{
    const [docs,accepts]=await Promise.all([repos.legal.docs(),repos.legal.acceptances().catch(()=>[])]);const accepted=new Map(accepts.filter(a=>a.aceptado&&!a.revocado_en).map(a=>[`${a.tipo}:${a.version}`,a]));
    const manualDef=manualDefinition();const groups=[...new Set(manualDef.items.map(x=>x.group))];const staff=team();
    const poster=manualDef.kind==='club'&&diffusion()?`<aside class="kx-manual-poster"><div class="kx-manual-poster-copy"><span>RECURSO DEL CLUB</span><strong>Cartel de descarga KOMBAX</strong><p>Cartel genérico para recepción, gimnasio o evento. Incluye espacio para QR y código corto de invitación.</p><a class="btn btn-ghost" href="./assets/docs/Cartel_Descarga_KOMBAX_Club.png" target="_blank" rel="noopener noreferrer">${icon('qr',{size:16})} Abrir cartel</a></div><img src="./assets/docs/Cartel_Descarga_KOMBAX_Club.png" alt="Cartel genérico de descarga KOMBAX para clubes" loading="lazy"></aside>`:'';
    const memberQuick=manualDef.kind==='member'?`<div class="kx-member-manual-quick"><div><span class="eyebrow">ACCESOS RÁPIDOS</span><strong>Lo que más usarás</strong><small>Tu manual no incluye administración del club.</small></div><div class="row-actions"><button type="button" class="btn btn-primary btn-sm" data-member-quick-route="groups">${icon('calendar',{size:15})} Horarios</button><button type="button" class="btn btn-ghost btn-sm" data-member-quick-route="finance">${icon('wallet',{size:15})} Cuotas</button><button type="button" class="btn btn-ghost btn-sm" data-member-quick-route="profile">${icon('user',{size:15})} Mi perfil</button><button type="button" class="btn btn-ghost btn-sm" data-member-quick-route="notifications">${icon('bell',{size:15})} Notificaciones</button></div></div>`:'';
    const manual=`<section class="kx-manual-shell ${manualDef.kind==='member'?'is-member':''}"><div class="kx-manual-hero"><div><span class="eyebrow">${esc(manualDef.eyebrow)}</span><h2>${esc(manualDef.heroTitle)}</h2><p>${esc(manualDef.description)}</p><div class="kx-manual-stats"><span><strong>${manualDef.items.length}</strong> funciones</span><span><strong>${groups.length}</strong> bloques</span><span><strong>${esc(rolesLabel(state.session?.roles||[state.session?.rol]))}</strong> tu acceso actual</span></div></div>${poster}</div>${memberQuick}<div class="kx-manual-tools"><label class="kx-manual-search">${icon('search',{size:18})}<input id="manual-search" type="search" placeholder="${esc(manualDef.searchPlaceholder)}" autocomplete="off"></label><select id="manual-group-filter" aria-label="Filtrar el manual por bloque"><option value="">Todos los bloques</option>${groups.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('')}</select><button class="btn btn-ghost" id="manual-clear-search">Limpiar</button></div><div class="kx-manual-grid">${manualDef.items.map(manualCard).join('')}</div><div id="manual-search-empty" class="empty-state" hidden><strong>No encuentro esa función</strong><span>${esc(manualDef.emptyHint)}</span></div></section>`;
    const legal=docs.map(d=>quickRow(icon(d.tipo==='privacidad'?'shieldCheck':d.tipo==='derechos_imagen'?'image':'fileText'),titleFor(d.tipo),`Versión ${d.version}`,`${accepted.has(`${d.tipo}:${d.version}`)?badge('Aceptado','ok'):badge(d.tipo==='derechos_imagen'?'Opcional':'Consultar','neutral')} <button class="btn btn-ghost btn-sm legal-open" data-id="${esc(d.id)}">Leer</button>`)).join('');
    setMainHtml(`${pageHeader(manualDef.headerTitle,manualDef.headerSubtitle,'','Ayuda')}${manual}${card('Condiciones y privacidad',legal||empty('Sin textos legales vigentes'))}${card('Privacidad y consentimiento',`<p class="muted">La autorización de imagen es independiente de las funciones esenciales de la aplicación. Las Normas de Comunidad del Club se aceptan de forma explícita antes de publicar contenido y pueden retirarse aquí para impedir nuevas publicaciones.</p><div class="row-actions">${docs.find(d=>d.tipo==='comunidad')?`<button class="btn btn-ghost" id="community-consent-toggle">${accepted.has(`comunidad:${docs.find(d=>d.tipo==='comunidad').version}`)?'Retirar aceptación de Comunidad del Club':'Aceptar Normas de Comunidad del Club'}</button>`:''}${docs.find(d=>d.tipo==='derechos_imagen')?`<button class="btn btn-ghost" id="image-consent-toggle">${accepted.has(`derechos_imagen:${docs.find(d=>d.tipo==='derechos_imagen').version}`)?'Retirar autorización de imagen':'Autorizar uso de imagen dentro del club'}</button>`:''}</div>`)}${card('Cuenta y eliminación',`<p class="muted">Puedes iniciar desde la app una solicitud de eliminación de tu cuenta. KOMBAX mantiene separado este proceso del cierre de un perfil público o de un club y evita borrar trazabilidad económica que deba conservarse.</p><div class="row-actions"><button class="btn btn-ghost" id="open-deletion-center">Gestionar eliminación de cuenta</button><a class="btn btn-ghost" href="./delete-account.html" target="_blank">Recurso web público</a></div>`)}`);
    bindInteractiveManual(manualDef.items,manualDef.detailSubtitle);
    document.getElementById('open-deletion-center')?.addEventListener('click',openDeletionCenter);
    document.querySelectorAll('.legal-open').forEach(b=>b.addEventListener('click',()=>{const d=docs.find(x=>x.id===b.dataset.id);openDetail({title:titleFor(d.tipo),subtitle:`Versión ${d.version}`,body:legalBody(d.cuerpo),width:'900px'});}));
    const community=docs.find(d=>d.tipo==='comunidad');document.getElementById('community-consent-toggle')?.addEventListener('click',async()=>{try{const on=!accepted.has(`comunidad:${community.version}`);await repos.legal.accept('comunidad',community.version,on);toast(on?'Normas de Comunidad del Club aceptadas':'Aceptación de Comunidad del Club retirada');await renderHelpLegal();}catch(e){setError(e)}});
    const image=docs.find(d=>d.tipo==='derechos_imagen');document.getElementById('image-consent-toggle')?.addEventListener('click',async()=>{try{const on=!accepted.has(`derechos_imagen:${image.version}`);await repos.legal.accept('derechos_imagen',image.version,on);toast(on?'Autorización registrada':'Autorización retirada');await renderHelpLegal();}catch(e){setError(e)}});
  }catch(e){setError(e);setMainHtml(`${pageHeader('Manual interactivo')} ${empty('No se pudo cargar la ayuda',e.message)}`)}
}
