-- Solo lectura. Todos los controles deben devolver PASS después de 042.
select 'showcase_tables' control,case when to_regclass('public.kombax_showcase_marcas') is not null and to_regclass('public.kombax_showcase_elementos') is not null and to_regclass('public.kombax_showcase_categorias') is not null and to_regclass('public.kombax_showcase_gestores') is not null then 'PASS' else 'FAIL' end resultado;
select 'showcase_rpc' control,case when to_regprocedure('public.app_kombax_showcase_list_v042(text,text,timestamp with time zone,uuid,integer)') is not null and to_regprocedure('public.app_kombax_showcase_mutate_v042(text,jsonb,uuid)') is not null then 'PASS' else 'FAIL' end resultado;
select 'no_direct_tables' control,case when not has_table_privilege('authenticated','public.kombax_showcase_marcas','SELECT') and not has_table_privilege('authenticated','public.kombax_showcase_elementos','SELECT') and not has_table_privilege('authenticated','public.kombax_showcase_gestores','SELECT') then 'PASS' else 'FAIL' end resultado;
select 'rls' control,case when not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname like 'kombax_showcase_%' and c.relkind='r' and not c.relrowsecurity) then 'PASS' else 'FAIL' end resultado;
select 'https_guards' control,case when pg_get_functiondef('public.app_kombax_showcase_url_v042(text)'::regprocedure) like '%https://%' then 'PASS' else 'FAIL' end resultado;
select 'page_limit' control,case when pg_get_functiondef('public.app_kombax_showcase_list_v042(text,text,timestamp with time zone,uuid,integer)'::regprocedure) like '%least(greatest(coalesce(p_limit, 24), 1), 24)%' then 'PASS' else 'FAIL' end resultado;
select 'no_commerce_domain' control,case when not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname like 'kombax_showcase_%' and c.relname ~ '(carrito|pedido|pago|envio|devolucion|stock|checkout)') then 'PASS' else 'FAIL' end resultado;
select 'categories' control,case when (select count(*) from public.kombax_showcase_categorias where activa)>=6 then 'PASS' else 'FAIL' end resultado;
