-- KOMBAX build 20030 · verify 057 · una fila, todos los controles juntos.
select
  to_regclass('public.club_ambitos_trabajo') is not null as scopes_ok,
  to_regclass('public.club_ambito_equipo') is not null as scope_team_ok,
  to_regclass('public.club_ambito_socios') is not null as scope_students_ok,
  to_regclass('public.club_ambito_grupos') is not null as scope_groups_ok,
  exists(select 1 from pg_indexes where schemaname='public' and tablename='club_ambito_socios' and indexname='uq_ambito_socio_principal_v057') as one_primary_scope_ok,
  to_regprocedure('public.monitor_puede_ver_socio_v057(uuid)') is not null as scoped_students_rpc_ok,
  to_regprocedure('public.monitor_asignado_a_grupo_v057(uuid)') is not null as scoped_groups_rpc_ok,
  to_regprocedure('public.app_kombax_monitor_puede_asistencia_v057(uuid)') is not null as attendance_permission_ok,
  to_regprocedure('public.app_kombax_monitor_puede_asistencia_registro_v057(uuid,uuid)') is not null as attendance_record_guard_ok,
  to_regprocedure('public.app_kombax_monitor_puede_seguimiento_v057(uuid)') is not null as tracking_permission_ok,
  to_regprocedure('public.app_kombax_mis_alumnos_v057(uuid)') is not null as safe_students_rpc_ok,
  to_regprocedure('public.app_kombax_mi_cartera_v057(uuid)') is not null as finance_portfolio_rpc_ok,
  to_regprocedure('public.app_kombax_mi_progreso_v057(uuid)') is not null as scoped_progress_rpc_ok,
  to_regprocedure('public.app_kombax_monitor_cobro_v057(uuid,numeric,date,text,text,text)') is not null as scoped_collection_rpc_ok,
  to_regprocedure('public.app_kombax_ambito_mutate_v057(text,jsonb,uuid)') is not null as management_rpc_ok,
  to_regprocedure('public.app_mutate_v160_pre_work_scopes_057(text,jsonb,uuid)') is not null as legacy_gateway_preserved_ok,
  pg_get_functiondef('public.puede_ver_socio(uuid)'::regprocedure) not ilike '%monitor_puede_ver_socio%' as admin_helper_no_monitor_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='socios' and policyname='socios_lectura' and coalesce(qual,'') not ilike '%monitor%') as raw_student_row_private_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='documentos_socios' and policyname='documentos_socios_lectura' and coalesce(qual,'') not ilike '%monitor%') as documents_private_ok,
  exists(select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='member_documents_read' and coalesce(qual,'') ilike '%puede_aportar_pago_socio%' and coalesce(qual,'') not ilike '%puede_ver_socio%') as document_storage_private_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='recibos_cuota' and policyname='recibos_cuota_lectura' and coalesce(qual,'') not ilike '%puede_ver_socio%') as receipts_private_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='reservas_sesion' and policyname='reservas_sesion_lectura' and coalesce(qual,'') ilike '%monitor_puede_ver_socio_v057%') as reservations_scoped_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='series_sesiones' and policyname='series_sesiones_lectura_rc10' and coalesce(qual,'') ilike '%monitor_asignado_a_grupo_v057%') as session_series_scoped_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='asistencias' and policyname='asistencia_gestion' and coalesce(qual,'') ilike '%asistencia_registro_v057%') as attendance_write_scoped_ok,
  exists(select 1 from pg_policies where schemaname='public' and tablename='seguimiento' and policyname='seguimiento_gestion' and coalesce(qual,'') ilike '%puede_seguimiento_v057%') as tracking_write_scoped_ok,
  pg_get_functiondef('public.app_mutate_v160(text,jsonb,uuid)'::regprocedure) ilike '%MONITOR_SCOPE_REQUIRED%' as session_gateway_scoped_ok;
