import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..'),read=p=>readFile(resolve(root,p),'utf8');
const assert=(ok,msg)=>{if(!ok)throw new Error(`FAIL RC12: ${msg}`);console.log(`OK RC12: ${msg}`)};
const [cfg,repos,community,finance,comms,sql,dispatch,reminders,css,gradle,main]=await Promise.all([
 read('web/config.js'),read('web/js/core/repositories.js'),read('web/js/modules/community.js'),read('web/js/modules/finance.js'),read('web/js/modules/comms-material.js'),read('supabase/migrations/023_scalability_finance_materials_v167.sql'),read('supabase/functions/notification-dispatch/index.ts'),read('supabase/functions/payment-reminders/index.ts'),read('web/css/app.css'),read('android/app/build.gradle'),read('android/app/src/main/java/com/urbanwarriors/app/MainActivity.java')]);
assert(cfg.includes("version: '2.0.0-rc.12'")&&cfg.includes('build: 20012'),'versionado integral RC12');
assert(repos.includes('offset=${Math.max')&&community.includes('PAGE_SIZE=20')&&community.includes('Cargar más publicaciones'),'Comunidad usa carga progresiva y paginación');
assert(community.includes('loading=\"lazy\"')&&community.includes('preload=\"none\"'),'feed multimedia usa lazy loading y evita precarga de vídeos');
assert(community.includes('automaticVideoCover')&&community.includes('Portada manual')&&repos.includes('portada_path'),'vídeos generan portada automática con sustitución manual');
assert(community.includes('compressImage')&&community.includes('1920')&&community.includes('duration>15.2'),'multimedia normalizada: imagen comprimida, vídeo 15 s y máximo 1080p');
assert(community.includes('vídeo máx. 50 MB')&&repos.includes('(isVideo?50:5)*1024*1024')&&repos.includes('El vídeo supera 50 MB.'),'límite de vídeo ampliado a 50 MB en interfaz y repositorio');
assert(sql.includes('publicaciones_comunidad_cursor_idx')&&sql.includes('club_id,creado_en desc,id desc'),'feed preparado para crecimiento multi-club');
assert(sql.includes("add column if not exists origen text not null default 'cuota'")&&sql.includes('referencia_id'),'cargos financieros distinguen cuotas/material');
assert(finance.includes('financeYear')&&finance.includes('Historial financiero')&&finance.includes('Tasa de cobro')&&finance.includes('Total pendiente'),'historial anual y vista accesible de alumno/familia');
assert(repos.includes('material.validar_entrega')&&repos.includes('material.registrar_entrega')&&comms.includes('Validar y cobrar')&&comms.includes('He cogido material'),'material admite autorregistro y validación de club');
assert(sql.includes("origen_registro in ('alumno','familia','club')")&&sql.includes("validacion_estado in ('pendiente','validado','rechazado')")&&sql.includes("'material',v_order.id"),'material validado crea cargo trazable');
assert(sql.includes('q.periodo <= date_trunc')&&sql.includes("'aviso_cobro','Pago pendiente en Urban Warriors'"),'avisos incluyen deudas antiguas y material');
assert(!dispatch.includes('allowedByPreference')&&!dispatch.includes("from('preferencias_notificacion')")&&!reminders.includes("from('preferencias_notificacion')"),'push no depende de preferencias individuales');
assert(!comms.includes('id=\"notif-preferences\"'),'usuario no recibe selector de categorías push');
assert(css.includes('finance-year-control')&&css.includes('community-more-wrap'),'estilos para nuevas interfaces');
assert(gradle.includes('versionCode 20012')&&gradle.includes("versionName '2.0.0-rc.12'")&&main.includes('UrbanWarriorsApp/2.0.0-rc.12'),'Android RC12 alineado');
assert(main.includes('POST_NOTIFICATIONS')&&css.includes('safe-area-inset-top')&&css.includes('safe-area-inset-bottom'),'capa Android conserva activación push y safe areas RC11');
console.log('RC12 BLOQUES INTEGRALES: PASS');
