-- Emergency rollback: re-opens only the superseded client grants closed by 088.
begin;
grant execute on function public.app_kombax_contactos_v065() to authenticated;
grant execute on function public.app_kombax_contact_mensajes_v065(uuid) to authenticated;
grant execute on function public.app_kombax_contact_mark_read_v065(uuid) to authenticated;
grant execute on function public.app_kombax_social_network_mutate_v065(text,jsonb,uuid) to authenticated;
grant execute on function public.app_kombax_album_v043(uuid) to authenticated;
grant execute on function public.app_kombax_identity_mutate_v051(text,jsonb,uuid) to authenticated;
grant execute on function public.app_kombax_platform_dashboard_v055() to authenticated;
grant execute on function public.app_kombax_platform_profiles_v055(text,integer) to authenticated;
grant execute on function public.app_kombax_showcase_list_v042(text,text,timestamptz,uuid,integer) to anon,authenticated;
grant execute on function public.app_kombax_showcase_mis_elementos_v042(uuid) to authenticated;
grant execute on function public.app_kombax_showcase_mis_espacios_v045(uuid) to authenticated;
grant execute on function public.app_kombax_showcase_mutate_v042(text,jsonb,uuid) to authenticated;
grant execute on function public.app_kombax_showcase_mutate_v048(text,jsonb,uuid) to authenticated;
grant execute on function public.app_kombax_showcase_mutate_v054(text,jsonb,uuid) to authenticated;
grant execute on function public.app_kombax_showcase_puede_gestionar_v042(uuid) to authenticated;
grant execute on function public.app_kombax_social_directorio_v041(text,integer) to authenticated;
grant execute on function public.app_kombax_social_directorio_v044(text,integer) to authenticated;
grant execute on function public.app_kombax_social_directorio_v052(text,integer) to authenticated;
grant execute on function public.app_kombax_social_estado_v041(uuid) to authenticated;
grant execute on function public.app_kombax_social_estado_v049(uuid) to authenticated;
grant execute on function public.app_kombax_social_estado_v051(uuid) to authenticated;
grant execute on function public.app_kombax_social_mis_perfiles_v041() to authenticated;
grant execute on function public.app_kombax_social_mis_perfiles_v044() to authenticated;
grant execute on function public.app_kombax_social_tipo_v045(uuid) to authenticated;
commit;
