-- KOMBAX 20.057 · relational foreign-key coverage (102)
-- Covers business/ownership/cascade relations used by the application. Pure actor/audit FKs are intentionally excluded.

create index if not exists idx_material_pedidos_variante_fk_v102 on public.material_pedidos(variante_id) where variante_id is not null;
create index if not exists idx_material_catalogo_disciplina_fk_v102 on public.material_catalogo(club_id, disciplina_id) where disciplina_id is not null;
create index if not exists idx_socios_tarifa_fk_v102 on public.socios(club_id, tarifa_id) where tarifa_id is not null;
create index if not exists idx_eventos_comp_disciplina_fk_v102 on public.eventos_competicion(disciplina_id) where disciplina_id is not null;
create index if not exists idx_material_entregas_variante_fk_v102 on public.material_entregas(variante_id) where variante_id is not null;
create index if not exists idx_comunicaciones_disciplina_fk_v102 on public.comunicaciones(club_id, disciplina_id) where disciplina_id is not null;
create index if not exists idx_comunicaciones_grupo_fk_v102 on public.comunicaciones(club_id, grupo_id) where grupo_id is not null;
create index if not exists idx_evento_combates_part_a_fk_v102 on public.evento_combates(club_id, participante_a_id) where participante_a_id is not null;
create index if not exists idx_evento_combates_part_b_fk_v102 on public.evento_combates(club_id, participante_b_id) where participante_b_id is not null;
create index if not exists idx_evento_combates_ganador_fk_v102 on public.evento_combates(ganador_participante_id) where ganador_participante_id is not null;
create index if not exists idx_hist_avisos_notificacion_fk_v102 on public.historial_avisos_cuota(notificacion_id) where notificacion_id is not null;
create index if not exists idx_hist_avisos_perfil_fk_v102 on public.historial_avisos_cuota(perfil_id) where perfil_id is not null;
create index if not exists idx_team_permissions_perfil_fk_v102 on public.kombax_club_team_permissions(perfil_id) where perfil_id is not null;
create index if not exists idx_notif_revisiones_perfil_fk_v102 on public.notificaciones_revisiones(perfil_id) where perfil_id is not null;
create index if not exists idx_tarifas_disciplina_fk_v102 on public.tarifas(club_id, disciplina_id) where disciplina_id is not null;
create index if not exists idx_aceptaciones_legales_socio_fk_v102 on public.aceptaciones_legales(club_id, socio_id) where socio_id is not null;
create index if not exists idx_aceptaciones_legales_texto_fk_v102 on public.aceptaciones_legales(club_id, texto_legal_id) where texto_legal_id is not null;
create index if not exists idx_aceptaciones_legales_perfil_fk_v102 on public.aceptaciones_legales(perfil_id) where perfil_id is not null;
create index if not exists idx_entitlements_capacidad_fk_v102 on public.kombax_entitlements(capacidad_clave);
create index if not exists idx_verificacion_docs_perfil_fk_v102 on public.kombax_verificacion_documentos(perfil_id) where perfil_id is not null;
create index if not exists idx_verificacion_docs_solicitud_fk_v102 on public.kombax_verificacion_documentos(solicitud_id) where solicitud_id is not null;
create index if not exists idx_pagos_socio_fk_v102 on public.pagos(club_id, socio_id) where socio_id is not null;
create index if not exists idx_seguimiento_socio_fk_v102 on public.seguimiento(club_id, socio_id) where socio_id is not null;
create index if not exists idx_ambito_socios_ambito_fk_v102 on public.club_ambito_socios(club_id, ambito_id);
create index if not exists idx_graduaciones_disciplina_fk_v102 on public.graduaciones(club_id, disciplina_id) where disciplina_id is not null;
create index if not exists idx_graduaciones_club_fk_v102 on public.graduaciones(club_id);
create index if not exists idx_graduaciones_grado_ant_fk_v102 on public.graduaciones(club_id, grado_anterior_id) where grado_anterior_id is not null;
create index if not exists idx_graduaciones_grado_fk_v102 on public.graduaciones(club_id, grado_id) where grado_id is not null;
create index if not exists idx_graduaciones_socio_fk_v102 on public.graduaciones(club_id, socio_id) where socio_id is not null;
create index if not exists idx_hist_tarifas_club_fk_v102 on public.historial_tarifas(club_id);
create index if not exists idx_hist_tarifas_tarifa_fk_v102 on public.historial_tarifas(club_id, tarifa_id) where tarifa_id is not null;
create index if not exists idx_codigo_intentos_anon_club_fk_v102 on public.kombax_codigo_intentos_anon_v086(club_id);
create index if not exists idx_plan_capacidades_capacidad_fk_v102 on public.kombax_plan_capacidades(capacidad_clave);
create index if not exists idx_showcase_gestores_perfil_fk_v102 on public.kombax_showcase_gestores(perfil_id) where perfil_id is not null;
create index if not exists idx_solic_eliminacion_club_fk_v102 on public.kombax_solicitudes_eliminacion(club_id) where club_id is not null;
create index if not exists idx_bloqueos_comunidad_objetivo_fk_v102 on public.bloqueos_comunidad(bloqueado_perfil_id) where bloqueado_perfil_id is not null;
create index if not exists idx_ambito_equipo_ambito_fk_v102 on public.club_ambito_equipo(club_id, ambito_id);
create index if not exists idx_ambito_equipo_perfil_fk_v102 on public.club_ambito_equipo(perfil_id);
create index if not exists idx_aceptaciones_globales_perfil_fk_v102 on public.kombax_aceptaciones_globales(perfil_id) where perfil_id is not null;
create index if not exists idx_social_likes_perfil_fk_v102 on public.kombax_social_likes(perfil_id);
create index if not exists idx_solic_equipo_perfil_fk_v102 on public.kombax_solicitudes_equipo_club(perfil_id);
create index if not exists idx_mod_acceso_social_identidad_fk_v102 on public.moderacion_accesos_sociales(identidad_social_id) where identidad_social_id is not null;
create index if not exists idx_mod_acceso_social_perfil_fk_v102 on public.moderacion_accesos_sociales(perfil_id) where perfil_id is not null;
create index if not exists idx_preferencias_notif_perfil_fk_v102 on public.preferencias_notificacion(perfil_id);
create index if not exists idx_ambito_grupos_ambito_fk_v102 on public.club_ambito_grupos(club_id, ambito_id);
create index if not exists idx_consentimientos_club_fk_v102 on public.consentimientos(club_id);
create index if not exists idx_consentimientos_socio_fk_v102 on public.consentimientos(club_id, socio_id) where socio_id is not null;
create index if not exists idx_consentimientos_texto_fk_v102 on public.consentimientos(club_id, texto_legal_id);
create index if not exists idx_consentimientos_tutor_fk_v102 on public.consentimientos(tutor_perfil_id) where tutor_perfil_id is not null;
create index if not exists idx_codigo_intentos_club_fk_v102 on public.kombax_codigo_intentos_v086(club_id);
create index if not exists idx_codigos_acceso_audit_club_fk_v102 on public.kombax_codigos_acceso_audit(club_id);
create index if not exists idx_showcase_guardados_elemento_fk_v102 on public.kombax_showcase_guardados(elemento_id);
create index if not exists idx_socio_descuentos_descuento_fk_v102 on public.socio_descuentos(club_id, descuento_id);
create index if not exists idx_recibos_pago_fk_v102 on public.recibos_cuota(pago_id) where pago_id is not null;
create index if not exists idx_grupos_monitor_principal_fk_v102 on public.grupos(monitor_principal_id) where monitor_principal_id is not null;
create index if not exists idx_identidades_sociales_club_fk_v102 on public.identidades_sociales(club_origen_id) where club_origen_id is not null;
create index if not exists idx_identidades_sociales_socio_fk_v102 on public.identidades_sociales(socio_origen_id) where socio_origen_id is not null;
create index if not exists idx_documentos_reemplazado_fk_v102 on public.documentos_socios(reemplazado_por) where reemplazado_por is not null;
create index if not exists idx_social_comentarios_autor_fk_v102 on public.kombax_social_comentarios(autor_social_id) where autor_social_id is not null;
create index if not exists idx_verificacion_eventos_perfil_fk_v102 on public.kombax_verificacion_eventos(perfil_directo_id) where perfil_directo_id is not null;
create index if not exists idx_solic_eliminacion_perfil_fk_v102 on public.kombax_solicitudes_eliminacion(perfil_directo_id) where perfil_directo_id is not null;
create index if not exists idx_social_bloqueos_objetivo_fk_v102 on public.kombax_social_bloqueos(bloqueado_social_id) where bloqueado_social_id is not null;

notify pgrst, 'reload schema';
