-- KOMBAX R72 / build 20123 live section 10
begin;
-- 10. R72 contract/policy refresh. QA legal drafts: legal review remains pending.
-- ---------------------------------------------------------------------------
update kombax_marketplace.policy_documents set status='retired',updated_at=now() where status='active';
insert into kombax_marketplace.policy_documents(policy_code,version,title,body,audience,required_for_seller,required_for_buyer,status,legal_review_status,effective_at) values
 ('marketplace_terms','1.2-r72-qa','Condiciones KOMBAX Showcase Marketplace',
 'BORRADOR QA · REVISIÓN JURÍDICA OBLIGATORIA. KOMBAX Showcase funciona como marketplace tecnológico. Los productos con compra directa son ofrecidos por el vendedor identificado. Los límites de catálogo de cada plan representan capacidad incluida; los planes compatibles pueden añadir bloques renovables y acumulables de +25 productos durante 30 días por 8 EUR, separados de Commerce. Archivar un producto libera capacidad activa y conserva su referencia e historial. Si un producto con pedidos, reseñas u otra trazabilidad relevante se elimina desde la gestión, KOMBAX puede retirarlo de la venta conservando el registro histórico necesario en lugar de destruirlo. Las reseñas, puntuaciones, fotografías y respuestas son contenido generado por usuarios sujeto a moderación. KOMBAX puede mostrar el distintivo Compra verificada solo cuando exista un pedido entregado atribuible al usuario y producto. Vendedor y comprador pueden reportar contenido; el vendedor no puede eliminar unilateralmente una crítica legítima. Los datos legales definitivos del operador deben completarse y someterse a revisión jurídica antes del lanzamiento comercial público.',
 'both',true,true,'active','pending',now()),
 ('seller_agreement','1.2-r72-qa','Acuerdo de vendedor KOMBAX Showcase',
 'BORRADOR QA · REVISIÓN JURÍDICA OBLIGATORIA. El vendedor actúa por cuenta propia y responde por legalidad, seguridad, descripción, precio, stock, entrega, garantías, devoluciones y atención. La venta directa exige verificación, políticas aceptadas y Stripe Connect operativo. La ampliación Showcase +25 añade 25 posiciones activas durante 30 días por 8 EUR, es acumulable y no activa Commerce ni modifica por sí sola la comisión de plataforma. Al expirar capacidad adicional KOMBAX no elimina referencias ni reputación: los productos que excedan la capacidad podrán quedar fuera de capacidad hasta que el vendedor renueve, amplíe, cambie de plan o archive referencias. Archivar libera capacidad conservando historial; la eliminación física se limita a fichas sin historial relevante. El vendedor acepta que las reseñas de usuarios, incluidas fotografías, puntuaciones y la marca Compra verificada, forman parte de la reputación del producto. Puede responder y reportar, pero no alterar ni borrar reseñas legítimas de terceros.',
 'seller',true,false,'active','pending',now()),
 ('buyer_protection','1.2-r72-qa','Protección del comprador KOMBAX Showcase',
 'BORRADOR QA · REVISIÓN JURÍDICA OBLIGATORIA. El comprador dispone de trazabilidad de pedidos, incidencias y reembolsos conforme a las condiciones aplicables. Puede publicar una valoración de producto habilitado para Commerce, con puntuación, texto y fotografías dentro de los límites técnicos. KOMBAX marcará Compra verificada únicamente cuando el sistema pueda vincular la reseña con un pedido entregado. El autor puede editar o retirar su aportación; la retirada deja de mostrar el contenido, pero KOMBAX puede conservar trazabilidad técnica o de moderación cuando sea necesario. Las reseñas deben ser veraces, respetuosas y no vulnerar derechos, privacidad ni propiedad intelectual.',
 'buyer',false,true,'active','pending',now()),
 ('prohibited_products','1.2-r72-qa','Política de productos prohibidos y restringidos',
 'BORRADOR QA · REVISIÓN JURÍDICA OBLIGATORIA. No pueden ofrecerse productos ilegales, falsificados, robados, peligrosos o sujetos a restricciones incompatibles con el servicio. El vendedor debe cumplir normativa de consumo, seguridad de producto, etiquetado, propiedad intelectual, fiscalidad y restricciones de edad o comercialización aplicables. KOMBAX puede retirar fichas, conservar evidencia histórica y suspender la venta ante riesgo o incumplimiento. Las reseñas o archivos multimedia tampoco pueden utilizarse para promocionar productos prohibidos, fraude o contenido ilícito.',
 'seller',true,false,'active','pending',now())
on conflict(policy_code,version) do update set title=excluded.title,body=excluded.body,audience=excluded.audience,required_for_seller=excluded.required_for_seller,required_for_buyer=excluded.required_for_buyer,status=excluded.status,legal_review_status=excluded.legal_review_status,effective_at=excluded.effective_at,updated_at=now();

update kombax_commercial.event_contract_documents set status='retired',updated_at=now() where policy_code='events_ticketing_agreement' and status='active';
insert into kombax_commercial.event_contract_documents(policy_code,version,title,body,required_for_ticketing,status,legal_review_status,effective_at) values
 ('events_ticketing_agreement','1.3-r72-qa','Acuerdo de servicio · KOMBAX Events + Ticketing',
 'BORRADOR OPERATIVO QA · REVISIÓN JURÍDICA OBLIGATORIA. El organizador vende entradas en su nombre mediante su cuenta Stripe Connect y mantiene la responsabilidad material sobre celebración, cambios, cancelaciones, atención y devoluciones. KOMBAX presta checkout, ticket digital, QR y control de acceso según la activación contratada. La ficha del evento puede incluir una comunidad con comentarios, respuestas, fotografías, vídeos cortos y valoraciones. KOMBAX puede identificar como Asistió al evento a un usuario cuando exista una entrada KOMBAX válida con check-in registrado. El organizador puede responder a valoraciones y reportar contenido, pero no eliminar unilateralmente críticas legítimas de terceros; la moderación corresponde a KOMBAX. Quien aporta contenido debe disponer de derechos y autorizaciones suficientes, respetar privacidad, menores, propiedad intelectual y normas de comunidad. Los datos legales definitivos y tratamiento fiscal deberán validarse antes del lanzamiento público.',
 true,'active','pending',now())
on conflict(policy_code,version) do update set title=excluded.title,body=excluded.body,required_for_ticketing=true,status='active',legal_review_status=excluded.legal_review_status,effective_at=excluded.effective_at,updated_at=now();

notify pgrst,'reload schema';
commit;
