begin;
create schema if not exists kombax_training;revoke all on schema kombax_training from public,anon,authenticated;
create table if not exists kombax_training.access_grants(id uuid primary key default gen_random_uuid(),subject_type text not null check(subject_type in('federation','professional_body','club','partner')),subject_id uuid not null,training_enabled boolean not null default false,agreement_reference text,note text,activated_by uuid references auth.users(id) on delete set null,activated_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(subject_type,subject_id));
create table if not exists kombax_training.programs(id uuid primary key default gen_random_uuid(),subject_type text not null,subject_id uuid not null,title text not null,description text,source_locale text not null default 'es',status text not null default 'draft' check(status in('draft','private','archived')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_training_programs_subject_r86 on kombax_training.programs(subject_type,subject_id,status);
create table if not exists kombax_training.modules(id uuid primary key default gen_random_uuid(),program_id uuid not null references kombax_training.programs(id) on delete cascade,title text not null,description text,position integer not null default 0,required boolean not null default true,created_at timestamptz not null default now());
create table if not exists kombax_training.resources(id uuid primary key default gen_random_uuid(),module_id uuid not null references kombax_training.modules(id) on delete cascade,title text not null,resource_type text not null check(resource_type in('document','video','link','practice','other')),storage_path text,external_url text,created_at timestamptz not null default now());
create table if not exists kombax_training.enrollments(id uuid primary key default gen_random_uuid(),program_id uuid not null references kombax_training.programs(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,status text not null default 'active' check(status in('active','completed','withdrawn','suspended')),started_at timestamptz not null default now(),completed_at timestamptz,unique(program_id,user_id));
create table if not exists kombax_training.evaluations(id uuid primary key default gen_random_uuid(),module_id uuid not null references kombax_training.modules(id) on delete cascade,title text not null,instructions text,configuration jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists kombax_training.evaluation_attempts(id uuid primary key default gen_random_uuid(),evaluation_id uuid not null references kombax_training.evaluations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,status text not null default 'submitted',score numeric,response jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists kombax_training.credentials(id uuid primary key default gen_random_uuid(),enrollment_id uuid not null references kombax_training.enrollments(id) on delete cascade,credential_type text not null check(credential_type in('certificate','license','attendance','other')),title text not null,reference text,issued_at timestamptz,expires_at timestamptz,document_path text,created_at timestamptz not null default now());
alter table kombax_training.access_grants enable row level security;alter table kombax_training.programs enable row level security;alter table kombax_training.modules enable row level security;alter table kombax_training.resources enable row level security;alter table kombax_training.enrollments enable row level security;alter table kombax_training.evaluations enable row level security;alter table kombax_training.evaluation_attempts enable row level security;alter table kombax_training.credentials enable row level security;
create or replace function public.app_kombax_training_status_r86(p_subject_type text,p_subject_id uuid) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare v_actor uuid:=(select auth.uid());v_enabled boolean:=false;v_agreement text;v_programs jsonb:='[]'::jsonb;v_enrollments jsonb:='[]'::jsonb;
begin
 if v_actor is null then raise exception 'AUTH_REQUIRED'; end if;if p_subject_type is null or p_subject_id is null then raise exception 'TRAINING_SUBJECT_REQUIRED'; end if;
 if p_subject_type in('club','federation') and not kombax_payments.can_access_subject_r80(v_actor,p_subject_type,p_subject_id,false) then raise exception 'TRAINING_SUBJECT_FORBIDDEN'; end if;
 select g.training_enabled,g.agreement_reference into v_enabled,v_agreement from kombax_training.access_grants g where g.subject_type=p_subject_type and g.subject_id=p_subject_id;
 if not coalesce(v_enabled,false) then return jsonb_build_object('enabled',false,'subject_type',p_subject_type,'subject_id',p_subject_id,'programs','[]'::jsonb,'enrollments','[]'::jsonb); end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'title',p.title,'description',p.description,'status',p.status,'source_locale',p.source_locale,'module_count',(select count(*) from kombax_training.modules m where m.program_id=p.id)) order by p.created_at desc),'[]'::jsonb) into v_programs from kombax_training.programs p where p.subject_type=p_subject_type and p.subject_id=p_subject_id and p.status='private';
 select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'program_id',e.program_id,'status',e.status,'started_at',e.started_at,'completed_at',e.completed_at) order by e.started_at desc),'[]'::jsonb) into v_enrollments from kombax_training.enrollments e join kombax_training.programs p on p.id=e.program_id where e.user_id=v_actor and p.subject_type=p_subject_type and p.subject_id=p_subject_id;
 return jsonb_build_object('enabled',true,'subject_type',p_subject_type,'subject_id',p_subject_id,'agreement_reference',v_agreement,'programs',v_programs,'enrollments',v_enrollments);
end $$;
revoke all on function public.app_kombax_training_status_r86(text,uuid) from public,anon;grant execute on function public.app_kombax_training_status_r86(text,uuid) to authenticated;
notify pgrst,'reload schema';commit;
