begin;
create schema if not exists kombax_consulting;
revoke all on schema kombax_consulting from public,anon,authenticated;
do $$ begin create type kombax_consulting.request_status as enum ('requested','classified','information_pending','quoted','accepted','paid','in_review','delivered','closed','cancelled'); exception when duplicate_object then null; end $$;
create table if not exists kombax_consulting.requests(
  id uuid primary key default gen_random_uuid(),requester_user_id uuid not null references auth.users(id) on delete cascade,subject_type text,subject_id uuid,entity_type text,territory text,municipality text,discipline text,
  consultation_type text not null,target_date date,summary text not null,minors_involved boolean not null default false,foreign_athletes boolean not null default false,ticket_sales boolean not null default false,venue_defined boolean not null default false,
  federation_involved text,status kombax_consulting.request_status not null default 'requested',classification_note text,quote_amount_minor integer check(quote_amount_minor is null or quote_amount_minor>=0),quote_currency text not null default 'EUR' check(char_length(quote_currency)=3),
  quote_note text,quote_valid_until date,quote_accepted_at timestamptz,payment_status text not null default 'not_available' check(payment_status in('not_available','pending_activation','pending','paid','failed','refunded')),payment_reference text,
  assigned_to uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_consulting_requests_requester_r85 on kombax_consulting.requests(requester_user_id,created_at desc);
create index if not exists idx_consulting_requests_status_r85 on kombax_consulting.requests(status,updated_at desc);
create table if not exists kombax_consulting.documents(id uuid primary key default gen_random_uuid(),request_id uuid not null references kombax_consulting.requests(id) on delete cascade,uploaded_by uuid not null references auth.users(id) on delete cascade,storage_path text not null unique,original_name text not null,mime_type text,size_bytes bigint check(size_bytes is null or size_bytes>=0),created_at timestamptz not null default now());
create index if not exists idx_consulting_documents_request_r85 on kombax_consulting.documents(request_id,created_at desc);
create table if not exists kombax_consulting.events(id bigint generated always as identity primary key,request_id uuid not null references kombax_consulting.requests(id) on delete cascade,actor_user_id uuid references auth.users(id) on delete set null,event_type text not null,from_status text,to_status text,detail jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists idx_consulting_events_request_r85 on kombax_consulting.events(request_id,created_at desc);
alter table kombax_consulting.requests enable row level security;alter table kombax_consulting.documents enable row level security;alter table kombax_consulting.events enable row level security;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('kombax-consulting-docs','kombax-consulting-docs',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp']::text[])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists consulting_docs_owner_insert_r85 on storage.objects;create policy consulting_docs_owner_insert_r85 on storage.objects for insert to authenticated with check(bucket_id='kombax-consulting-docs' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists consulting_docs_owner_select_r85 on storage.objects;create policy consulting_docs_owner_select_r85 on storage.objects for select to authenticated using(bucket_id='kombax-consulting-docs' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists consulting_docs_owner_delete_r85 on storage.objects;create policy consulting_docs_owner_delete_r85 on storage.objects for delete to authenticated using(bucket_id='kombax-consulting-docs' and (storage.foldername(name))[1]=(select auth.uid())::text);
create or replace function public.app_kombax_consulting_mine_r85() returns jsonb language sql stable security definer set search_path='' as $$
  select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'subject_type',r.subject_type,'subject_id',r.subject_id,'entity_type',r.entity_type,'territory',r.territory,'municipality',r.municipality,'discipline',r.discipline,'consultation_type',r.consultation_type,'target_date',r.target_date,'summary',r.summary,
  'minors_involved',r.minors_involved,'foreign_athletes',r.foreign_athletes,'ticket_sales',r.ticket_sales,'venue_defined',r.venue_defined,'federation_involved',r.federation_involved,'status',r.status,'classification_note',r.classification_note,
  'quote_amount_minor',r.quote_amount_minor,'quote_currency',r.quote_currency,'quote_note',r.quote_note,'quote_valid_until',r.quote_valid_until,'quote_accepted_at',r.quote_accepted_at,'payment_status',r.payment_status,'created_at',r.created_at,'updated_at',r.updated_at,
  'documents',coalesce((select jsonb_agg(jsonb_build_object('id',d.id,'original_name',d.original_name,'mime_type',d.mime_type,'size_bytes',d.size_bytes,'storage_path',d.storage_path,'created_at',d.created_at) order by d.created_at desc) from kombax_consulting.documents d where d.request_id=r.id),'[]'::jsonb),
  'events',coalesce((select jsonb_agg(jsonb_build_object('event_type',e.event_type,'from_status',e.from_status,'to_status',e.to_status,'detail',e.detail,'created_at',e.created_at) order by e.created_at desc) from kombax_consulting.events e where e.request_id=r.id),'[]'::jsonb)) order by r.created_at desc),'[]'::jsonb)
  from kombax_consulting.requests r where r.requester_user_id=(select auth.uid());
$$;
create or replace function public.app_kombax_consulting_mutate_r85(p_operation text,p_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_actor uuid:=(select auth.uid());v_request kombax_consulting.requests;v_id uuid;v_owner boolean:=false;v_status kombax_consulting.request_status;v_path text;
begin
 if v_actor is null then raise exception 'AUTH_REQUIRED'; end if;v_owner:=coalesce(public.app_kombax_es_platform_admin_v055(),false);
 if p_operation='request.create' then
   if length(trim(coalesce(p_payload->>'consultation_type','')))<2 or length(trim(coalesce(p_payload->>'summary','')))<10 then raise exception 'CONSULTING_REQUIRED_FIELDS'; end if;
   if nullif(p_payload->>'subject_type','') is not null and nullif(p_payload->>'subject_id','') is not null and not kombax_payments.can_access_subject_r80(v_actor,p_payload->>'subject_type',(p_payload->>'subject_id')::uuid,false) then raise exception 'CONSULTING_SUBJECT_FORBIDDEN'; end if;
   insert into kombax_consulting.requests(requester_user_id,subject_type,subject_id,entity_type,territory,municipality,discipline,consultation_type,target_date,summary,minors_involved,foreign_athletes,ticket_sales,venue_defined,federation_involved)
   values(v_actor,nullif(p_payload->>'subject_type',''),nullif(p_payload->>'subject_id','')::uuid,nullif(p_payload->>'entity_type',''),nullif(p_payload->>'territory',''),nullif(p_payload->>'municipality',''),nullif(p_payload->>'discipline',''),trim(p_payload->>'consultation_type'),nullif(p_payload->>'target_date','')::date,trim(p_payload->>'summary'),coalesce((p_payload->>'minors_involved')::boolean,false),coalesce((p_payload->>'foreign_athletes')::boolean,false),coalesce((p_payload->>'ticket_sales')::boolean,false),coalesce((p_payload->>'venue_defined')::boolean,false),nullif(p_payload->>'federation_involved','')) returning * into v_request;
   insert into kombax_consulting.events(request_id,actor_user_id,event_type,to_status) values(v_request.id,v_actor,'request.created','requested');return to_jsonb(v_request);
 elsif p_operation='document.add' then
   v_id=(p_payload->>'request_id')::uuid;v_path=trim(coalesce(p_payload->>'storage_path',''));select * into strict v_request from kombax_consulting.requests where id=v_id;
   if v_request.requester_user_id<>v_actor and not v_owner then raise exception 'CONSULTING_REQUEST_FORBIDDEN'; end if;if v_path='' or split_part(v_path,'/',1)<>v_actor::text then raise exception 'CONSULTING_DOCUMENT_PATH_INVALID'; end if;
   insert into kombax_consulting.documents(request_id,uploaded_by,storage_path,original_name,mime_type,size_bytes) values(v_id,v_actor,v_path,left(coalesce(p_payload->>'original_name','documento'),255),nullif(p_payload->>'mime_type',''),nullif(p_payload->>'size_bytes','')::bigint) returning id into v_id;
   insert into kombax_consulting.events(request_id,actor_user_id,event_type,detail) values(v_request.id,v_actor,'document.added',jsonb_build_object('document_id',v_id));return jsonb_build_object('ok',true,'document_id',v_id);
 elsif p_operation='request.accept_quote' then
   v_id=(p_payload->>'request_id')::uuid;select * into strict v_request from kombax_consulting.requests where id=v_id for update;if v_request.requester_user_id<>v_actor then raise exception 'CONSULTING_REQUEST_FORBIDDEN'; end if;if v_request.status<>'quoted' or v_request.quote_amount_minor is null then raise exception 'CONSULTING_QUOTE_NOT_READY'; end if;
   update kombax_consulting.requests set status='accepted',quote_accepted_at=now(),payment_status='pending_activation',updated_at=now() where id=v_id;insert into kombax_consulting.events(request_id,actor_user_id,event_type,from_status,to_status,detail) values(v_id,v_actor,'quote.accepted','quoted','accepted',jsonb_build_object('billing','pending_activation'));return jsonb_build_object('ok',true,'status','accepted','payment_status','pending_activation');
 elsif p_operation='owner.update' then
   if not v_owner then raise exception 'PLATFORM_ADMIN_REQUIRED'; end if;v_id=(p_payload->>'request_id')::uuid;select * into strict v_request from kombax_consulting.requests where id=v_id for update;v_status=coalesce(nullif(p_payload->>'status','')::kombax_consulting.request_status,v_request.status);
   if nullif(p_payload->>'quote_amount_minor','') is not null and (p_payload->>'quote_amount_minor')::integer<0 then raise exception 'CONSULTING_QUOTE_INVALID'; end if;
   update kombax_consulting.requests set status=v_status,classification_note=coalesce(p_payload->>'classification_note',classification_note),quote_amount_minor=case when p_payload ? 'quote_amount_minor' then nullif(p_payload->>'quote_amount_minor','')::integer else quote_amount_minor end,quote_note=coalesce(p_payload->>'quote_note',quote_note),quote_valid_until=case when p_payload ? 'quote_valid_until' then nullif(p_payload->>'quote_valid_until','')::date else quote_valid_until end,assigned_to=case when p_payload ? 'assigned_to' then nullif(p_payload->>'assigned_to','')::uuid else assigned_to end,updated_at=now() where id=v_id;
   insert into kombax_consulting.events(request_id,actor_user_id,event_type,from_status,to_status,detail) values(v_id,v_actor,'owner.updated',v_request.status::text,v_status::text,p_payload-'request_id');return jsonb_build_object('ok',true,'status',v_status);
 elsif p_operation='request.close' then
   v_id=(p_payload->>'request_id')::uuid;select * into strict v_request from kombax_consulting.requests where id=v_id for update;if v_request.requester_user_id<>v_actor and not v_owner then raise exception 'CONSULTING_REQUEST_FORBIDDEN'; end if;if v_request.status not in ('delivered','cancelled') and not v_owner then raise exception 'CONSULTING_CLOSE_NOT_ALLOWED'; end if;
   update kombax_consulting.requests set status='closed',updated_at=now() where id=v_id;insert into kombax_consulting.events(request_id,actor_user_id,event_type,from_status,to_status) values(v_id,v_actor,'request.closed',v_request.status::text,'closed');return jsonb_build_object('ok',true,'status','closed');
 end if;raise exception 'CONSULTING_OPERATION_INVALID';
end $$;
revoke all on function public.app_kombax_consulting_mine_r85() from public,anon;grant execute on function public.app_kombax_consulting_mine_r85() to authenticated;
revoke all on function public.app_kombax_consulting_mutate_r85(text,jsonb) from public,anon;grant execute on function public.app_kombax_consulting_mutate_r85(text,jsonb) to authenticated;
notify pgrst,'reload schema';commit;
